
CREATE TABLE #TABLE_NAME# (
    id INT NOT NULL,
    path VARCHAR(512) NOT NULL,
    signature VARCHAR(64)
);

ALTER TABLE #TABLE_NAME#
	ADD CONSTRAINT pk_#TABLE_NAME#
		PRIMARY KEY (id) ;

ALTER TABLE #TABLE_NAME#
	ADD CONSTRAINT fk_#TABLE_NAME#
		FOREIGN KEY (id)
			REFERENCES t_inventorysm (id)
				ON DELETE CASCADE ;

CREATE TRIGGER tr_#TABLE_NAME#_ins AFTER INSERT
	ON #TABLE_NAME# 
		FOR EACH ROW EXECUTE PROCEDURE tf_inserteventtableitem('#TABLE_NAME#', 'INS') ;

CREATE TRIGGER tr_#TABLE_NAME#_upd AFTER UPDATE
	ON #TABLE_NAME# 
		FOR EACH ROW EXECUTE PROCEDURE tf_inserteventtableitem('#TABLE_NAME#', 'UPD') ;


