#
#	Copyright 1995-2016, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$
#
#	$Prod: A.C.S. Order Generator $
#	$Id$
#
#   $Log$
#   Revision 5.2  2017/03/20 10:22:48  clanas
#   updated to use the new dependency machanism
#
#   Revision 5.1  2016/03/21 10:10:02  marpas
#   adapting to last dev environment.
#   now relies on HAS_MISSION_INCLUDE
#
#   Revision 5.0  2013/06/19 14:33:33  marpas
#   adoption of libException 5.x standards
#
#   Revision 2.25  2013/04/24 10:47:11  chicas
#   updated LIB
#
#   Revision 2.24  2013/03/29 19:56:16  marpas
#   removing useless libraries
#
#   Revision 2.23  2013/03/08 17:32:42  marpas
#   libDbBasic no longer used
#
#   Revision 2.22  2013/02/28 13:57:09  marpas
#   no libMessage dependency
#
#   Revision 2.21  2011/11/23 16:42:22  serfol
#   adding the CSCLirsen project
#
#   Revision 2.20  2009/03/06 10:04:41  ivafam
#   Aligned GoceLTA section to Goce
#
#   Revision 2.19  2009/01/28 13:21:10  marpas
#   useless libraries removed
#
#   Revision 2.18  2008/12/04 18:18:30  ivafam
#   libResultManager removed
#
#   Revision 2.17  2008/12/02 11:25:22  marpas
#   bProc not longer directly referenced
#
#   Revision 2.16  2008/11/28 11:24:17  giapas
#   ExplOrbWrapperDb added for GoceLTA.
#
#   Revision 2.15  2008/11/21 18:59:58  marpas
#   minor changes
#
#   Revision 2.14  2008/09/22 09:08:50  danalt
#   added HAS_MISSION includes
#
#   Revision 2.13  2008/06/23 09:19:53  ivafam
#   Updated project section
#
#   Revision 2.12  2008/05/30 12:24:59  giucas
#   DAPSBrazil project section added
#
#   Revision 2.11  2007/05/18 13:58:31  giucas
#   Added missing ExplOrbWrapperDb and ExplWrapperDb in Goce project
#
#   Revision 2.10  2007/04/20 10:31:57  ivafam
#   Patch to remove libProc dependence of libGfeSatStore
#
#   Revision 2.9  2007/04/19 07:57:48  giucas
#   Missing OBTConverter added to CSLibya section
#
#   Revision 2.8  2007/04/19 07:49:00  giucas
#   CSLibya project added
#
#   Revision 2.7  2007/04/11 15:05:59  clanas
#   implemented Orbit propagator with Db separation
#
#   Revision 2.6  2007/03/06 16:52:53  crivig
#   removed dependency on QtException
#
#   Revision 2.5  2007/01/26 10:47:20  giapas
#   AuxFileHandling libs added for ADM
#
#   Revision 2.4  2007/01/10 14:25:18  giucas
#   Added libAuxFileHandlingDefault in Cosmo section
#
#   Revision 2.3  2007/01/10 11:44:42  giucas
#   Updated for new CFI 3.5 integration
#
#   Revision 2.2  2006/09/11 15:00:29  giapas
#   ADM specific section added.
#
#   Revision 2.1  2006/06/21 13:01:04  ivafam
#   Method compareNoCase replaced with StringUtils::compareNoCase
#
#   Revision 2.0  2006/02/28 15:49:11  paoscu
#   Exception 2.1 I/F adopted
#
#   Revision 1.44  2006/02/27 15:58:47  danalt
#   changed libAuxFileHandling in libAuxFileHandlingBase
#
#   Revision 1.43  2005/12/16 14:14:47  giapas
#   Removed Gocecmf project.
#
#   Revision 1.42  2005/12/16 13:27:54  giapas
#   Added Gocecmf project.
#
#   Revision 1.41  2005/11/24 18:03:58  giapas
#   Fixed to compile in CompactStation environment.
#
#   Revision 1.40  2005/11/15 15:36:20  giapas
#   Fixed CompactStation section.
#
#   Revision 1.39  2005/11/14 18:22:14  giapas
#   Section for CompactStation added.
#
#   Revision 1.38  2005/11/04 09:28:27  danalt
#   added libssl
#
#   Revision 1.37  2005/11/03 16:54:09  marpas
#   SSL and CRC libs added
#
#   Revision 1.36  2005/10/06 15:43:25  marfav
#   Plugin support added
#   Orders creator moved to specialized libraries
#
#   Revision 1.35  2005/09/21 15:08:26  danalt
#   modified PROJECTPROP for COSMO
#
#   Revision 1.34  2005/07/28 17:49:47  marpas
#   getting rid of libARFClient and all HSM libraries.
#   Loading them will be a task of the AcsIsm plugin if configured
#
#   Revision 1.33  2005/07/22 13:34:29  marfav
#   Modified CMAPI library name
#
#   Revision 1.32  2005/07/14 11:10:11  ivafam
#   Added project GoceLTA
#
#   Revision 1.31  2005/06/21 12:25:52  marpas
#   GroupedCollection algorithm implemented
#
#   Revision 1.30  2005/06/20 21:25:22  marpas
#   1) Anx2Anx take into account the orbit mode and multiple orbits. Moreover it has parameters differentiated on triggering file type basis
#   2) Paremeters MaxWaitingTime and its derivated, MaxMergeDistance and its derivated are now differentiated on file type basis for merging algoritms.
#   3) OrdersGeneration.xml file under configuration for Goce Project.
#
#   Revision 1.29  2005/06/15 12:14:13  integrator
#   Added libStorageManager
#
#   Revision 1.28  2005/06/13 09:48:53  danalt
#   added lTimeConverter in Cosmo
#
#   Revision 1.27  2005/06/13 08:40:16  marpas
#   COSMO now uses ACS converters libraries
#
#   Revision 1.26  2005/02/18 10:59:08  ivafam
#   Added GTS project
#
#   Revision 1.25  2005/01/11 15:50:03  clanas
#   Removed ACE lib as it is not longer required by HSM Client lib
#
#   Revision 1.24  2004/10/28 14:51:46  marpas
#   files added/removed
#
#   Revision 1.23  2004/10/15 09:55:16  integrator
#   Added libFeatures
#
#   Revision 1.22  2004/10/11 09:25:35  marfav
#   dbCosmoExtended library added
#
#   Revision 1.21  2004/10/07 19:03:45  marpas
#   new files for external RPRO orders NRT like
#
#   Revision 1.20  2004/10/05 08:04:37  marpas
#   fixed
#
#   Revision 1.19  2004/10/01 17:15:24  marpas
#   new M&C
#
#   Revision 1.18  2004/09/07 14:09:58  marpas
#   Makefile.Station removed
#   supported projects Cosmo, Cryosat, Envisat
#
#   Revision 1.17  2004/09/06 09:10:20  danalt
#   Cosmo MultiMission Environment Support Added
#
#   Revision 1.16  2004/05/18 10:12:12  marpas
#   INFORMIX multithread libs adopted
#
#   Revision 1.15  2004/03/23 08:59:18  marpas
#   Orbit wrapper not initialized nor linked
#
#   Revision 1.14  2004/03/19 11:12:14  achval
#   remove small bug cut/paste into NRT order generation
#
#   Revision 1.13  2004/03/08 23:31:00  marpas
#   Simulation mode introduced
#
#   Revision 1.12  2004/03/01 18:19:16  marpas
#   Level2 anx 2 anx currently under implementation
#
#   Revision 1.11  2003/10/16 15:40:37  paoscu
#   -lRegExp Added
#
#   Revision 1.10  2003/07/18 19:55:20  marpas
#   -O3 flag supported in template instantiation
#
#   Revision 1.9  2003/07/17 22:42:23  marpas
#   Optimization flag overridden
#   compilation warning removed
#
#   Revision 1.8  2003/06/04 19:33:53  marpas
#   V1 test.
#
#   Revision 1.7  2003/03/13 17:32:52  marpas
#   fixed
#
#   Revision 1.6  2003/03/13 17:32:01  marpas
#   some improvements
#
#   Revision 1.5  2003/02/20 08:48:41  marpas
#   NRT test
#
#   Revision 1.4  2003/02/18 16:57:23  marpas
#   test in progress
#
#   Revision 1.3  2003/02/07 17:48:46  marpas
#   work in progress
#
#   Revision 1.2  2003/02/07 10:36:55  marpas
#   work in progress
#
#   Revision 1.1.1.1  2003/02/04 18:47:30  marpas
#   Import Order Generator
#

include ../../common/commondefs.mk


  USERFLAG = $(PROJECTFLAG)

  LIBRARYNAME = OrderGenerator

  VERSIONFILE = ogV.C



   C++SOURCES = \
 		OrderGenerator.C \
		OGListener.C \
		ogV.C



#prevent remotion of objects, target and versioning
      VERSIONRULE =
      TARGETFILES = OrderGenerator
      CLEANTESTRULE=

SPECIFICLIBS= \
    $(PROJECT_ORBITPROPAGATOR) \
    $(PROJECT_TIMECONVERTER)


$(TARGETFILES) : $(OBJECTS)
	$(CXX) $(LDOPTS) $(CXXFLAGS) $(LIBRARYPATH) -o $@  $(OBJECTS)  $(DEPLIBS) $(PRJLIBS) $(SPECIFICLIBS)

cleanspecific:

helpspecific:

include ../../common/commonrules.mk

