#
#	Copyright 1995-2013, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libPackageCirculatorTask$
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 1.1.1.1  2013/06/18 16:38:21  nicvac
#	Import libPackageCirculatorTask
#	
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libPackageCirculatorTask

VERSIONFILE = PackageCirculatorTaskV.C

COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)

C++SOURCES = PackageCirculatorTask.C \
	PackageCirculatorTaskV.C

C++INCLUDE = PackageCirculatorTask.h \

DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared


#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk
