#
#	Copyright 1995-2014, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	Authors: 
#
#	$Prod: A.C.S. Template StringKey Based Factory Library Makefile $
#	
#	$Id$
#
#	$Log$
#	Revision 1.5  2016/11/21 16:08:17  marfav
#	S3MPM-847
#	Fixed library dependancies
#	
#	Revision 1.4  2014/05/16 09:33:44  marpas
#	fixing helpspecific target
#	
#	Revision 1.3  2006/08/23 14:51:56  paoscu
#	Shared libraries dependencies added
#	
#	Revision 1.2  2005/06/20 15:41:07  enrcar
#	INCLUDEPATH REMOVED
#	
#	Revision 1.1.1.1  2004/04/07 13:30:10  marfav
#	Import libStringKeyFactory
#	
#
#
include ../../common/commondefs.mk


  LIBRARYNAME =	libStringKeyFactory

  VERSIONFILE =	strkfV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
		StringKeyFactory.C \
		strkfV.C \


   C++INCLUDE = \
		StringKeyFactory.h \





DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared 




DSOSPECIFICDEPS =



#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

helpspecific:

include ../../common/commonrules.mk
