#
#	Copyright 2019, Exprivia - DFDA-AS
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Exprivia SpA.
#
#	$Author: $
#
#	$Prod: LTA rest interface $
#


include ../../common/commondefs.mk

  LIBRARYNAME =	libLTARest

  VERSIONFILE = LTARestV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
        NotificationServiceRequestPayload.C \
        NotificationServiceResponsePayload.C \
        EstimationTimeServiceRequestPayload.C \
        EstimationTimeServiceResponsePayload.C \
        NotificationServiceClient.C \
        QuotaServiceResponsePayload.C \
        QuotaServiceCancelOrderRequestPayload.C \
        QuotaServiceCheckBatchQuotaRequestPayload.C \
        QuotaServiceCheckOrderQuotaRequestPayload.C \
        QuotaServiceCheckDownloadQuotaVolumeRequestPayload.C \
        QuotaServiceCheckParallelOrderQuotaRequestPayload.C \
        QuotaServiceUpdateOrderRegistryRequestPayload.C \
        QuotaServiceGetDownloadTokenRequestPayload.C \
        QuotaServiceUseDownloadTokenRequestPayload.C \
        QuotaServiceReleaseDownloadTokenRequestPayload.C \
        QuotaServiceNotifyDownloadStatusRequestPayload.C \
        RetrieveServiceGetProductRequestPayload.C \
        RetrieveServiceGetProductResponsePayload.C \
        RetrieveServiceGetFileStatusRequestPayload.C \
        RetrieveServiceGetFileStatusResponsePayload.C \
        RetrieveServiceMakeBulkRequestPayload.C \
        RetrieveServiceMakeBulkResponsePayload.C \
        RetrieveServiceGetBulkStatusRequestPayload.C \
        RetrieveServiceGetBulkStatusResponsePayload.C \
        RetrieveServiceGetBulkDetailsRequestPayload.C \
        RetrieveServiceGetBulkDetailsResponsePayload.C \
        RetrieveServiceGetBatchDetailsRequestPayload.C \
        RetrieveServiceGetBatchDetailsResponsePayload.C \
        ODataQueryProductsResponsePayload.C \
        ODataOrderRequestPayload.C \
        ODataOrderResponsePayload.C \
        ODataBulkCreateRequestPayload.C \
        ODataBulkCreateResponsePayload.C \
        ODataBatchOrderResponsePayload.C \
        ODataBatchTriggeringRequestPayload.C \
	ODataNotificationServicePayload.C \
	ODataSubscriptionRequestPayload.C \
	ODataSubscriptionResponsePayload.C \
        LTAUploadTargetAIPResponsePayload.C \
        LTAAvailableDownloadAIPsResponsePayload.C \
        DirectDLResolverResolveUUIDResponsePayload.C \
	ProductOrderResponsePayload.C \
	S3AwsUploaderRequestPayload.C \
        GenericAuthHandler.C \
        BaseAuthHandler.C \
        OAuth2Handler.C \
        LTARestClient.C \
        LTARestV.C

   C++INCLUDE = \
        NotificationServiceRequestPayload.h \
        NotificationServiceResponsePayload.h \
        EstimationTimeServiceRequestPayload.h \
        EstimationTimeServiceResponsePayload.h \
        NotificationServiceClient.h \
        QuotaServiceResponsePayload.h \
        QuotaServicePayloadsExceptions.h \
        QuotaServiceCancelOrderRequestPayload.h \
        QuotaServiceCheckBatchQuotaRequestPayload.h \
        QuotaServiceCheckOrderQuotaRequestPayload.h \
        QuotaServiceCheckDownloadQuotaVolumeRequestPayload.h \
        QuotaServiceCheckParallelOrderQuotaRequestPayload.h \
        QuotaServiceUpdateOrderRegistryRequestPayload.h \
        QuotaServiceGetDownloadTokenRequestPayload.h \
        QuotaServiceUseDownloadTokenRequestPayload.h \
        QuotaServiceReleaseDownloadTokenRequestPayload.h \
        QuotaServiceNotifyDownloadStatusRequestPayload.h \
        RetrieveServiceResponseErrorCodeEnum.h \
        RetrieveServiceGetProductRequestPayload.h \
        RetrieveServiceGetProductResponsePayload.h \
        RetrieveServiceGetFileStatusRequestPayload.h \
        RetrieveServiceGetFileStatusResponsePayload.h \
        RetrieveServiceMakeBulkRequestPayload.h \
        RetrieveServiceMakeBulkResponsePayload.h \
        RetrieveServiceGetBulkStatusRequestPayload.h \
        RetrieveServiceGetBulkStatusResponsePayload.h \
        RetrieveServiceGetBulkDetailsRequestPayload.h \
        RetrieveServiceGetBulkDetailsResponsePayload.h \
        RetrieveServiceGetBatchDetailsRequestPayload.h \
        RetrieveServiceGetBatchDetailsResponsePayload.h \
        ODataQueryProductsResponsePayload.h \
        ODataOrderRequestPayload.h \
        ODataOrderResponsePayload.h \
        ODataBulkCreateRequestPayload.h \
        ODataBulkCreateResponsePayload.h \
        ODataBatchOrderResponsePayload.h \
        ODataBatchTriggeringRequestPayload.h \
	ODataNotificationServicePayload.h \
	ODataSubscriptionRequestPayload.h \
	ODataSubscriptionResponsePayload.h \
        LTAUploadTargetAIPResponsePayload.h \
        LTAAvailableDownloadAIPsResponsePayload.h \
        DirectDLResolverResolveUUIDResponsePayload.h \
	ProductOrderResponsePayload.h \
	S3AwsUploaderRequestPayload.h \
        GenericAuthHandler.h \
        BaseAuthHandler.h \
        OAuth2Handler.h \
        LTARestClient.h \
        


COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)


# DO NOT DELETE
#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


include ../../common/commonrules.mk

