#
#	Copyright 1995-2013, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libUserNotification$
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 1.3  2013/05/27 12:18:53  nicvac
#	DSODEPEND
#	
#	Revision 1.2  2013/05/24 18:31:27  nicvac
#	S2PDGS-308: Inventory notifications implemented.
#	
#	Revision 1.1.1.1  2013/05/23 13:41:01  nicvac
#	Import libUserNotification
#	
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libUserNotification

VERSIONFILE = UserNotificationV.C

CUSTOM_INCLUDEPATH =

CUSTOM_LIBPATH =

CSOURCES =	

CINCLUDE =	

C++SOURCES = \
	UserNotification.C \
	EmailUserNotification.C \
	FacebookUserNotification.C \
	InventoryEmailNotification.C \
	UserNotifier.C \
	UserNotificationV.C \


C++INCLUDE = \
	UserNotification.h \
	EmailUserNotification.h \
	FacebookUserNotification.h \
	InventoryEmailNotification.h \
	UserNotifier.h \


DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

DSOSPECIFICDEPS =


