#
#	Copyright 1995-2018, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$
#
#	$Prod: libACSStations Library Makefile $
#
#	$Id$
#
#       $Log$
#       Revision 1.2  2008/05/22 16:36:40  giucas
#       Python wrapper enabled
#
#       Revision 1.1.1.1  2008/05/22 12:34:01  giucas
#       Moved ACSStationsWrapper and python wrapper from libSgiIncludes
#
#
#
#

include ../../common/commondefs.mk

  LIBRARYNAME =	libACSStations

  VERSIONFILE = acsStatV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
		acsStatV.C \
		ACSStationsWrapper.C \
		
   C++INCLUDE = \
		ACSStationsWrapper.h \

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:

install:

# DO NOT DELETE


include ../../common/commonrules.mk

