// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:03  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/04/19 15:23:45  marpas
	coding best practices application in progress
	
	Revision 5.4  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:53  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:20  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.4  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.3  2012/06/15 09:54:29  marpas
	removing warning related to virtual method hiding
	
	Revision 2.2  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.1  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.0  2006/02/28 09:09:34  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.9  2005/06/17 10:31:54  marpas
	std namespaces took into consideration
	
	Revision 1.8  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.7  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.6  2004/04/13 16:57:08  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.5  2004/03/04 18:54:08  paoscu
	Class generated again. New clob management.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbConfigurationStyleSheet_H_
#define _dbConfigurationStyleSheet_H_

#include <exException.h>
#include <dbPersistent.h>

_ACS_BEGIN_NAMESPACE(acs)

class dbCryosatFactory ;

class dbRow ;
class rsResourceSet ;
class XMLOstream ;

//
//
//
// class dbConfigurationStyleSheet
//
//
//
class dbConfigurationStyleSheet :
	public dbPersistent
{
	friend class dbCryosatFactory ; // PRQA S 2107
public:

	virtual ~dbConfigurationStyleSheet() throw() ;
	dbConfigurationStyleSheet &operator=(const dbConfigurationStyleSheet &) ; // operator =

	static  std::string staticClassName() ;
	virtual dbPersistent *clone() const ; // PRQA S 2502

	// inherited from dbPersistent
	virtual std::string className() const ;
	virtual void reset() ; // initialize the class
	virtual IdType save(dbConnection &)  ; // save the data in database
	virtual bool load(dbConnection & , IdType id=0)  ; // load the class from the database. Return true if obect exist
	virtual IdType update(dbConnection &)  ; // update an existing instance in database
	virtual IdType remove(dbConnection &)  ; // remove the class from the database // PRQA S 2502
	virtual bool validate() const  ; // True if the class have valid parameters, false otherwise
	virtual void exportObj(rsResourceSet &s) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &s)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &xst) const ; // export the class to XML stream

	int loadRow(const dbRow &, int offset=0) ;

	void setName(const std::string &) ;
	const std::string &getName(bool *set=0) const ;
	void unsetName();

	void setVersion(const std::string &) ;
	const std::string &getVersion(bool *set=0) const ;
	void unsetVersion();

	// replace the file of an existing record
	void replaceStyleSheetFile(const std::string &path, dbConnection &) ;
	// save the file on disk
	void saveStyleSheetFile(const std::string &path, const std::string &filename, dbConnection &) ;

	// This method return a hint for the filename
	std::string getStyleSheetFileName() const ;
	// set/get the original file name
	void setStyleSheetUploadFileName(const std::string &) ;
	std::string getStyleSheetUploadFileName(bool *set=0) const;

	static std::string getFields() ;
	static std::string getTable() ;
	static std::string getOrderBy() ;

	// output to stream
	virtual void writeTo(std::ostream &) const ;
	virtual void writeTo(exostream &) const ;


protected:
	dbConfigurationStyleSheet() ;
	dbConfigurationStyleSheet(const dbConfigurationStyleSheet &) ;


private:
	std::string _name ;
	bool _nameSet ;

	std::string _version ;
	bool _versionSet ;

	std::string _styleSheetUploadFileName ;
	bool _styleSheetUploadFileNameSet ;

	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbConfigurationStyleSheet)
} ;


_ACS_END_NAMESPACE

#endif // _dbConfigurationStyleSheet_H_
