/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/27 08:56:02  damdec
	CGSACQ-86: compilation warnings fixed.
	
	Revision 6.0  2016/07/07 13:44:03  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.4  2016/04/19 15:23:45  marpas
	coding best practices application in progress
	
	Revision 5.3  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:53  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:20  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.8  2013/04/12 12:14:37  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.7  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.6  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.5  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.4  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.3  2010/03/05 15:09:10  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.2  2008/09/23 08:27:37  crivig
	porting to postgres8
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:34  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.21  2006/01/20 10:19:55  enrcar
	EC:: define FORCE_DBEXPRESS_QUERY introduced to allow safer tests on dbexpress-ported queries
	
	Revision 1.20  2006/01/13 13:49:11  enrcar
	updated to dbexprss
	
	Revision 1.29  2005/11/04 18:01:18  danalt
	*** empty log message ***
	
	Revision 1.19  2005/06/15 07:44:49  integrator
	multiple storage manager implemented
	
	Revision 1.18  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.17  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.16  2004/10/04 15:13:52  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.15  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.14  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.13  2004/05/03 14:55:33  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.12  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.11  2004/04/13 16:57:08  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.10  2004/03/04 18:54:08  paoscu
	Class generated again. New clob management.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbConfigurationStyleSheet.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <File.h>
#include <unistd.h>
#include <XMLOstream.h>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbConfigurationStyleSheet)

// constructor
dbConfigurationStyleSheet::dbConfigurationStyleSheet():
	dbPersistent(),
	_name() ,
	_nameSet(false) ,
	_version() ,
	_versionSet(false) ,
	_styleSheetUploadFileName() ,
	_styleSheetUploadFileNameSet(false)
{
}


// copy constructor
dbConfigurationStyleSheet::dbConfigurationStyleSheet(const dbConfigurationStyleSheet &o):
	dbPersistent(o),
	_name(o._name) ,
	_nameSet(o._nameSet) ,
	_version(o._version) ,
	_versionSet(o._versionSet) ,
	_styleSheetUploadFileName(o._styleSheetUploadFileName) ,
	_styleSheetUploadFileNameSet(o._styleSheetUploadFileNameSet)
{
}


dbConfigurationStyleSheet::~dbConfigurationStyleSheet() throw()
{
}




dbPersistent *dbConfigurationStyleSheet::clone() const
{
	return new dbConfigurationStyleSheet(*this) ;
}



// operator =
dbConfigurationStyleSheet &dbConfigurationStyleSheet::operator=(const dbConfigurationStyleSheet &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_name=o._name;
		_nameSet=o._nameSet;
		_version=o._version;
		_versionSet=o._versionSet;
		_styleSheetUploadFileName=o._styleSheetUploadFileName;
		_styleSheetUploadFileNameSet=o._styleSheetUploadFileNameSet;
	}
	return *this ;
}


string dbConfigurationStyleSheet::className() const
{
	return staticClassName() ;
}


string dbConfigurationStyleSheet::staticClassName()
{
	return "dbConfigurationStyleSheet" ;
}


// initialize the class
void dbConfigurationStyleSheet::reset()
{
	Lock lock(*this) ;

	// reset dbPersistent
	dbPersistent::reset() ;
	_name="" ;
	_nameSet=false ;
	_version="" ;
	_versionSet=false ;
	_styleSheetUploadFileName="" ;
	_styleSheetUploadFileNameSet=false ;
}


// save the data in database
dbPersistent::IdType dbConfigurationStyleSheet::save(dbConnection &conn)
{
	Lock lock(*this) ;

	if (!isModified())
		return 0 ; 

	if (isFromDatabase()) 
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::save(). Use the method update() instead of save().") ;
		ACS_THROW(e) ;
	}
	if(!_nameSet) 
	{
		InvalidUse e("Mandatory field \"Name\" must be set.") ;
		ACS_THROW(e) ;
	}
	if(!_versionSet) 
	{
		InvalidUse e("Mandatory field \"Version\" must be set.") ;
		ACS_THROW(e) ;
	}
	if(!_styleSheetUploadFileNameSet) 
	{
		InvalidUse e("Mandatory field \"StyleSheet\" must be set.") ;
		ACS_THROW(e) ;
	}


	db::Transaction transaction(conn) ;

	transaction.begin_work("dbConfigurationStyleSheet_SAVE") ;
	conn.addStateWrapper(*this) ;


    const string &dbKey = conn.getKey() ;
	string uploadfile = _styleSheetUploadFileName ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "INSERT INTO " + getTable() + " (" ;
		queryString += "Name" ;
		queryString += ", Version" ;
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey,_name) ;
		queryString +=	", " +  db::toSQL(dbKey, _version) ;
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbConfigurationStyleSheet::save") ;

    query.execForStatus();
 
    SQLString blqueryst( dbKey, SQLString::LOBJ_UPLOAD ) ;
    blqueryst.setColumnAndFileName( "StyleSheet", uploadfile );
    blqueryst.addTableList( getTable() );
    {
        dbQueryParameters p(dbKey) ;
        p.addParameter( dbParam(dbKey,  getTable(), "Name", dbParam::EQUAL_TO, db::toSQL(dbKey, _name)) ) ;
        blqueryst.addANDWhereParameter(p) ;
    }
    {
        dbQueryParameters p(dbKey) ;
        p.addParameter( dbParam(dbKey,  getTable(), "Version", dbParam::EQUAL_TO, db::toSQL(dbKey,_version)) ) ;
        blqueryst.addANDWhereParameter(p) ;
    }   

    dbQuery blquery(conn, blqueryst, "dbConfigurationStyleSheet::saveBlob") ;	
    blquery.uploadClob();

    transaction.commit() ;
    
	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbConfigurationStyleSheet::load(dbConnection &conn , IdType id)
{
	Lock lock(*this) ;
	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB) ;

	dbConfigurationStyleSheet tempRecord(*this); //store current record.


	reset() ; 

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "SELECT " ;
		queryString +=	getFields() ;
		queryString += " FROM " + getTable() ;
		queryString += " WHERE Name " ;
		if(tempRecord._nameSet)
			queryString +=	string("= ") +  db::toSQL(dbKey, tempRecord._name) ;
		else
			queryString +=	" IS NULL" ;
		if(tempRecord._versionSet  && !tempRecord._version.empty() )
			queryString += " AND Version = " +  db::toSQL(dbKey, tempRecord._version) ;
		//else load records with all available versions and use sort to select the wanted one
		string getOrderByString(getOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos)
				queryString += getOrderByString ;
			else
				queryString += " ORDER BY " + getOrderByString ;
		}

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbConfigurationStyleSheet::load") ;
	dbRow row(dbKey) ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	dbSet setQ;
	query.execForSet(setQ) ;
    if (setQ.size() > 1) // it should not occur
    {
        ACS_THROW(InvalidUse("Unexpected query result dimension: it should return just one row"));
    }
    else
    {
		if ( not setQ.getNextRow(row) )
        {
        	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "No " << getTable() << " record found ");
			*this = tempRecord;  //Nothing found: restore previuos situation.
			return false ;
        }
	}

	loadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbConfigurationStyleSheet::update(dbConnection &conn)
{
	ACS_THROW(InvalidUse("No update foreseen on this record type")) ;
}


// remove the class from the database
dbPersistent::IdType dbConfigurationStyleSheet::remove(dbConnection &conn)
{
	Lock lock(*this) ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "DELETE FROM " + getTable() ;
		queryString += " WHERE " ;
		queryString += "Name " ;
		if(_nameSet)
			queryString +=	string("= ") +  db::toSQL(dbKey, _name)  + " AND " ;
		else
			queryString +=	"IS NULL AND" ;
		queryString += "Version " ;
		if(_versionSet)
			queryString +=	string("= ") +  db::toSQL(dbKey, _version)   ;
		else
			queryString +=	"IS NULL" ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
    db::Transaction transaction(conn) ;
	transaction.begin_work("dbConfigurationStyleSheet_REMOVE") ;

	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "dbConfigurationStyleSheet::remove") ;

	query.execForStatus() ;
	transaction.commit() ;


	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbConfigurationStyleSheet::validate() const
{
	Lock lock(*this) ;

	return true;
}


// export the class to stream
void dbConfigurationStyleSheet::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbConfigurationStyleSheet") ;
	dbPersistent::exportObj(s) ;
	if(_nameSet)
	{
		s.setValue("_name",_name) ;
	}
	s.setValue("_nameSet",_nameSet) ;
	if(_versionSet)
	{
		s.setValue("_version",_version) ;
	}
	s.setValue("_versionSet",_versionSet) ;
}


// import the class from a stream
void dbConfigurationStyleSheet::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbConfigurationStyleSheet") ;
	dbPersistent::importObj(s) ;
	reset() ;
	s.getValue("_nameSet",_nameSet) ;
	if(_nameSet)
	{
		s.getValue("_name",_name) ;
	}
	else
		_name = "" ;
	s.getValue("_versionSet",_versionSet) ;
	if(_versionSet)
	{
		s.getValue("_version",_version) ;
	}
	else
		_version = "" ;
}


// export the class to XML stream
void dbConfigurationStyleSheet::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbConfigurationStyleSheet");
	dbPersistent::exportXML(xst) ;
	if(_nameSet)
	{
	XMLOstream::Tag txml0(xst, "_name", _name, "label=\"Name\"");
	}
	else
	{
	XMLOstream::Tag txml0(xst, "_name", string("<null>"), "label=\"Name\"");
	}
	{
	XMLOstream::Tag txml0Set(xst, "_nameSet", (_nameSet ? "true" : "false")) ;
	}
	if(_versionSet)
	{
	XMLOstream::Tag txml1(xst, "_version", _version, "label=\"Version\"");
	}
	else
	{
	XMLOstream::Tag txml1(xst, "_version", string("<null>"), "label=\"Version\"");
	}
	{
	XMLOstream::Tag txml1Set(xst, "_versionSet", (_versionSet ? "true" : "false")) ;
	}
}

// load the object from a row
int dbConfigurationStyleSheet::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ;

	row.columnSet(offset + 0, _name, _nameSet) ;
	row.columnSet(offset + 1, _version, _versionSet) ;


	setFromDatabase() ;

	return offset + 2 ;
}


void dbConfigurationStyleSheet::setName(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::setName(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 64)
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::setName(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_nameSet || _name != v ) 
	{
		_name = v ;
		_nameSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbConfigurationStyleSheet::getName(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _nameSet ;
	return _name ;
}


void dbConfigurationStyleSheet::unsetName()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::unsetName(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_nameSet == true)
		setModifiedFlag();
	_nameSet = false;

}
void dbConfigurationStyleSheet::setVersion(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::setVersion(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 8)
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::setVersion(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_versionSet || _version != v ) 
	{
		_version = v ;
		_versionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbConfigurationStyleSheet::getVersion(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _versionSet ;
	return _version ;
}


void dbConfigurationStyleSheet::unsetVersion()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationStyleSheet::unsetVersion(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_versionSet == true)
		setModifiedFlag();
	_versionSet = false;

}
void dbConfigurationStyleSheet::replaceStyleSheetFile(const string &path, dbConnection &conn) 
{
	Lock lock(*this) ;

	if (_name.empty())
	{
		ObjectNotLoaded ex("_name is an empty string.") ;
		ACS_THROW(ex)
	}
	if (_version.empty())
	{
		ObjectNotLoaded ex("_version is an empty string.") ;
		ACS_THROW(ex)
	}
	string uploadfile = path ;

	if (uploadfile.empty() ) 
	{
		ObjectNotLoaded ex("Path is empty.") ;
		ACS_THROW(ex)
	}
    
    const string &dbKey = conn.getKey() ;

    SQLString queryString(dbKey,  SQLString::LOBJ_UPLOAD ) ;
    queryString.setColumnAndFileName( "StyleSheet", uploadfile );
    queryString.addTableList( getTable() );
    {
        dbQueryParameters p(dbKey) ;
	    if(_nameSet)
            p.addParameter( dbParam(dbKey, getTable(), "Namespace" , dbParam::EQUAL_TO, db::toSQL(dbKey,_name)) ) ;
        else
            p.addParameter( dbParam(dbKey, getTable(), "Namespace" , dbParam::ISNULL) ) ;
        queryString.addANDWhereParameter(p) ;
    }

    {
        dbQueryParameters p(dbKey) ;
	    if(_versionSet)
            p.addParameter( dbParam(dbKey, getTable(), "Version", dbParam::EQUAL_TO, db::toSQL(dbKey,_version)) ) ;
        else
            p.addParameter( dbParam(dbKey, getTable(), "Version", dbParam::ISNULL) ) ;
        queryString.addANDWhereParameter(p) ;
    }   

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Uploading file: " << uploadfile) ;

	dbQuery query(conn, queryString, "dbConfigurationStyleSheet::replaceStyleSheetFile") ;	

    query.uploadClob();
}

// Save the file on disk
void dbConfigurationStyleSheet::saveStyleSheetFile(const string &path, const string &filename, dbConnection &conn) 
{
	Lock lock(*this) ;

	string completePath ;
	if (path != "" && filename != "")
		completePath = path + "/" + filename ;
	else if (filename != "")
		completePath = filename ;
	else if (path != "")
		completePath = path ;
	else 
		completePath = getStyleSheetFileName() ;

	if(isFromDatabase()) {


	    const string &dbKey = conn.getKey() ;
        SQLString queryString(dbKey,  SQLString::LOBJ_DOWNLOAD ) ;
        queryString.setColumnAndFileName( "StyleSheet", completePath );
        queryString.addTableList( getTable() );

        {
            dbQueryParameters p(dbKey) ;
            if(_nameSet)
                p.addParameter( dbParam(dbKey, getTable(), "Name" , dbParam::EQUAL_TO, db::toSQL(dbKey,_name)) ) ;
            else
                p.addParameter( dbParam(dbKey, getTable(), "Name" , dbParam::ISNULL) ) ;
            queryString.addANDWhereParameter(p) ;
        }

        {
            dbQueryParameters p(dbKey) ;
            if(_versionSet)
                p.addParameter( dbParam(dbKey, getTable(), "Version" , dbParam::EQUAL_TO, db::toSQL(dbKey,_version)) ) ;
            else
                p.addParameter( dbParam(dbKey, getTable(), "Version" , dbParam::ISNULL) ) ;
            queryString.addANDWhereParameter(p) ;
        }   

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Downloading file: " << completePath) ;


		dbQuery query(conn, queryString, "dbConfigurationStyleSheet::saveStyleSheetFile") ;	

        try
        {
            query.downloadClob();
        }
        catch(exception &x)
        {
            ACS_THROW(exIOException(x, "Couldn't download File from Clob.")) ;
        }

		// change permissions allowing other users to override this file later.
		File::chmod(completePath,0664) ;

	}
	else
	{
		ObjectNotLoaded ex("Error: object not loaded") ;
		ACS_THROW(ex) ;
	/* ALTERNATIVE METHOD : LINK CREATION
		int err = ::link(getStyleSheetFileName().c_str(),completePath.c_str()) ;
		if(err != 0) {	
			string str = "Cannot copy \"" + getStyleSheetFileName() + "\" on \"" + completePath + "\"";
			exFileOpenException e(str , errno) ;
			ACS_THROW (e) ;
		}
	*/
	}
}

// by definition: <namespace>_<version>.<ext>
string dbConfigurationStyleSheet::getStyleSheetFileName() const 
{
	Lock lock(*this) ;

	return _name + "_" +_version + ".xsl";
}

void dbConfigurationStyleSheet::setStyleSheetUploadFileName(const string &uf)
{
	Lock lock(*this) ;

	_styleSheetUploadFileName = uf ;
	_styleSheetUploadFileNameSet = true ;
}

string dbConfigurationStyleSheet::getStyleSheetUploadFileName(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _styleSheetUploadFileNameSet ;
	return _styleSheetUploadFileName ;
}


// get the field names
string dbConfigurationStyleSheet::getFields()
{
	string s ;
	s += getTable() + "." + "Name, ";
	s += getTable() + "." + "Version" ;
	return s ;
}


// get the table name
string dbConfigurationStyleSheet::getTable()
{
	return "T_ConfigurationStyleSheets" ;
}


// get the order by clause
string dbConfigurationStyleSheet::getOrderBy()
{
	return "Name, Version DESC" ;
}


void dbConfigurationStyleSheet::writeTo(ostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_name = " << (_nameSet ? _name : string("<null>")) << endl 
		 << "_version = " << (_versionSet ? _version : string("<null>")) << endl  ;
}


void dbConfigurationStyleSheet::writeTo(exostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_name = " << (_nameSet ? _name : string("<null>")) << endl 
		 << "_version = " << (_versionSet ? _version : string("<null>")) << endl  ;
}


_ACS_END_NAMESPACE
