/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:03  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.4  2016/04/19 15:23:45  marpas
	coding best practices application in progress
	
	Revision 5.3  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:24  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:52  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:20  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.8  2013/04/12 12:14:37  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.7  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.6  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.5  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.4  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.3  2010/03/05 15:09:10  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.2  2008/09/23 08:27:37  crivig
	porting to postgres8
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:34  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.38  2006/01/20 10:19:54  enrcar
	EC:: define FORCE_DBEXPRESS_QUERY introduced to allow safer tests on dbexpress-ported queries
	
	Revision 1.37  2006/01/13 13:43:45  enrcar
	updated to dbexpress
	

	Revision 1.36  2005/06/15 07:44:49  integrator
	multiple storage manager implemented
	
	Revision 1.35  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.34  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.33  2004/10/04 15:13:52  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.32  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.31  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.30  2004/05/03 14:55:33  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.29  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.28  2004/04/13 16:57:08  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.27  2004/03/04 18:54:08  paoscu
	Class generated again. New clob management.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbConfigurationSchema.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbSet.h>
#include <dbConv.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <File.h>
#include <unistd.h>
#include <XMLOstream.h>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbConfigurationSchema)

// constructor
dbConfigurationSchema::dbConfigurationSchema() :
	dbPersistent(),
	_namespace() ,
	_namespaceSet() ,
	_version() ,
	_versionSet() ,
	_schemaUploadFileName() ,
	_schemaUploadFileNameSet()

{
}


// copy constructor
dbConfigurationSchema::dbConfigurationSchema(const dbConfigurationSchema &o):
	dbPersistent(o),
	_namespace(o._namespace) ,
	_namespaceSet(o._namespaceSet) ,
	_version(o._version) ,
	_versionSet(o._versionSet) ,
	_schemaUploadFileName(o._schemaUploadFileName) ,
	_schemaUploadFileNameSet(o._schemaUploadFileNameSet)
{
}


dbConfigurationSchema::~dbConfigurationSchema() throw()
{
}



dbPersistent *dbConfigurationSchema::clone() const
{
	return new dbConfigurationSchema(*this) ;
}



// operator =
dbConfigurationSchema &dbConfigurationSchema::operator=(const dbConfigurationSchema &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_namespace=o._namespace;
		_namespaceSet=o._namespaceSet;
		_version=o._version;
		_versionSet=o._versionSet;
		_schemaUploadFileName=o._schemaUploadFileName;
		_schemaUploadFileNameSet=o._schemaUploadFileNameSet;
	}
	return *this ;
}


string dbConfigurationSchema::className() const
{
	return staticClassName() ;
}


string dbConfigurationSchema::staticClassName()
{
	return "dbConfigurationSchema" ;
}


// initialize the class
void dbConfigurationSchema::reset()
{
	Lock lock(*this) ;

	// reset dbPersistent
	dbPersistent::reset() ;
	_namespace="" ;
	_namespaceSet=false ;
	_version="" ;
	_versionSet=false ;
	_schemaUploadFileName="" ;
	_schemaUploadFileNameSet=false ;
}


// save the data in database
dbPersistent::IdType dbConfigurationSchema::save(dbConnection &conn)
{
	Lock lock(*this) ;

	if (!isModified())
		return 0 ; 

	if (isFromDatabase()) 
	{
		InvalidUse e("Error: dbConfigurationSchema::save(). Use the method update() instead of save().") ;
		ACS_THROW(e) ;
	}
	if(!_namespaceSet) 
	{
		InvalidUse e("Mandatory field \"Namespace\" must be set.") ;
		ACS_THROW(e) ;
	}
	if(!_versionSet) 
	{
		InvalidUse e("Mandatory field \"Version\" must be set.") ;
		ACS_THROW(e) ;
	}
	if(!_schemaUploadFileNameSet) 
	{
		InvalidUse e("Mandatory field \"Schema\" must be set.") ;
		ACS_THROW(e) ;
	}

    const string &dbKey = conn.getKey() ;
	db::Transaction transaction(conn) ;
	transaction.begin_work("dbConfigurationSchema_SAVE") ;
 	conn.addStateWrapper(*this) ;

	dbQuery query(conn) ;

	string uploadfile = _schemaUploadFileName ;


    // Creating blank namespace

    SQLString queryString(dbKey, SQLString::INSERT ) ;

    // Add Table list
    queryString.addTableList( getTable() );

    // Add Values
    {
        queryString.addValuesList( "Namespace", db::toSQL(dbKey,_namespace) ) ;
        queryString.addValuesList( "Version", db::toSQL(dbKey,_version) ) ;
        // Space unset
    }

	query.sqlString(queryString, "dbConfigurationSchema::save") ;


    query.execForStatus();
    
    // SPACE IS UPLOADED using function replaceSchemaFile
    replaceSchemaFile(uploadfile, conn) ; 

	transaction.commit() ;
	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbConfigurationSchema::load(dbConnection &conn , IdType id)
{
	Lock lock(*this) ;

	dbConfigurationSchema tempRecord(*this); //store current record.


	reset() ; 

	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB) ;

	string queryString ;
    const string &dbKey = conn.getKey( );
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	getFields() ;
		queryString += " FROM " + getTable() ;
		queryString += " WHERE Namespace " ;
		if(tempRecord._namespaceSet)
			queryString +=	"= " + db::toSQL(dbKey,tempRecord._namespace) ;
		else
			queryString +=	" IS NULL" ;
		if(tempRecord._versionSet  && !tempRecord._version.empty() )
			queryString += " AND Version = " + db::toSQL(dbKey,tempRecord._version) ;
		//else load records with all available versions and use sort to select the wanted one
		string getOrderByString(getOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos)
				queryString += getOrderByString ;
			else
				queryString += " ORDER BY " + getOrderByString ;
		}
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbConfigurationSchema::load") ;
	dbRow row(conn.getKey()) ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	try
	{
        dbSet set ;
		query.execForSet(set) ;
        ACS_COND_THROW(set.empty(), dbQuery::QueryNoDataFound("empty set")) ; // PRQA S 3081 2
        ACS_COND_THROW(set.size() > 1, exIllegalValueException("Set size > 1")) ;
        set.getNextRow(row) ; // first and only 
	}
	catch (dbQuery::QueryNoDataFound &e)
	{
		*this = tempRecord;  //Nothing found: restore previuos situation.
		return false ;
	}

	loadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbConfigurationSchema::update(dbConnection &conn)
{
	ACS_THROW(InvalidUse("No update foreseen on this record type")) ;
}


// remove the class from the database
dbPersistent::IdType dbConfigurationSchema::remove(dbConnection &conn)
{
	Lock lock(*this) ;

	string queryString ;
    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "DELETE FROM " + getTable() ;
		queryString += " WHERE " ;
		queryString += "Namespace " ;
		if(_namespaceSet)
			queryString +=	"= " + db::toSQL(dbKey,_namespace) + " AND " ;
		else
			queryString +=	"IS NULL AND" ;
		queryString += "Version " ;
		if(_versionSet)
			queryString +=	"= " + db::toSQL(dbKey,_version) ;
		else
			queryString +=	"IS NULL" ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	db::Transaction transaction(conn) ;
	transaction.begin_work("dbConfigurationSchema_SAVE") ;

	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "dbConfigurationSchema::remove") ;
	query.execForStatus() ;
	transaction.commit() ;


	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbConfigurationSchema::validate() const
{
	Lock lock(*this) ;

	return true;
}



// export the class to stream
void dbConfigurationSchema::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbConfigurationSchema") ;
	dbPersistent::exportObj(s) ;
	if(_namespaceSet)
	{
		s.setValue("_namespace",_namespace) ;
	}
	s.setValue("_namespaceSet",_namespaceSet) ;
	if(_versionSet)
	{
		s.setValue("_version",_version) ;
	}
	s.setValue("_versionSet",_versionSet) ;
}


// import the class from a stream
void dbConfigurationSchema::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbConfigurationSchema") ;
	dbPersistent::importObj(s) ;
	reset() ;
	s.getValue("_namespaceSet",_namespaceSet) ;
	if(_namespaceSet)
	{
		s.getValue("_namespace",_namespace) ;
	}
	else
		_namespace = "" ;
	s.getValue("_versionSet",_versionSet) ;
	if(_versionSet)
	{
		s.getValue("_version",_version) ;
	}
	else
		_version = "" ;
}


// export the class to XML stream
void dbConfigurationSchema::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbConfigurationSchema");
	dbPersistent::exportXML(xst) ;
	if(_namespaceSet)
	{
	XMLOstream::Tag txml0(xst, "_namespace", _namespace, "label=\"Namespace\"");
	}
	else
	{
	XMLOstream::Tag txml0(xst, "_namespace", string("<null>"), "label=\"Namespace\"");
	}
	{
	XMLOstream::Tag txml0Set(xst, "_namespaceSet", (_namespaceSet ? "true" : "false")) ;
	}
	if(_versionSet)
	{
	XMLOstream::Tag txml1(xst, "_version", _version, "label=\"Version\"");
	}
	else
	{
	XMLOstream::Tag txml1(xst, "_version", string("<null>"), "label=\"Version\"");
	}
	{
	XMLOstream::Tag txml1Set(xst, "_versionSet", (_versionSet ? "true" : "false")) ;
	}
}



// load the object from a row
int dbConfigurationSchema::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ;

	row.columnSet(offset + 0, _namespace, _namespaceSet) ;
	row.columnSet(offset + 1, _version, _versionSet) ;


	setFromDatabase() ;

	return offset + 2 ;
}


void dbConfigurationSchema::setNamespace(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationSchema::setNamespace(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 64)
	{
		InvalidUse e("Error: dbConfigurationSchema::setNamespace(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_namespaceSet || _namespace != v ) 
	{
		_namespace = v ;
		_namespaceSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbConfigurationSchema::getNamespace(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _namespaceSet ;
	return _namespace ;
}


void dbConfigurationSchema::unsetNamespace()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationSchema::unsetNamespace(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_namespaceSet == true)
		setModifiedFlag();
	_namespaceSet = false;

}
void dbConfigurationSchema::setVersion(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationSchema::setVersion(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 8)
	{
		InvalidUse e("Error: dbConfigurationSchema::setVersion(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_versionSet || _version != v ) 
	{
		_version = v ;
		_versionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbConfigurationSchema::getVersion(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _versionSet ;
	return _version ;
}


void dbConfigurationSchema::unsetVersion()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbConfigurationSchema::unsetVersion(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_versionSet == true)
		setModifiedFlag();
	_versionSet = false;

}
void dbConfigurationSchema::replaceSchemaFile(const string &path, dbConnection &conn) 
{
	Lock lock(*this) ;

	if (_namespace.empty())
	{
		ObjectNotLoaded ex("_namespace is an empty string.") ;
		ACS_THROW(ex)
	}
	if (_version.empty())
	{
		ObjectNotLoaded ex("_version is an empty string.") ;
		ACS_THROW(ex)
	}
	string uploadfile = path ;

	if (uploadfile.empty() ) 
	{
		ObjectNotLoaded ex("Path is empty.") ;
		ACS_THROW(ex)
	}

    
    const string &dbKey = conn.getKey( );
    SQLString queryString(dbKey, SQLString::LOBJ_UPLOAD ) ;
    queryString.setColumnAndFileName( "Schema", uploadfile );
    queryString.addTableList( getTable() );
    {
        dbQueryParameters p(dbKey) ;
        if(_namespaceSet)
            p.addParameter(dbParam(dbKey,  getTable(), "Namespace" , dbParam::EQUAL_TO, db::toSQL(dbKey,_namespace)) ) ;
        else
            p.addParameter(dbParam(dbKey,  getTable(), "Namespace" , dbParam::ISNULL) ) ;
        queryString.addANDWhereParameter(p) ;
    }

    {
        dbQueryParameters p(dbKey) ;
        if(_versionSet)
            p.addParameter(dbParam(dbKey,  getTable(), "Version", dbParam::EQUAL_TO, db::toSQL(dbKey,_version)) ) ;
        else
            p.addParameter(dbParam(dbKey,  getTable(), "Version", dbParam::ISNULL) ) ;
        queryString.addANDWhereParameter(p) ;
    }   

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "file: " << uploadfile) ;
    
	dbQuery query(conn, queryString, "dbConfigurationSchema::replaceSchemaFile") ;	

    query.uploadClob();
}

// Save the file on disk
void dbConfigurationSchema::saveSchemaFile(const string &path, const string &filename, dbConnection &conn) 
{
	Lock lock(*this) ;

	string completePath ;
	if (path != "" && filename != "")
		completePath = path + "/" + filename ;
	else if (filename != "")
		completePath = filename ;
	else if (path != "")
		completePath = path ;
	else 
		completePath = getSchemaFileName() ;

	if(isFromDatabase()) {
	
        const string &dbKey = conn.getKey() ;

        SQLString queryString(dbKey, SQLString::LOBJ_DOWNLOAD ) ;
        queryString.setColumnAndFileName( "Schema", completePath );
        queryString.addTableList( getTable() );
        
        {
            dbQueryParameters p(dbKey) ;
            if(_namespaceSet)
                p.addParameter( dbParam(dbKey, getTable(), "Namespace" , dbParam::EQUAL_TO, db::toSQL(dbKey,_namespace)) ) ;
            else
                p.addParameter( dbParam(dbKey, getTable(), "Namespace" , dbParam::ISNULL) ) ;
            queryString.addANDWhereParameter(p) ;
        }
            
        {
            dbQueryParameters p(dbKey) ;
            if(_versionSet)
                p.addParameter( dbParam(dbKey, getTable(), "Version" , dbParam::EQUAL_TO, db::toSQL(dbKey,_version)) ) ;
            else
                p.addParameter( dbParam(dbKey, getTable(), "Version" , dbParam::ISNULL) ) ;
            queryString.addANDWhereParameter(p) ;
        }   
	    
        ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Downloading file: " << completePath) ;


		dbQuery query(conn, queryString, "dbConfigurationSchema::saveSchemaFile") ;	
        try
        {
            query.downloadClob();
        }
        catch(exception &x)
        {
            ACS_THROW( exIOException(x, "Couldn't download File from Clob.")) ;
        }
        
		// change permissions allowing other users to override this file later.
		File::chmod(completePath,0664) ;

	}
	else
	{
		ObjectNotLoaded ex("Error: object not loaded") ;
		ACS_THROW(ex) ;
	/* ALTERNATIVE METHOD : LINK CREATION
		int err = ::link(getVersionFileName().c_str(),completePath.c_str()) ;
		if(err != 0) {	
			string str = "Cannot copy \"" + getVersionFileName() + "\" on \"" + completePath + "\"";
			exFileOpenException e(str , errno) ;
			ACS_THROW (e) ;
		}
	*/
	}
}

// by definition: <namespace>_<version>.<ext>
string dbConfigurationSchema::getSchemaFileName() const 
{
	Lock lock(*this) ;
	return _namespace + "_" +_version + ".dtd";
}

void dbConfigurationSchema::setSchemaUploadFileName(const string &uf)
{
	Lock lock(*this) ;

	_schemaUploadFileName = uf ;
	_schemaUploadFileNameSet = true ;
}

string dbConfigurationSchema::getSchemaUploadFileName(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _schemaUploadFileNameSet ;
	return _schemaUploadFileName ;
}


// get the field names
string dbConfigurationSchema::getFields()
{
	string s ;
	s += getTable() + "." + "Namespace, ";
	s += getTable() + "." + "Version" ;
	return s ;
}


// get the table name
string dbConfigurationSchema::getTable()
{
	return "T_ConfigurationSchemas" ;
}


// get the order by clause
string dbConfigurationSchema::getOrderBy()
{
	return "Namespace, Version DESC" ;
}


void dbConfigurationSchema::writeTo(ostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_namespace = " << (_namespaceSet ? _namespace : string("<null>")) << "\n" 
		 << "_version = " << (_versionSet ? _version : string("<null>")) << "\n"  ;
}


void dbConfigurationSchema::writeTo(exostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_namespace = " << (_namespaceSet ? _namespace : string("<null>")) << "\n" 
		 << "_version = " << (_versionSet ? _version : string("<null>")) << "\n"  ;
}


_ACS_END_NAMESPACE
