// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:54  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:21  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.4  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.3  2012/06/15 09:54:29  marpas
	removing warning related to virtual method hiding
	
	Revision 2.2  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.1  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.4  2005/06/17 10:31:54  marpas
	std namespaces took into consideration
	
	Revision 1.3  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.2  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.1  2004/04/16 16:33:19  paoscu
	dbDistributionFormat added.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbDistributionFormat_H_
#define _dbDistributionFormat_H_

#include <exException.h>
#include <dbPersistent.h>

_ACS_BEGIN_NAMESPACE(acs)

class dbCryosatFactory ;

class dbRow ;
class rsResourceSet ;
class XMLOstream ;

//
//
//
// class dbDistributionFormat
//
//
//
class dbDistributionFormat : // PRQA S 2109, 2153
	public dbPersistent
{
	friend class dbCryosatFactory ; // PRQA S 2107
public:

	virtual ~dbDistributionFormat() throw() ;
	dbDistributionFormat &operator=(const dbDistributionFormat &) ; // operator =

	static  std::string staticClassName() ;

	// inherited from dbPersistent
	virtual dbPersistent* clone() const ; // PRQA S 2502
	virtual std::string className() const ;
	virtual void reset() ; // initialize the class
	virtual IdType save(dbConnection &)  ; // save the data in database
	virtual bool load(dbConnection & , IdType id=0)  ; // load the class from the database. Return true if obect exist
	virtual IdType update(dbConnection &)  ; // update an existing instance in database
	virtual IdType remove(dbConnection &)  ; // remove the class from the database // PRQA S 2502
	virtual bool validate() const  ; // True if the class have valid parameters, false otherwise
	virtual void exportObj(rsResourceSet &s) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &s)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &xst) const ; // export the class to XML stream

	int loadRow(const dbRow &, int offset=0) ;

	static std::string getWhere() ;
	static std::string getIdName() ;

	void setFormat(const std::string &) ;
	const std::string &getFormat(bool *set=0) const ;
	void unsetFormat();

	void setDescription(const std::string &) ;
	const std::string &getDescription(bool *set=0) const ;
	void unsetDescription();

	static std::string getFields() ;
	static std::string getTable() ;
	static std::string getOrderBy() ;

	// output to stream
	virtual void writeTo(std::ostream &) const ;
	virtual void writeTo(exostream &) const ;


protected:
	dbDistributionFormat() ;
	dbDistributionFormat(const dbDistributionFormat &) ;


private:
	int privateLoadRow(const dbRow &, int offset=0) ;
	static std::string privateGetFields() ;
	static std::string privateGetOrderBy() ;


private:
	std::string _format ;
	bool _formatSet ;

	std::string _description ;
	bool _descriptionSet ;

	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbDistributionFormat)
} ;


_ACS_END_NAMESPACE

#endif // _dbDistributionFormat_H_
