/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/27 08:27:46  damdec
	Compilation warnings fixed.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.3  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:55  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:22  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.11  2013/04/30 13:31:42  marpas
	dbPersistent interface changed
	
	Revision 2.10  2013/04/17 17:37:24  marpas
	dbPersistent interface changed
	
	Revision 2.9  2013/04/12 12:14:37  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.8  2013/03/29 19:51:29  marpas
	removing html related functions
	
	Revision 2.7  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.6  2012/02/14 12:52:46  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.5  2011/09/28 13:16:12  danalt
	JobResponsible size is now 64
	
	Revision 2.4  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.3  2010/03/05 15:09:10  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.2  2009/09/29 15:33:55  marpas
	useless include removed
	
	Revision 2.1  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.16  2005/06/15 07:44:49  integrator
	multiple storage manager implemented
	
	Revision 1.15  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.14  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.13  2004/10/04 15:13:52  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.12  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.11  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.10  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.9  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.8  2004/04/13 16:57:08  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.7  2004/02/04 10:12:35  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbDistributionView.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbSet.h>
#include <dbConv.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>



using namespace acs ;
using namespace std ;


ACS_CLASS_DEFINE_DEBUG_LEVEL(dbDistributionView)

// constructor
dbDistributionView::dbDistributionView() :
	dbPersistent(),
	_status(),
	_statusSet(),
	_distributedDate(),
	_distributedDateSet(),
	_jobResponsible(),
	_jobResponsibleSet(),
	_creationDate(),
	_creationDateSet(),
	_mediaType(),
	_mediaTypeSet(),
	_userId(),
	_userIdSet()

{
	reset() ;
}


// copy constructor
dbDistributionView::dbDistributionView(const dbDistributionView &o):
	dbPersistent(o),
	_status(o._status),
	_statusSet(o._statusSet),
	_distributedDate(o._distributedDate),
	_distributedDateSet(o._distributedDateSet),
	_jobResponsible(o._jobResponsible),
	_jobResponsibleSet(o._jobResponsibleSet),
	_creationDate(o._creationDate),
	_creationDateSet(o._creationDateSet),
	_mediaType(o._mediaType),
	_mediaTypeSet(o._mediaTypeSet),
	_userId(o._userId),
	_userIdSet(o._userIdSet)
{
}


dbDistributionView::~dbDistributionView() throw()
{
}


dbPersistent *dbDistributionView::clone() const
{
	return new dbDistributionView(*this) ;
}



// operator =
dbDistributionView &dbDistributionView::operator=(const dbDistributionView &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_status=o._status;
		_statusSet=o._statusSet;
		_distributedDate=o._distributedDate;
		_distributedDateSet=o._distributedDateSet;
		_jobResponsible=o._jobResponsible;
		_jobResponsibleSet=o._jobResponsibleSet;
		_creationDate=o._creationDate;
		_creationDateSet=o._creationDateSet;
		_mediaType=o._mediaType;
		_mediaTypeSet=o._mediaTypeSet;
		_userId=o._userId;
		_userIdSet=o._userIdSet;
	}
	return *this ;
}


string dbDistributionView::className() const
{
	return staticClassName() ;
}


string dbDistributionView::staticClassName()
{
	return "dbDistributionView" ;
}


// initialize the class
void dbDistributionView::reset()
{
	Lock lock(*this) ;

	// reset dbPersistent
	dbPersistent::reset() ;
	_status="" ;
	_statusSet=false ;
	_distributedDate.reset() ;
	_distributedDateSet=false ;
	_jobResponsible="" ;
	_jobResponsibleSet=false ;
	_creationDate.reset() ;
	_creationDateSet=false ;
	_mediaType="" ;
	_mediaTypeSet=false ;
	_userId="" ;
	_userIdSet=false ;
}


// save the data in database
dbPersistent::IdType dbDistributionView::save(dbConnection &conn)
{
	InvalidUse e("this class doesn't allow save");
	ACS_THROW(e);
}


// load the class from the database. Return true if object exist
bool dbDistributionView::load(dbConnection &conn , IdType id)
{
	Lock lock(*this) ;
	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB) ;

	dbDistributionView tempRecord(*this); //store current record.


	reset() ; 

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	getFields() ;
		queryString += " FROM " + getTable() ;
		if(id==0)
		{
			queryString += " WHERE PackageId = " ;
			queryString +=	 db::toSQL(dbKey, tempRecord.getId()) ;
		}
		else
		{
			queryString += " WHERE PackageId = " ;
			queryString +=	 db::toSQL(dbKey, id) ;
		}
		string getOrderByString(getOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos)
				queryString += getOrderByString ;
			else
				queryString += " ORDER BY " + getOrderByString ;
		}
	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbDistributionView::load") ;
	dbRow row(conn.getKey()) ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	try
	{
        dbSet set ;
		query.execForSet(set) ;
        ACS_COND_THROW(set.empty(), dbQuery::QueryNoDataFound("empty set")) ; // PRQA S 3081 2
        ACS_COND_THROW(set.size() > 1, exIllegalValueException("Set size > 1")) ;
        set.getNextRow(row) ; // first and only 
	}
	catch (dbQuery::QueryNoDataFound &e)
	{
		*this = tempRecord;  //Nothing found: restore previuos situation.
		return false ;
	}

	loadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbDistributionView::update(dbConnection &conn)
{
	InvalidUse e("this class doesn't allow update");
	ACS_THROW(e);
}


// remove the class from the database
dbPersistent::IdType dbDistributionView::remove(dbConnection &conn)
{
	InvalidUse e("this class doesn't allow remove");
	ACS_THROW(e);
}


// True if the class have valid parameters, false otherwise
bool dbDistributionView::validate() const
{
	Lock lock(*this) ;

	return true;
}


// export the class to stream
void dbDistributionView::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbDistributionView") ;
	dbPersistent::exportObj(s) ;
	s.setValue("_packageId", getId()) ;
	if(_statusSet)
	{
		s.setValue("_status",_status) ;
	}
	s.setValue("_statusSet",_statusSet) ;
	if(_distributedDateSet)
	{
		{
		rsPushNSpace rpns2(s,"_distributedDate") ;
		_distributedDate.exportObj(s) ;
		}
	}
	s.setValue("_distributedDateSet",_distributedDateSet) ;
	if(_jobResponsibleSet)
	{
		s.setValue("_jobResponsible",_jobResponsible) ;
	}
	s.setValue("_jobResponsibleSet",_jobResponsibleSet) ;
	if(_creationDateSet)
	{
		{
		rsPushNSpace rpns4(s,"_creationDate") ;
		_creationDate.exportObj(s) ;
		}
	}
	s.setValue("_creationDateSet",_creationDateSet) ;
	if(_mediaTypeSet)
	{
		s.setValue("_mediaType",_mediaType) ;
	}
	s.setValue("_mediaTypeSet",_mediaTypeSet) ;
	if(_userIdSet)
	{
		s.setValue("_userId",_userId) ;
	}
	s.setValue("_userIdSet",_userIdSet) ;
}


// import the class from a stream
void dbDistributionView::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbDistributionView") ;
	dbPersistent::importObj(s) ;
	unsigned long id ;
	s.getValue("_packageId", id) ;
	setId(id) ;
	s.getValue("_statusSet",_statusSet) ;
	if(_statusSet)
	{
		s.getValue("_status",_status) ;
	}
	else
		_status = "" ;
	s.getValue("_distributedDateSet",_distributedDateSet) ;
	if(_distributedDateSet)
	{
		{
		rsPushNSpace rpns2(s,"_distributedDate") ;
		_distributedDate.importObj(s) ;
		}
	}
	else
		_distributedDate.reset() ;
	s.getValue("_jobResponsibleSet",_jobResponsibleSet) ;
	if(_jobResponsibleSet)
	{
		s.getValue("_jobResponsible",_jobResponsible) ;
	}
	else
		_jobResponsible = "" ;
	s.getValue("_creationDateSet",_creationDateSet) ;
	if(_creationDateSet)
	{
		{
		rsPushNSpace rpns4(s,"_creationDate") ;
		_creationDate.importObj(s) ;
		}
	}
	else
		_creationDate.reset() ;
	s.getValue("_mediaTypeSet",_mediaTypeSet) ;
	if(_mediaTypeSet)
	{
		s.getValue("_mediaType",_mediaType) ;
	}
	else
		_mediaType = "" ;
	s.getValue("_userIdSet",_userIdSet) ;
	if(_userIdSet)
	{
		s.getValue("_userId",_userId) ;
	}
	else
		_userId = "" ;
}


// export the class to XML stream
void dbDistributionView::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbDistributionView");
	dbPersistent::exportXML(xst) ;
	{
	ostringstream os;
	os << getId();
	XMLOstream::Tag txml0(xst, "_packageId", os.str(), "label=\"Package Id\"");
	}
	if(_statusSet)
	{
	XMLOstream::Tag txml1(xst, "_status", _status, "label=\"Status\"");
	}
	else
	{
	XMLOstream::Tag txml1(xst, "_status", string("<null>"), "label=\"Status\"");
	}
	{
	XMLOstream::Tag txml1Set(xst, "_statusSet", (_statusSet ? "true" : "false")) ;
	}
	if(_distributedDateSet)
	{
		XMLOstream::Tag txml2(xst, "_distributedDate", "", "label=\"Distributed Date\"");
		_distributedDate.exportXML(xst) ;
	}
	else
	{
	XMLOstream::Tag txml2(xst, "_distributedDate", string("<null>"), "label=\"Distributed Date\"");
	}
	{
	XMLOstream::Tag txml2Set(xst, "_distributedDateSet", (_distributedDateSet ? "true" : "false")) ;
	}
	if(_jobResponsibleSet)
	{
	XMLOstream::Tag txml3(xst, "_jobResponsible", _jobResponsible, "label=\"Job Responsible\"");
	}
	else
	{
	XMLOstream::Tag txml3(xst, "_jobResponsible", string("<null>"), "label=\"Job Responsible\"");
	}
	{
	XMLOstream::Tag txml3Set(xst, "_jobResponsibleSet", (_jobResponsibleSet ? "true" : "false")) ;
	}
	if(_creationDateSet)
	{
		XMLOstream::Tag txml4(xst, "_creationDate", "", "label=\"Creation Date\"");
		_creationDate.exportXML(xst) ;
	}
	else
	{
	XMLOstream::Tag txml4(xst, "_creationDate", string("<null>"), "label=\"Creation Date\"");
	}
	{
	XMLOstream::Tag txml4Set(xst, "_creationDateSet", (_creationDateSet ? "true" : "false")) ;
	}
	if(_mediaTypeSet)
	{
	XMLOstream::Tag txml5(xst, "_mediaType", _mediaType, "label=\"Media Type\"");
	}
	else
	{
	XMLOstream::Tag txml5(xst, "_mediaType", string("<null>"), "label=\"Media Type\"");
	}
	{
	XMLOstream::Tag txml5Set(xst, "_mediaTypeSet", (_mediaTypeSet ? "true" : "false")) ;
	}
	if(_userIdSet)
	{
	XMLOstream::Tag txml6(xst, "_userId", _userId, "label=\"User Id\"");
	}
	else
	{
	XMLOstream::Tag txml6(xst, "_userId", string("<null>"), "label=\"User Id\"");
	}
	{
	XMLOstream::Tag txml6Set(xst, "_userIdSet", (_userIdSet ? "true" : "false")) ;
	}
}


// load the object from a row
int dbDistributionView::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ;

	unsigned long id ;

	row.column(offset + 0, id) ;

	setId(id) ;

	row.columnSet(offset + 1, _status, _statusSet) ;
	row.columnSet(offset + 2, _distributedDate, _distributedDateSet) ;
	row.columnSet(offset + 3, _jobResponsible, _jobResponsibleSet) ;
	row.columnSet(offset + 4, _creationDate, _creationDateSet) ;
	row.columnSet(offset + 5, _mediaType, _mediaTypeSet) ;
	row.columnSet(offset + 6, _userId, _userIdSet) ;


	setFromDatabase() ;

	return offset + 7 ;
}


void dbDistributionView::setPackageId(dbPersistent::IdType v)
{
	Lock lock(*this) ;

	if (getId() != v ) 
	{
		setId(v) ;
		setModifiedFlag() ;
	}
}


dbPersistent::IdType dbDistributionView::getPackageId() const
{
	Lock lock(*this) ;

	return getId() ;
}


void dbDistributionView::setStatus(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 32)
	{
		InvalidUse e("Error: dbDistributionView::setStatus(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_statusSet || _status != v ) 
	{
		_status = v ;
		_statusSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionView::getStatus(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _statusSet ;
	return _status ;
}


void dbDistributionView::unsetStatus()
{
	Lock lock(*this) ;
	if(_statusSet == true)
		setModifiedFlag();
	_statusSet = false;

}
void dbDistributionView::setDistributedDate(const DateTime &v)
{
	Lock lock(*this) ;

	if (!_distributedDateSet || _distributedDate != v ) 
	{
		_distributedDate = v ;
		_distributedDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistributionView::getDistributedDate(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _distributedDateSet ;
	return _distributedDate ;
}


void dbDistributionView::unsetDistributedDate()
{
	Lock lock(*this) ;
	if(_distributedDateSet == true)
		setModifiedFlag();
	_distributedDateSet = false;

}
void dbDistributionView::setJobResponsible(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 64)
	{
		InvalidUse e("Error: dbDistributionView::setJobResponsible(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_jobResponsibleSet || _jobResponsible != v ) 
	{
		_jobResponsible = v ;
		_jobResponsibleSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionView::getJobResponsible(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _jobResponsibleSet ;
	return _jobResponsible ;
}


void dbDistributionView::unsetJobResponsible()
{
	Lock lock(*this) ;
	if(_jobResponsibleSet == true)
		setModifiedFlag();
	_jobResponsibleSet = false;

}
void dbDistributionView::setCreationDate(const DateTime &v)
{
	Lock lock(*this) ;

	if (!_creationDateSet || _creationDate != v ) 
	{
		_creationDate = v ;
		_creationDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistributionView::getCreationDate(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _creationDateSet ;
	return _creationDate ;
}


void dbDistributionView::unsetCreationDate()
{
	Lock lock(*this) ;
	if(_creationDateSet == true)
		setModifiedFlag();
	_creationDateSet = false;

}
void dbDistributionView::setMediaType(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 16)
	{
		InvalidUse e("Error: dbDistributionView::setMediaType(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_mediaTypeSet || _mediaType != v ) 
	{
		_mediaType = v ;
		_mediaTypeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionView::getMediaType(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _mediaTypeSet ;
	return _mediaType ;
}


void dbDistributionView::unsetMediaType()
{
	Lock lock(*this) ;
	if(_mediaTypeSet == true)
		setModifiedFlag();
	_mediaTypeSet = false;

}
void dbDistributionView::setUserId(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 32)
	{
		InvalidUse e("Error: dbDistributionView::setUserId(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_userIdSet || _userId != v ) 
	{
		_userId = v ;
		_userIdSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionView::getUserId(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _userIdSet ;
	return _userId ;
}


void dbDistributionView::unsetUserId()
{
	Lock lock(*this) ;
	if(_userIdSet == true)
		setModifiedFlag();
	_userIdSet = false;

}
// get the field names
string dbDistributionView::getFields()
{
	string s ;
	s += getTable() + "." + "PackageId, ";
	s += getTable() + "." + "Status, ";
	s += getTable() + "." + "DistributedDate, ";
	s += getTable() + "." + "JobResponsible, ";
	s += getTable() + "." + "CreationDate, ";
	s += getTable() + "." + "MediaType, ";
	s += getTable() + "." + "UserId" ;
	return s ;
}


// get the table name
string dbDistributionView::getTable()
{
	return "V_Distribution" ;
}


// get the order by clause
string dbDistributionView::getOrderBy()
{
	return "" ;
}


void dbDistributionView::writeTo(ostream &o) const
{
	Lock lock(*this) ;

	string tmp ; 

	o
		 << "_packageId = " << getId() << "\n" 
		 << "_status = " << (_statusSet ? _status : string("<null>")) << "\n" 
		 << "_distributedDate = " << (_distributedDateSet ? _distributedDate.utcs(tmp) : string("<null>")) << "\n" 
		 << "_jobResponsible = " << (_jobResponsibleSet ? _jobResponsible : string("<null>")) << "\n" 
		 << "_creationDate = " << (_creationDateSet ? _creationDate.utcs(tmp) : string("<null>")) << "\n" 
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : string("<null>")) << "\n" 
		 << "_userId = " << (_userIdSet ? _userId : string("<null>")) << "\n"  ;
}


void dbDistributionView::writeTo(exostream &o) const
{
	Lock lock(*this) ;

	string tmp ; 

	o
		 << "_packageId = " << getId() << "\n" 
		 << "_status = " << (_statusSet ? _status : string("<null>")) << "\n" 
		 << "_distributedDate = " << (_distributedDateSet ? _distributedDate.utcs(tmp) : string("<null>")) << "\n" 
		 << "_jobResponsible = " << (_jobResponsibleSet ? _jobResponsible : string("<null>")) << "\n" 
		 << "_creationDate = " << (_creationDateSet ? _creationDate.utcs(tmp) : string("<null>")) << "\n" 
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : string("<null>")) << "\n" 
		 << "_userId = " << (_userIdSet ? _userId : string("<null>")) << "\n"  ;
}


