/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.3  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:53  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:21  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.6  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.5  2012/11/16 13:01:12  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.3  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.2  2007/05/08 10:56:58  marpas
	management of related tables improved and or fixed
	
	Revision 2.1  2007/04/18 22:12:55  marpas
	Management of dbDistributionpolicies relations with respect to data sets and originators
	
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbDistPolMDS.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbConnectionPool.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <XMLOstream.h>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbDistPolMDS)

// constructor
dbDistPolMDS::dbDistPolMDS(dbConnection &conn) : dbSmartPersistent("t_distpoldataset", conn)
{
}


// copy constructor
dbDistPolMDS::dbDistPolMDS(const dbDistPolMDS &o):
	dbSmartPersistent(o)
{
}


dbDistPolMDS::~dbDistPolMDS() throw()
{
}



dbPersistent *dbDistPolMDS::clone() const
{
	return new dbDistPolMDS(*this) ;
}


// operator =
dbDistPolMDS &dbDistPolMDS::operator=(const dbDistPolMDS &o)
{
	Lock lock(*this) ; // PRQA S 3050
	Lock lo(o) ; // PRQA S 3050

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


string dbDistPolMDS::className() const
{
	return staticClassName() ;
}


string dbDistPolMDS::staticClassName()
{
	return "dbDistPolMDS" ;
}

// export the class to stream
void dbDistPolMDS::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ; // PRQA S 3050
    bool null ;
    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ; // PRQA S 3050
	rsPushNSpace nsp(s,"dbDistPolMDS") ;
	dbPersistent::exportObj(s) ;
	if(isSet("policy"))
	{
		s.setValue("_policy",getPolicy(null, c)) ;
	}
	s.setValue("_policySet",isSet("policy")) ;


}





// import the class from a stream
void dbDistPolMDS::importObj(rsResourceSet &s)
{
	Lock lock(*this) ; // PRQA S 3050

    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ; // PRQA S 3050
	rsPushNSpace nsp(s,"dbDistPolMDS") ;
	dbSmartPersistent::importObj(s) ;
	bool is = false ;
	s.getValue("_policySet",is) ;
	if(is)
	{
		IdType v ;
		s.getValue("_policy",v) ;
		setPolicy(v, c) ;
	}
	else
		unsetPolicy() ;
		
}




// export the class to XML stream
void dbDistPolMDS::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ; // PRQA S 3050

    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ; // PRQA S 3050
    bool null = false ;
	XMLOstream::Tag txml(xst, "dbDistPolMDS");
	dbSmartPersistent::exportXML(xst) ;
	if(isSet("filename"))
	{
		XMLOstream::Tag txml(xst, "_policy", getPolicy(null, c), "label=\"Policy\"");
	}
	else
	{
		XMLOstream::Tag txml(xst, "_policy", string("<null>"), "label=\"Policy\"");
	}
	{
		XMLOstream::Tag txml(xst, "_policySet", (isSet("policy") ? "true" : "false")) ;
	}
	
}


void dbDistPolMDS::setPolicy(IdType v, dbConnection &c)
{
	set("policy",v, c) ;
}


dbPersistent::IdType dbDistPolMDS::getPolicy(bool &s, dbConnection &c) const
{
	dbPersistent::IdType v ; 
	
	get("policy",v, s, c) ;

	return v ;
}


void dbDistPolMDS::unsetPolicy()
{
	unset("policy") ;
}


void dbDistPolMDS::setMeasDataSetId(int v, dbConnection &c)
{
	set<int>("dataset",v, c) ;
}


int dbDistPolMDS::getMeasDataSetId(bool &s, dbConnection &c) const
{
	int v = 0 ; 
	
	get<int>("dataset",v, s, c) ;

	return v ;
}


void dbDistPolMDS::unsetMeasDataSetId()
{
	unset("dataset") ;
}


void dbDistPolMDS::setCount(int v, dbConnection &c)
{
	set<int>("num",v, c) ;
}


int dbDistPolMDS::getCount(bool &s, dbConnection &c) const
{
	int v = 0 ; 
	
	get<int>("num",v, s, c) ;

	return v ;
}


void dbDistPolMDS::unsetCount()
{
	unset("num") ;
}



// get the field names
string dbDistPolMDS::getFields()
{
	string s ;
	s += getTable() + "." + "Policy, ";
	s += getTable() + "." + "Dataset, ";
	s += getTable() + "." + "Num ";
	return s ;
}


// get the table name
string dbDistPolMDS::getTable()
{
	return "T_DistPolDataSet" ;
}

_ACS_END_NAMESPACE
