// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/27 08:26:25  damdec
	PDS_OLD_SCHEMA flag removed. Code updated: field Format is no mandatory.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.1  2014/05/26 11:39:44  marpas
	dbConv casted to avoid problem with new libXMLResources templates for tags
	
	Revision 4.0  2013/09/30 12:30:54  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:22  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.20  2013/04/30 13:31:42  marpas
	dbPersistent interface changed
	
	Revision 2.19  2013/04/17 17:37:24  marpas
	dbPersistent interface changed
	
	Revision 2.18  2013/04/12 12:14:37  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.17  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.16  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.15  2013/02/05 10:24:45  marfav
	PackagingAlgoId field management added
	
	Revision 2.14  2013/01/08 16:24:19  marfav
	DistributionRule_ID management implementation completed
	
	Revision 2.13  2012/12/21 12:33:15  marpas
	PDS_OLD_SCHEMA unchanged, new distributionrule_id mandatory field management added
	
	Revision 2.12  2012/11/16 13:01:13  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.10  2012/02/14 12:52:46  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.9  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.8  2010/03/05 15:09:10  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.7  2009/09/29 15:30:42  marpas
	useless include removed
	
	Revision 2.6  2009/04/07 08:29:49  enrcar
	EC:: the value of offset misleading after having added new params. Fixed.
	
	Revision 2.5  2009/03/27 09:35:09  danalt
	corrected minor error in SQL query
	
	Revision 2.4  2009/03/24 10:00:33  crivig
	cartid, subreq new fields handled
	
	Revision 2.3  2009/02/19 10:19:08  enrcar
	EC:: Useless control removed
	
	Revision 2.2  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.1  2008/07/14 13:15:15  marpas
	statistics improved
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.36  2005/06/15 07:44:49  integrator
	multiple storage manager implemented
	
	Revision 1.35  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.34  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.33  2004/10/04 15:13:52  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.32  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.31  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.30  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.29  2004/04/21 10:23:08  paoscu
	Bug fixed in privateLoadRow.
	
	Revision 1.28  2004/04/19 13:38:43  paoscu
	Field "format" added.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbDistributionItem.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbSet.h>
#include <dbConv.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbDistributionItem)

// constructor
dbDistributionItem::dbDistributionItem() :
	dbPersistent(),
	_idSet(),
	_dueDate() ,
	_dueDateSet() ,
	_distributedDate() ,
	_distributedDateSet() ,
	_creationDate() ,
	_creationDateSet() ,
	_packageId() ,
	_packageIdSet() ,
	_fileName() ,
	_fileNameSet() ,
	_fileVersion() ,
	_fileVersionSet() ,
	_mediaType() ,
	_mediaTypeSet() ,
	_userId() ,
	_userIdSet() ,
	_format() ,
	_formatSet(),
	_cartId() ,
	_cartIdSet(),
	_subReq() ,
	_subReqSet(),
	_distRuleId(),
	_distRuleIdSet(),
	_dissPackAlgoId(),
	_dissPackAlgoIdSet()

{
}


// copy constructor
dbDistributionItem::dbDistributionItem(const dbDistributionItem &o):
	dbPersistent(o),
	_idSet(o._idSet),
	_dueDate(o._dueDate) ,
	_dueDateSet(o._dueDateSet) ,
	_distributedDate(o._distributedDate) ,
	_distributedDateSet(o._distributedDateSet) ,
	_creationDate(o._creationDate) ,
	_creationDateSet(o._creationDateSet) ,
	_packageId(o._packageId) ,
	_packageIdSet(o._packageIdSet) ,
	_fileName(o._fileName) ,
	_fileNameSet(o._fileNameSet) ,
	_fileVersion(o._fileVersion) ,
	_fileVersionSet(o._fileVersionSet) ,
	_mediaType(o._mediaType) ,
	_mediaTypeSet(o._mediaTypeSet) ,
	_userId(o._userId) ,
	_userIdSet(o._userIdSet) ,
	_format(o._format) ,
	_formatSet(o._formatSet),
	_cartId(o._cartId) ,
	_cartIdSet(o._cartIdSet),
	_subReq(o._subReq) ,
	_subReqSet(o._subReqSet),
	_distRuleId(o._distRuleId),
	_distRuleIdSet(o._distRuleIdSet),
	_dissPackAlgoId(o._dissPackAlgoId),
	_dissPackAlgoIdSet(o._dissPackAlgoIdSet)
{
}


dbDistributionItem::~dbDistributionItem() throw()
{
}


// operator =
dbDistributionItem &dbDistributionItem::operator=(const dbDistributionItem &o)
{
	Lock guard(*this); // PRQA S 3050

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_idSet = o._idSet ;
		_dueDate=o._dueDate;
		_dueDateSet=o._dueDateSet;
		_distributedDate=o._distributedDate;
		_distributedDateSet=o._distributedDateSet;
		_creationDate=o._creationDate;
		_creationDateSet=o._creationDateSet;
		_packageId=o._packageId;
		_packageIdSet=o._packageIdSet;
		_fileName=o._fileName;
		_fileNameSet=o._fileNameSet;
		_fileVersion=o._fileVersion;
		_fileVersionSet=o._fileVersionSet;
		_mediaType=o._mediaType;
		_mediaTypeSet=o._mediaTypeSet;
		_userId=o._userId;
		_userIdSet=o._userIdSet;
		_format=o._format;
		_formatSet=o._formatSet;
		_cartId=o._cartId;
		_cartIdSet=o._cartIdSet;
		_subReq=o._subReq;
		_subReqSet=o._subReqSet;
		_distRuleId = o._distRuleId ;
		_distRuleIdSet = o._distRuleIdSet ;
		_dissPackAlgoId = o._dissPackAlgoId ;
		_dissPackAlgoIdSet = o._dissPackAlgoIdSet ;
	}
	return *this ;
}


dbPersistent *dbDistributionItem::clone() const
{
	Lock guard(*this); // PRQA S 3050

	return new dbDistributionItem(*this) ;
}


string dbDistributionItem::className() const
{
	return staticClassName() ;
}


string dbDistributionItem::staticClassName()
{
	return "dbDistributionItem" ;
}


// initialize the class
void dbDistributionItem::reset()
{
	Lock guard(*this); // PRQA S 3050

	// reset dbPersistent
	dbPersistent::reset() ;
	_dueDate.reset() ;
	_dueDateSet=false ;
	_distributedDate.reset() ;
	_distributedDateSet=false ;
	_creationDate.reset() ;
	_creationDateSet=false ;
	_packageId=0 ;
	_packageIdSet=false ;
	_fileName="" ;
	_fileNameSet=false ;
	_fileVersion="" ;
	_fileVersionSet=false ;
	_mediaType="" ;
	_mediaTypeSet=false ;
	_userId="" ;
	_userIdSet=false ;
	_format="" ;
	_formatSet=false ;
	_cartId=0 ;
	_cartIdSet=false ;
	_subReq=0 ;
	_subReqSet=false ;
	_distRuleId = 0 ;
	_distRuleIdSet = false ;
	_dissPackAlgoId = 0;
	_dissPackAlgoIdSet = false;
}


// save the data in database
dbPersistent::IdType dbDistributionItem::save(dbConnection &conn) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	if (!isModified()) {
		return getId() ;
    } 

	if (isFromDatabase()) 
	{
		ACS_THROW(InvalidUse("Use the method update() instead of save().")) ; // PRQA S 3081
	}

	if(!_dueDateSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Due Date\" must be set.")) ; // PRQA S 3081
	}
	if(!_fileNameSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"File Name\" must be set.")) ; // PRQA S 3081
	}
	if(!_fileVersionSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"File Version\" must be set.")) ; // PRQA S 3081
	}
	if(!_mediaTypeSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Media Type\" must be set.")) ; // PRQA S 3081
	}
	if(!_userIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Id\" must be set.")) ; // PRQA S 3081
	}
	if(!_distRuleIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Distribution Rule\" must be set.")) ; // PRQA S 3081
	}

	if (!_dissPackAlgoIdSet)
	{
		ACS_THROW(InvalidUse("Mandatory field \"Dissemination Packing Algo Id\" must be set.")) ; // PRQA S 3081
	}

    db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistributionItem_SAVE") ;
	conn.addStateWrapper(*this) ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "INSERT INTO T_DistributionItems (" ;
		queryString += "DueDate" ;
		if(_distributedDateSet) {
			queryString += ", DistributedDate" ;
        }
		if(_creationDateSet) {
			queryString += ", CreationDate" ;
        }
		if(_packageIdSet) {
			queryString += ", PackageId" ;
        }
		queryString += ", FileName" ;
		queryString += ", FileVersion" ;
		queryString += ", MediaType" ;
		queryString += ", UserId" ;
		if (_formatSet)
		{
			queryString += ", Format" ;
		}
		if(_cartIdSet) {
			queryString += ", CartId" ;
        }
		if(_subReqSet) {
			queryString += ", SubReq" ;
        }
		queryString += ", DistributionRule_ID";
		queryString += ", DisseminationPackingAlgo_ID";
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey,_dueDate,dbConv::YearToFraction) ;
		if(_distributedDateSet) {
			queryString +=	", " + db::toSQL(dbKey,_distributedDate,dbConv::YearToFraction) ;
        }
		if(_creationDateSet) {
			queryString +=	", " + db::toSQL(dbKey,_creationDate,dbConv::YearToFraction) ;
        }
		if(_packageIdSet) {
			queryString +=	", " + db::toSQL(dbKey,_packageId) ;
        }
		queryString +=	", " + db::toSQL(dbKey,_fileName) ;
		queryString +=	", " + db::toSQL(dbKey,_fileVersion) ;
		queryString +=	", " + db::toSQL(dbKey,_mediaType) ;
		queryString +=	", " + db::toSQL(dbKey,_userId) ;
		if (_formatSet)
		{
			queryString +=	", " + db::toSQL(dbKey,_format) ;
		}
		if(_cartIdSet) {
			queryString +=	", " + db::toSQL(dbKey,_cartId) ;
        }
		if(_subReqSet) {
			queryString +=	", " + db::toSQL(dbKey,_subReq) ;
        }
		queryString +=	", " + db::toSQL(dbKey,_distRuleId) ;
		queryString +=	", " + db::toSQL(dbKey,_dissPackAlgoId) ;
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString,"SaveDistributionItem") ;

	if (!query.execForStatus())
	{
			ACS_THROW(dbQuery::QueryExecuteException("Query Execution error: Command : " // PRQA S 3081
			    + queryString + " Error : "	+ query.errorString())) ; 
	}

    // obtain the last serial just inserted
    setId(getLastSerial(conn, "T_DistributionItems")) ;

	transaction.commit() ;
	// record that the values come from the database
	setFromDatabase() ; 
	return getId() ;
}


// load the class from the database. Return true if object exist
bool dbDistributionItem::load(dbConnection &conn , IdType id) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	IdType Id=id;

	if(Id == 0) {
		Id=getId() ;
    }
    
	if(Id==0)
	{
		ACS_THROW(IdNotProvided("Cannot obtain \"Id\"")) ; // PRQA S 3081
	}

	dbDistributionItem tempRecord(*this); //store current record.


	reset() ; 


	string queryString ;

    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	privateGetFields() ;
		queryString += " FROM T_DistributionItems" ;
		queryString += " WHERE Id = " ;
		queryString +=	db::toSQL(dbKey,Id) ;
		string getOrderByString(privateGetOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos) {
				queryString += getOrderByString ;
            }
			else {
				queryString += " ORDER BY " + getOrderByString ;
            }
		}
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString,"LoadDistributionItem") ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString)  ;

	dbRow row(conn.getKey()) ;
	dbSet setQ;
	query.execForSet(setQ) ;
    if (setQ.size() > 1) // it should not occur
    {
        ACS_THROW(InvalidUse("Unexpected query result dimension: it should return just one row"));
    }
    else
    {
		if ( not setQ.getNextRow(row) )
        {
			*this = tempRecord;  //Nothing found: restore previuos situation.
			return false ;
        }
	}
		
	privateLoadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbDistributionItem::update(dbConnection &conn) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	if (0 == getId())
	{
		ACS_THROW(ObjectNotLoaded("Use the method save() instead.")) ;  // PRQA S 3081
	}

	if (!isFromDatabase())
	{
		ACS_THROW(ObjectNotLoaded("Use the method save() instead of update().")) ;  // PRQA S 3081
	}

	if (!isModified()) {
		return 0 ; 
    }

	if(!_dueDateSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Due Date\" must be set.")) ;  // PRQA S 3081
	}
	if(!_fileNameSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"File Name\" must be set.")) ;  // PRQA S 3081
	}
	if(!_fileVersionSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"File Version\" must be set.")) ;  // PRQA S 3081
	}
	if(!_mediaTypeSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Media Type\" must be set.")) ;  // PRQA S 3081
	}
	if(!_userIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Id\" must be set.")) ;  // PRQA S 3081
	}
	if(!_distRuleIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Distribution Rule\" must be set.")) ;  // PRQA S 3081
	}

	if (!_dissPackAlgoIdSet)
	{
		ACS_THROW(InvalidUse("Mandatory field \"Dissemination Packing Algo Id\" must be set.")) ;  // PRQA S 3081
	}
    db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistributionItem_UPDATE") ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "UPDATE T_DistributionItems SET " ; 
		queryString += "DueDate= " + db::toSQL(dbKey,_dueDate,dbConv::YearToFraction) ;
		if(_distributedDateSet) {
			queryString += ", DistributedDate= " + db::toSQL(dbKey,_distributedDate,dbConv::YearToFraction) ;
        }
		else {
			queryString += ", DistributedDate=  NULL " ; 
        }
		if(_creationDateSet) {
			queryString += ", CreationDate= " + db::toSQL(dbKey,_creationDate,dbConv::YearToFraction) ;
        }
		else {
			queryString += ", CreationDate=  NULL " ; 
        }
		if(_packageIdSet) {
			queryString += ", PackageId= " + db::toSQL(dbKey,_packageId) ;
        }
		else {
			queryString += ", PackageId=  NULL " ; 
        }
		queryString += ", FileName= " + db::toSQL(dbKey,_fileName) ;
		queryString += ", FileVersion= " + db::toSQL(dbKey,_fileVersion) ;
		queryString += ", MediaType= " + db::toSQL(dbKey,_mediaType) ;
		queryString += ", UserId= " + db::toSQL(dbKey,_userId) ;
		if (_formatSet)
		{
			queryString += ", Format= " + db::toSQL(dbKey,_format) ;
		}
		if(_cartIdSet) {
			queryString +=", CartId= " + db::toSQL(dbKey,_cartId) ;
        }
		else {
			queryString +=", CartId= NULL";
        }
		if(_subReqSet) {
			queryString +=", SubReq= " + db::toSQL(dbKey,_subReq) ;
        }
		else {
			queryString +=", SubReq= NULL";
        }

		if(_distRuleIdSet) {
			queryString +=", DistributionRule_Id= " + db::toSQL(dbKey,_distRuleId) ;
		}
        else {
			queryString +=", DistributionRule_Id= NULL";
        }

		queryString +=", DisseminationPackingAlgo_Id= " + db::toSQL(dbKey,_dissPackAlgoId) ;
		queryString += " WHERE " ;
		queryString += "Id = " + db::toSQL(dbKey,getId()) ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey,SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString,"UpdateDistributionItem") ;

	query.execForStatus() ;
	transaction.commit() ;
	resetModifiedFlag() ;
	return getId() ;

}


// remove the class from the database
dbPersistent::IdType dbDistributionItem::remove(dbConnection &conn)
{
	Lock guard(*this); // PRQA S 3050

	if (0 == getId())
	{
		ACS_THROW(IdNotProvided("Id not set")) ; // PRQA S 3081
	}


    db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistributionItem_REMOVE") ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "DELETE FROM T_DistributionItems" ;
		queryString += " WHERE " ;
		queryString += "Id = " + db::toSQL(dbKey,getId()) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString,"RemoveDistributionItem") ;

	query.execForStatus() ;
	transaction.commit() ;


	resetFromDatabase() ;
	setModifiedFlag() ;

	return getId() ;
}


// True if the class have valid parameters, false otherwise
bool dbDistributionItem::validate() const
{
	Lock guard(*this); // PRQA S 3050

	return true;
}


// export the class to stream
void dbDistributionItem::exportObj(rsResourceSet &s) const
{
	Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbDistributionItem") ;
	dbPersistent::exportObj(s) ;

	if(_idSet) {
		s.setValue("_id", getId()) ;
    }
	s.setValue("_idSet",_idSet) ;

	if(_dueDateSet)
	{
		rsPushNSpace rpns1(s,"_dueDate") ;
		_dueDate.exportObj(s) ;
	}
	s.setValue("_dueDateSet",_dueDateSet) ;

	if(_distributedDateSet)
	{
		rsPushNSpace rpns2(s,"_distributedDate") ;
		_distributedDate.exportObj(s) ;
	}
	s.setValue("_distributedDateSet",_distributedDateSet) ;

	if(_creationDateSet)
	{
		rsPushNSpace rpns3(s,"_creationDate") ;
		_creationDate.exportObj(s) ;
	}
	s.setValue("_creationDateSet",_creationDateSet) ;

	if(_packageIdSet) {
		s.setValue("_packageId",_packageId) ;
    }
	s.setValue("_packageIdSet",_packageIdSet) ;

	if(_fileNameSet) {
		s.setValue("_fileName",_fileName) ;
    }
	s.setValue("_fileNameSet",_fileNameSet) ;

	if(_fileVersionSet) {
		s.setValue("_fileVersion",_fileVersion) ;
    }
	s.setValue("_fileVersionSet",_fileVersionSet) ;

	if(_mediaTypeSet) {
		s.setValue("_mediaType",_mediaType) ;
    }
	s.setValue("_mediaTypeSet",_mediaTypeSet) ;

	if(_userIdSet) {
		s.setValue("_userId",_userId) ;
    }
	s.setValue("_userIdSet",_userIdSet) ;

	if(_formatSet) {
		s.setValue("_format",_format) ;
    }
	s.setValue("_formatSet",_formatSet) ;

	if(_cartIdSet) {
		s.setValue("_cartId",_cartId) ;
    }
	s.setValue("_cartIdSet",_cartIdSet) ;

	if(_subReqSet) {
		s.setValue("_subReq",_subReq) ;
    }
	s.setValue("_subReqSet",_subReqSet) ;

	if(_distRuleIdSet) {
		s.setValue("_distRuleIdSet",_distRuleIdSet) ;
    }
	s.setValue("_distRuleId",_distRuleId) ;

	if (_dissPackAlgoIdSet) {
		s.setValue("_dissPackAlgoIdSet",_dissPackAlgoIdSet) ;
    }
	s.setValue("_dissPackAlgoId",_dissPackAlgoId) ;

}


// import the class from a stream
void dbDistributionItem::importObj(rsResourceSet &s)
{
	Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbDistributionItem") ;
	dbPersistent::importObj(s) ;
	reset() ;
	s.getValue("_idSet",_idSet) ;
	if(_idSet)
	{
		IdType id = 0 ;
		s.getValue("_id", id) ;
		setId(id) ;
	}

	s.getValue("_dueDateSet",_dueDateSet) ;
	if(_dueDateSet)
	{
		rsPushNSpace rpns1(s,"_dueDate") ;
		_dueDate.importObj(s) ;
	}

	s.getValue("_distributedDateSet",_distributedDateSet) ;
	if(_distributedDateSet)
	{
		rsPushNSpace rpns2(s,"_distributedDate") ;
		_distributedDate.importObj(s) ;
	}

	s.getValue("_creationDateSet",_creationDateSet) ;
	if(_creationDateSet)
	{
		rsPushNSpace rpns3(s,"_creationDate") ;
		_creationDate.importObj(s) ;
	}

	s.getValue("_packageIdSet",_packageIdSet) ;
	if(_packageIdSet) {
		s.getValue("_packageId",_packageId) ;
    }

	s.getValue("_fileNameSet",_fileNameSet) ;
	if(_fileNameSet) {
		s.getValue("_fileName",_fileName) ;
    }

	s.getValue("_fileVersionSet",_fileVersionSet) ;
	if(_fileVersionSet) {
		s.getValue("_fileVersion",_fileVersion) ;
    }

	s.getValue("_mediaTypeSet",_mediaTypeSet) ;
	if(_mediaTypeSet) {
		s.getValue("_mediaType",_mediaType) ;
    }

	s.getValue("_userIdSet",_userIdSet) ;
	if(_userIdSet) {
		s.getValue("_userId",_userId) ;
    }

	s.getValue("_formatSet",_formatSet) ;
	if(_formatSet) {
		s.getValue("_format",_format) ;
    }


	s.getValue("_cartIdSet",_cartIdSet) ;
	if(_cartIdSet) {
		s.getValue("_cartId",_cartId) ;
    }

	s.getValue("_subReqSet",_subReqSet) ;
	if(_subReqSet) {
		s.getValue("_subReq",_subReq) ;
    }
	s.getValue("_distRuleIdSet",_distRuleIdSet) ;
	if(_distRuleIdSet) {
		s.getValue("_distRuleId",_distRuleId) ;
    }

	s.getValue("_dissPackAlgoId",_dissPackAlgoId) ;
	if (_dissPackAlgoIdSet) {
		s.getValue("_dissPackAlgoIdSet",_dissPackAlgoIdSet) ;
    }
}


// export the class to XML stream
void dbDistributionItem::exportXML(XMLOstream &xst) const
{
	Lock guard(*this); // PRQA S 3050
    const string dbKey="" ;
	XMLOstream::Tag txml(xst, "dbDistributionItem");
	dbPersistent::exportXML(xst) ;
    string null = "<null>" ;
	if(_idSet)
	{
		ostringstream os;
		os << getId();
		XMLOstream::Tag txml0(xst, "_id", os.str(), "label=\"Id\"");
	}
	else
	{
		XMLOstream::Tag txml0(xst, "_id", null, "label=\"Id\"");
	}
	{
		XMLOstream::Tag txml0Set(xst, "_idSet", (_idSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_dueDateSet)
	{
		XMLOstream::Tag txml1(xst, "_dueDate", "", "label=\"Due Date\"");
		_dueDate.exportXML(xst) ;
	}
	else
	{
		XMLOstream::Tag txml1(xst, "_dueDate", null, "label=\"Due Date\"");
	}
	{
		XMLOstream::Tag txml1Set(xst, "_dueDateSet", (_dueDateSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_distributedDateSet)
	{
		XMLOstream::Tag txml2(xst, "_distributedDate", "", "label=\"Distributed Date\"");
		_distributedDate.exportXML(xst) ;
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_distributedDate", null, "label=\"Distributed Date\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_distributedDateSet", (_distributedDateSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_creationDateSet)
	{
		XMLOstream::Tag txml3(xst, "_creationDate", "", "label=\"Creation Date\"");
		_creationDate.exportXML(xst) ;
	}
	else
	{
		XMLOstream::Tag txml3(xst, "_creationDate", null, "label=\"Creation Date\"");
	}
	{
		XMLOstream::Tag txml3Set(xst, "_creationDateSet", (_creationDateSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_packageIdSet)
	{
		XMLOstream::Tag txml4(xst, "_packageId", db::toSQL(dbKey,_packageId), "label=\"Package Id\"");
	}
	else
	{
		XMLOstream::Tag txml4(xst, "_packageId", null, "label=\"Package Id\"");
	}
	{
		XMLOstream::Tag txml4Set(xst, "_packageIdSet", (_packageIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_fileNameSet)
	{
		XMLOstream::Tag txml5(xst, "_fileName", _fileName, "label=\"File Name\"");
	}
	else
	{
		XMLOstream::Tag txml5(xst, "_fileName", null, "label=\"File Name\"");
	}
	{
		XMLOstream::Tag txml5Set(xst, "_fileNameSet", (_fileNameSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_fileVersionSet)
	{
		XMLOstream::Tag txml6(xst, "_fileVersion", _fileVersion, "label=\"File Version\"");
	}
	else
	{
		XMLOstream::Tag txml6(xst, "_fileVersion", null, "label=\"File Version\"");
	}
	{
		XMLOstream::Tag txml6Set(xst, "_fileVersionSet", (_fileVersionSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_mediaTypeSet)
	{
		XMLOstream::Tag txml7(xst, "_mediaType", _mediaType, "label=\"Media Type\"");
	}
	else
	{
		XMLOstream::Tag txml7(xst, "_mediaType", null, "label=\"Media Type\"");
	}
	{
		XMLOstream::Tag txml7Set(xst, "_mediaTypeSet", (_mediaTypeSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_userIdSet)
	{
		XMLOstream::Tag txml8(xst, "_userId", _userId, "label=\"User Id\"");
	}
	else
	{
		XMLOstream::Tag txml8(xst, "_userId", null, "label=\"User Id\"");
	}
	{
		XMLOstream::Tag txml8Set(xst, "_userIdSet", (_userIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_formatSet)
	{
		XMLOstream::Tag txml9(xst, "_format", _format, "label=\"Format\"");
	}
	else
	{
		XMLOstream::Tag txml9(xst, "_format", null, "label=\"Format\"");
	}
	{
		XMLOstream::Tag txml9Set(xst, "_formatSet", (_formatSet ? "true" : "false")) ; // PRQA S 3380
	}



	if(_cartIdSet)
	{
		XMLOstream::Tag txml4(xst, "_cartId", db::toSQL(dbKey,_cartId), "label=\"Cart Id\"");
	}
	else
	{
		XMLOstream::Tag txml4(xst, "_cartId", null, "label=\"Cart Id\"");
	}
	{
		XMLOstream::Tag txml4Set(xst, "_cartIdSet", (_cartIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_subReqSet)
	{
		XMLOstream::Tag txml4(xst, "_subReq", db::toSQL(dbKey,_subReq), "label=\"SubReq\"");
	}
	else
	{
		XMLOstream::Tag txml4(xst, "_subReq", null, "label=\"SubReq\"");
	}
	{
		XMLOstream::Tag txml4Set(xst, "_subReqSet", (_subReqSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_distRuleIdSet)
	{
		XMLOstream::Tag txml4(xst, "_distRuleId", db::toSQL(dbKey,_distRuleId), "label=\"DistributionRuleId\"");
	}
	else
	{
		XMLOstream::Tag txml4(xst, "_distRuleId", null, "label=\"DistributionRuleId\"");
	}
	{
		XMLOstream::Tag txml4Set(xst, "_distRuleIdSet", (_distRuleIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_dissPackAlgoIdSet)
	{
		XMLOstream::Tag txml4(xst, "_dissPackAlgoId", db::toSQL(dbKey,_dissPackAlgoId), "label=\"DistributionPackingAlgoId\"");
	}
	else
	{
		XMLOstream::Tag txml4(xst, "_dissPackAlgoId", null, "label=\"DistributionPackingAlgoId\"");
	}
	{
		XMLOstream::Tag txml4Set(xst, "_dissPackAlgoIdSet", (_dissPackAlgoIdSet ? "true" : "false")) ; // PRQA S 3380
	}

}




// load the object from a row
int dbDistributionItem::loadRow(const dbRow &row, int offset)
{
	Lock guard(*this); // PRQA S 3050

	return privateLoadRow(row, offset) ;

}


// load the object from a row
int dbDistributionItem::privateLoadRow(const dbRow &row, int offset)
{
	Lock guard(*this); // PRQA S 3050

	IdType id = 0 ;

	row.columnSet(offset + 0, id , _idSet) ; // PRQA S 3000, 3010 L_pLR

	setId(id) ;
    int currentf = 1 ;
	row.columnSet(offset + currentf++, _dueDate, _dueDateSet) ;
	row.columnSet(offset + currentf++, _distributedDate, _distributedDateSet) ;
	row.columnSet(offset + currentf++, _creationDate, _creationDateSet) ;
	row.columnSet(offset + currentf++, _packageId, _packageIdSet) ;
	row.columnSet(offset + currentf++, _fileName, _fileNameSet) ;
	row.columnSet(offset + currentf++, _fileVersion, _fileVersionSet) ;
	row.columnSet(offset + currentf++, _mediaType, _mediaTypeSet) ;
	row.columnSet(offset + currentf++, _userId, _userIdSet) ;
	row.columnSet(offset + currentf++, _format, _formatSet) ;
	row.columnSet(offset + currentf++, _cartId, _cartIdSet) ;
	row.columnSet(offset + currentf++, _subReq, _subReqSet) ;
	row.columnSet(offset + currentf++, _distRuleId, _distRuleIdSet) ;
	row.columnSet(offset + currentf++, _dissPackAlgoId, _dissPackAlgoIdSet) ;

	setFromDatabase() ;

	return offset + currentf;
    // PRQA L:L_pLR
}


string dbDistributionItem::getWhere()
{
	string res ;
	return res ;
}


string dbDistributionItem::getIdName()
{
	return "T_DistributionItems.Id" ;
}




void dbDistributionItem::setDueDate(const DateTime &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_dueDateSet || _dueDate != v ) 
	{
		_dueDate = v ;
		_dueDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistributionItem::getDueDate(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _dueDateSet ; }
	return _dueDate ;
}


void dbDistributionItem::unsetDueDate()
{
	Lock guard(*this); // PRQA S 3050
	if(_dueDateSet == true) {
		setModifiedFlag();
    }
	_dueDateSet = false;

}
void dbDistributionItem::setDistributedDate(const DateTime &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_distributedDateSet || (_distributedDate != v ) )
	{
		_distributedDate = v ;
		_distributedDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistributionItem::getDistributedDate(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _distributedDateSet ; }
	return _distributedDate ;
}


void dbDistributionItem::unsetDistributedDate()
{
	Lock guard(*this); // PRQA S 3050
	if(_distributedDateSet == true) { setModifiedFlag(); }
	_distributedDateSet = false;

}
void dbDistributionItem::setCreationDate(const DateTime &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_creationDateSet || (_creationDate != v ) )
	{
		_creationDate = v ;
		_creationDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistributionItem::getCreationDate(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _creationDateSet ; }
	return _creationDate ;
}


void dbDistributionItem::unsetCreationDate()
{
	Lock guard(*this); // PRQA S 3050
	if(_creationDateSet == true) {
		setModifiedFlag();
    }
	_creationDateSet = false;

}
void dbDistributionItem::setPackageId(IdType v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_packageIdSet || (_packageId != v ) )
	{
		_packageId = v ;
		_packageIdSet = true ;
		setModifiedFlag() ;
	}
}


dbPersistent::IdType dbDistributionItem::getPackageId(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _packageIdSet ; }
	return _packageId ;
}


void dbDistributionItem::unsetPackageId()
{
	Lock guard(*this); // PRQA S 3050
	if(_packageIdSet == true) {
		setModifiedFlag();
    }
	_packageIdSet = false;

}





void dbDistributionItem::setCartId(IdType v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_cartIdSet || (_cartId != v ) )
	{
		_cartId = v ;
		_cartIdSet = true ;
		setModifiedFlag() ;
	}
}


dbPersistent::IdType dbDistributionItem::getCartId(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _cartIdSet ; }
	return _cartId ;
}


void dbDistributionItem::unsetCartId()
{
	Lock guard(*this); // PRQA S 3050
	if(_cartIdSet == true) {
		setModifiedFlag();
    }
	_cartIdSet = false;

}

void dbDistributionItem::setSubReq(int v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_subReqSet || (_subReq != v )) 
	{
		_subReq = v ;
		_subReqSet = true ;
		setModifiedFlag() ;
	}
}


int dbDistributionItem::getSubReq(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _subReqSet ; }
	return _subReq ;
}


void dbDistributionItem::unsetSubReq()
{
	Lock guard(*this); // PRQA S 3050
	if(_subReqSet == true) {
		setModifiedFlag();
    }
	_subReqSet = false;

}

void dbDistributionItem::setFileName(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 128) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")) ; // PRQA S 3081
	}

	if (!_fileNameSet || _fileName != v ) 
	{
		_fileName = v ;
		_fileNameSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionItem::getFileName(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set){ *set = _fileNameSet ; }
	return _fileName ;
}


void dbDistributionItem::unsetFileName()
{
	Lock guard(*this); // PRQA S 3050
	if(_fileNameSet == true) {
		setModifiedFlag();
    }
	_fileNameSet = false;

}
void dbDistributionItem::setFileVersion(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 8) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")) ; // PRQA S 3081
	}

	if (!_fileVersionSet || (_fileVersion != v ) )
	{
		_fileVersion = v ;
		_fileVersionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionItem::getFileVersion(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _fileVersionSet ; }
	return _fileVersion ;
}


void dbDistributionItem::unsetFileVersion()
{
	Lock guard(*this); // PRQA S 3050
	if(_fileVersionSet == true) {
		setModifiedFlag();
    }
	_fileVersionSet = false;

}
void dbDistributionItem::setMediaType(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 16) // PRQA S 4400
	{
		ACS_THROW(InvalidUse( "String too long."))  ; // PRQA S 3081
	}

	if (!_mediaTypeSet || (_mediaType != v ) )
	{
		_mediaType = v ;
		_mediaTypeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionItem::getMediaType(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _mediaTypeSet ; }
	return _mediaType ;
}


void dbDistributionItem::unsetMediaType()
{
	Lock guard(*this); // PRQA S 3050
	if(_mediaTypeSet == true) {
		setModifiedFlag();
    }
	_mediaTypeSet = false;

}
void dbDistributionItem::setUserId(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse( "String too long."))  ; // PRQA S 3081
	}

	if (!_userIdSet || _userId != v ) 
	{
		_userId = v ;
		_userIdSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionItem::getUserId(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _userIdSet ; }
	return _userId ;
}


void dbDistributionItem::unsetUserId()
{
	Lock guard(*this); // PRQA S 3050
	if(_userIdSet == true) {
		setModifiedFlag();
    }
	_userIdSet = false;

}
void dbDistributionItem::setFormat(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_formatSet || (_format != v ) )
	{
		_format = v ;
		_formatSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionItem::getFormat(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _formatSet ; }
	return _format ;
}


void dbDistributionItem::unsetFormat()
{
	Lock guard(*this); // PRQA S 3050
	if(_formatSet == true) {
		setModifiedFlag();
    }
	_formatSet = false;

}



// get the field names
string dbDistributionItem::getFields()
{
	string s ;
	s += privateGetFields() ;
	return s ;
}

void dbDistributionItem::setDistributionRuleId(IdType v) 
{
	Lock guard(*this); // PRQA S 3050

	if (!_distRuleIdSet || (_distRuleId != v ) )
	{
		_distRuleId = v ;
		_distRuleIdSet = true ;
		setModifiedFlag() ;
	}
}

dbPersistent::IdType dbDistributionItem::getDistributionRuleId(bool *set) const 
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _distRuleIdSet ; }
	return _distRuleId ;
}

void dbDistributionItem::unsetDistributionRuleId()
{
	Lock guard(*this); // PRQA S 3050
	if(_distRuleIdSet == true) {
		setModifiedFlag();
    }
	_distRuleIdSet = false;
}

void dbDistributionItem::setDisseminationPackingAlgoId(IdType v) 
{
	Lock guard(*this); // PRQA S 3050

	if (!_dissPackAlgoIdSet || (_dissPackAlgoId != v ) )
	{
		_dissPackAlgoId = v ;
		_dissPackAlgoIdSet = true ;
		setModifiedFlag() ;
	}
}

dbPersistent::IdType dbDistributionItem::getDisseminationPackingAlgoId(bool *set) const 
{
	Lock guard(*this); // PRQA S 3050

	if (set) {
		*set = _dissPackAlgoIdSet ;
    }
	return _dissPackAlgoId ;
}

void dbDistributionItem::unsetDisseminationPackingAlgoId()
{
	Lock guard(*this); // PRQA S 3050
	if(_dissPackAlgoIdSet == true) {
		setModifiedFlag();
    }
	_dissPackAlgoIdSet = false;
}

// get the field names
string dbDistributionItem::privateGetFields()
{
	string s ;
	s += "T_DistributionItems.Id, ";
	s += "T_DistributionItems.DueDate, ";
	s += "T_DistributionItems.DistributedDate, ";
	s += "T_DistributionItems.CreationDate, ";
	s += "T_DistributionItems.PackageId, ";
	s += "T_DistributionItems.FileName, ";
	s += "T_DistributionItems.FileVersion, ";
	s += "T_DistributionItems.MediaType, ";
	s += "T_DistributionItems.UserId, ";
	s += "T_DistributionItems.Format," ;
	s += "T_DistributionItems.CartId," ;
	s += "T_DistributionItems.SubReq" ;
	s += ",T_DistributionItems.DistributionRule_Id" ;
	s += ",T_DistributionItems.DisseminationPackingAlgo_Id" ;
	return s ;
}


// get the table name
string dbDistributionItem::getTable()
{
	return "T_DistributionItems" ;
}


// get the order by clause
string dbDistributionItem::getOrderBy()
{
	string res ;
	res += privateGetOrderBy() ;
	return res ;
}


// get the order by clause
string dbDistributionItem::privateGetOrderBy()
{
	string res ;
	return res ;
}

void dbDistributionItem::writeTo(ostream &o) const
{
	Lock guard(*this); // PRQA S 3050
    const string dbKey="" ;
    string null = "<null>" ;
	string tmp ; 

	o
		 << "_id = " << (_idSet ?  db::toSQL(dbKey,getId()) : null) << "\n" // PRQA S 3380, 3385 L1
		 << "_dueDate = " << (_dueDateSet ? _dueDate.utcs(tmp) : null) << "\n" 
		 << "_distributedDate = " << (_distributedDateSet ? _distributedDate.utcs(tmp) : null) << "\n" 
		 << "_creationDate = " << (_creationDateSet ? _creationDate.utcs(tmp) : null) << "\n" 
		 << "_packageId = " << (_packageIdSet ? db::toSQL(dbKey,_packageId) : null) << "\n" 
		 << "_fileName = " << (_fileNameSet ? _fileName : null) << "\n" 
		 << "_fileVersion = " << (_fileVersionSet ? _fileVersion : null) << "\n" 
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : null) << "\n" 
		 << "_userId = " << (_userIdSet ? _userId : null) << "\n" 
		 << "_format = " << (_formatSet ? _format : null) << "\n"  
		 << "_cartId = " << (_cartIdSet ? db::toSQL(dbKey,_cartId) : null) << "\n"  
		 << "_subReq = " << (_subReqSet ? db::toSQL(dbKey,_subReq) : null) << "\n"
		 << "_distRuleId = " << (_distRuleIdSet ? db::toSQL(dbKey,_distRuleId) : null) << "\n"
		 << "_dissPackAlgoId = " << (_dissPackAlgoIdSet ? db::toSQL(dbKey,_dissPackAlgoId) : null) << "\n"
    ;
    // PRQA L:L1
}


void dbDistributionItem::writeTo(exostream &o) const
{
	Lock guard(*this); // PRQA S 3050
    const string dbKey="" ;
    string null = "<null>" ;
	string tmp ; 

	o
		 << "_id = " << (_idSet ?  db::toSQL(dbKey,getId()) : null) << "\n"  // PRQA S 3380, 3385 L2
		 << "_dueDate = " << (_dueDateSet ? _dueDate.utcs(tmp) : null) << "\n" 
		 << "_distributedDate = " << (_distributedDateSet ? _distributedDate.utcs(tmp) : null) << "\n" 
		 << "_creationDate = " << (_creationDateSet ? _creationDate.utcs(tmp) : null) << "\n" 
		 << "_packageId = " << (_packageIdSet ? db::toSQL(dbKey,_packageId) : null) << "\n" 
		 << "_fileName = " << (_fileNameSet ? _fileName : null) << "\n" 
		 << "_fileVersion = " << (_fileVersionSet ? _fileVersion : null) << "\n" 
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : null) << "\n" 
		 << "_userId = " << (_userIdSet ? _userId : null) << "\n" 
		 << "_format = " << (_formatSet ? _format : null) << "\n"  
		 << "_cartId = " << (_cartIdSet ? db::toSQL(dbKey,_cartId) : null) << "\n"  
		 << "_subReq = " << (_subReqSet ? db::toSQL(dbKey,_subReq) : null) << "\n"
		 << "_distRuleId = " << (_distRuleIdSet ? db::toSQL(dbKey,_distRuleId) : null) << "\n"
		 << "_dissPackAlgoId = " << (_dissPackAlgoIdSet ? db::toSQL(dbKey,_dissPackAlgoId) : null) << "\n"
    ;
    // PRQA L:L2
}
_ACS_END_NAMESPACE
