/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/27 14:33:37  damdec
	CSGACQ-86: compilation warnings fixed.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.3  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:54  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:21  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.9  2013/04/12 12:14:37  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.8  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.7  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.6  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.5  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.4  2010/03/05 15:09:10  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.3  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.2  2006/06/09 12:45:58  giucas
	Fixed syntax error in update query.
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.9  2005/08/31 11:50:28  marpas
	ace no longer used, includes are removed
	
	Revision 1.8  2005/06/15 07:44:49  integrator
	multiple storage manager implemented
	
	Revision 1.7  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.6  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.5  2004/10/04 15:13:52  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.4  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.3  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.2  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.1  2004/04/16 16:33:19  paoscu
	dbDistributionFormat added.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbDistributionFormat.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbDistributionFormat)

// constructor
dbDistributionFormat::dbDistributionFormat() :
	dbPersistent(),
	_format() ,
	_formatSet(false) ,
	_description() ,
	_descriptionSet(false)
{
}


// copy constructor
dbDistributionFormat::dbDistributionFormat(const dbDistributionFormat &o):
	dbPersistent(o),
	_format(o._format) ,
	_formatSet(o._formatSet) ,
	_description(o._description) ,
	_descriptionSet(o._descriptionSet)
{
}


dbDistributionFormat::~dbDistributionFormat() throw()
{
}


// operator =
dbDistributionFormat &dbDistributionFormat::operator=(const dbDistributionFormat &o)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050 2
	ThreadSafe::Lock lo(o);

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_format=o._format;
		_formatSet=o._formatSet;
		_description=o._description;
		_descriptionSet=o._descriptionSet;
	}
	return *this ;
}


dbPersistent *dbDistributionFormat::clone() const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	return new dbDistributionFormat(*this) ;
}


string dbDistributionFormat::className() const
{
	return staticClassName() ;
}


string dbDistributionFormat::staticClassName()
{
	return "dbDistributionFormat" ;
}


// initialize the class
void dbDistributionFormat::reset()
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	// reset dbPersistent
	dbPersistent::reset() ;
	_format="" ;
	_formatSet=false ;
	_description="" ;
	_descriptionSet=false ;
}


// save the data in database
dbPersistent::IdType dbDistributionFormat::save(dbConnection &conn)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (!isModified())
		return 0 ; 

	if (isFromDatabase()) 
	{
		InvalidUse e("Error: dbDistributionFormat::save(). Use the method update() instead of save().") ;
		ACS_THROW(e) ;
	}

	if(!_formatSet) 
	{
		InvalidUse e("Mandatory field \"Format\" must be set.") ;
		ACS_THROW(e) ;
	}


	db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistributionFormat_SAVE") ;
	conn.addStateWrapper(*this) ;


    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "INSERT INTO T_DistributionFormat (" ;
		queryString += "Format" ;
		if(_descriptionSet)
			queryString += ", Description" ;
		queryString +=	") VALUES ( " ;
		queryString +=	 db::toSQL(dbKey, _format) ;
		if(_descriptionSet)
			queryString +=	string(", ") +  db::toSQL(dbKey, _description) ;
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbDistributionFormat::save") ;

	if (!query.execForStatus())
	{
			dbQuery::QueryExecuteException e(string("Query Execution error: Command : ")
			+ string(queryString)
			+ string(" Error : ")
			+ string(query.errorString())) ;
			ACS_THROW (e) ;
	}

	transaction.commit() ;
    
	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbDistributionFormat::load(dbConnection &conn , IdType id)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050
	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB) ;

	dbDistributionFormat tempRecord(*this); //store current record.


	reset() ; 

    const string &dbKey = conn.getKey() ;
	dbRow row(dbKey) ;

	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "SELECT " ;
		queryString +=	privateGetFields() ;
		queryString += " FROM T_DistributionFormat" ;
		queryString += " WHERE Format " ;
		if(tempRecord._formatSet)
			queryString +=	string("= ") +  db::toSQL(dbKey, tempRecord._format) ;
		else
			queryString +=	" IS NULL" ;
		string getOrderByString(privateGetOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos)
				queryString += getOrderByString ;
			else
				queryString += " ORDER BY " + getOrderByString ;
		}
		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbDistributionFormat::load") ;


	dbSet setQ;
	query.execForSet(setQ) ;
    if (setQ.size() > 1) // it should not occur
    {
        ACS_THROW(InvalidUse("Unexpected query result dimension: it should return just one row"));
    }
    else
    {
		if ( not setQ.getNextRow(row) )
        {
        	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "No " << getTable() << " record found ");
			*this = tempRecord;  //Nothing found: restore previuos situation.
			return false ;
        }
	}

	privateLoadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbDistributionFormat::update(dbConnection &conn)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (!isFromDatabase())
	{
		ObjectNotLoaded ex("Error: dbDistributionFormat::update(). Use the method save() instead of update().") ; 
		ACS_THROW(ex)
	}

	if (!isModified())
		return 0 ; 

	if(!_formatSet) 
	{
		InvalidUse e("Mandatory field \"Format\" must be set.") ;
		ACS_THROW(e) ;
	}

	db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistributionFormat_UPDATE") ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = string("UPDATE T_DistributionFormat SET ") ; 
		if(_descriptionSet)
			queryString += "Description= " +  db::toSQL(dbKey, _description) ;
		else
			queryString += "Description=  NULL " ; 
		queryString += " WHERE " ;
		queryString += "Format " ;
		queryString +=	string("= ") +  db::toSQL(dbKey, _format) ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "dbDistributionFormat::update") ;

	query.execForStatus() ;
	transaction.commit() ;

	resetModifiedFlag() ;
	return 0 ;

}


// remove the class from the database
dbPersistent::IdType dbDistributionFormat::remove(dbConnection &conn)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistributionFormat_REMOVE") ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "DELETE FROM T_DistributionFormat" ;
		queryString += " WHERE " ;
		queryString += "Format " ;
		if(_formatSet)
			queryString +=	string("= ") +  db::toSQL(dbKey, _format) ;
		else
			queryString +=	"IS NULL" ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "dbDistributionFormat::remove") ;

	query.execForStatus() ;
	
    transaction.commit() ;


	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbDistributionFormat::validate() const
{
	return true;
}


// export the class to stream
void dbDistributionFormat::exportObj(rsResourceSet &s) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbDistributionFormat") ;
	dbPersistent::exportObj(s) ;

	if(_formatSet)
		s.setValue("_format",_format) ;
	s.setValue("_formatSet",_formatSet) ;

	if(_descriptionSet)
		s.setValue("_description",_description) ;
	s.setValue("_descriptionSet",_descriptionSet) ;

}


// import the class from a stream
void dbDistributionFormat::importObj(rsResourceSet &s)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbDistributionFormat") ;
	dbPersistent::importObj(s) ;
	reset() ;
	s.getValue("_formatSet",_formatSet) ;
	if(_formatSet)
		s.getValue("_format",_format) ;

	s.getValue("_descriptionSet",_descriptionSet) ;
	if(_descriptionSet)
		s.getValue("_description",_description) ;

}


// export the class to XML stream
void dbDistributionFormat::exportXML(XMLOstream &xst) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbDistributionFormat");
	dbPersistent::exportXML(xst) ;
	if(_formatSet)
	{
		XMLOstream::Tag txml0(xst, "_format", _format, "label=\"Format\"");
	}
	else
	{
		XMLOstream::Tag txml0(xst, "_format", string("<null>"), "label=\"Format\"");
	}
	{
		XMLOstream::Tag txml0Set(xst, "_formatSet", (_formatSet ? "true" : "false")) ;
	}

	if(_descriptionSet)
	{
		XMLOstream::Tag txml1(xst, "_description", _description, "label=\"Description\"");
	}
	else
	{
		XMLOstream::Tag txml1(xst, "_description", string("<null>"), "label=\"Description\"");
	}
	{
		XMLOstream::Tag txml1Set(xst, "_descriptionSet", (_descriptionSet ? "true" : "false")) ;
	}

}



// load the object from a row
int dbDistributionFormat::loadRow(const dbRow &row, int offset)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	return privateLoadRow(row, offset) ;

}


// load the object from a row
int dbDistributionFormat::privateLoadRow(const dbRow &row, int offset)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	row.columnSet(offset + 0, _format, _formatSet) ;
	row.columnSet(offset + 1, _description, _descriptionSet) ;


	setFromDatabase() ;

	return offset + 2 ;
}


string dbDistributionFormat::getWhere()
{
	string res ;
	return res ;
}


string dbDistributionFormat::getIdName()
{
	return "T_DistributionFormat.Format" ;
}



void dbDistributionFormat::setFormat(const string &v)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbDistributionFormat::setFormat(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 8)
	{
		InvalidUse e("Error: dbDistributionFormat::setFormat(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_formatSet || _format != v ) 
	{
		_format = v ;
		_formatSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionFormat::getFormat(bool *set) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (set)
		*set = _formatSet ;
	return _format ;
}


void dbDistributionFormat::unsetFormat()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbDistributionFormat::unsetFormat(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	ThreadSafe::Lock guard(*this); // PRQA S 3050
	if(_formatSet == true)
		setModifiedFlag();
	_formatSet = false;

}
void dbDistributionFormat::setDescription(const string &v)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (v.size() > 64)
	{
		InvalidUse e("Error: dbDistributionFormat::setDescription(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_descriptionSet || _description != v ) 
	{
		_description = v ;
		_descriptionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistributionFormat::getDescription(bool *set) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (set)
		*set = _descriptionSet ;
	return _description ;
}


void dbDistributionFormat::unsetDescription()
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050
	if(_descriptionSet == true)
		setModifiedFlag();
	_descriptionSet = false;

}
// get the field names
string dbDistributionFormat::getFields()
{
	string s ;
	s += privateGetFields() ;
	return s ;
}


// get the field names
string dbDistributionFormat::privateGetFields()
{
	string s ;
	s += "T_DistributionFormat.Format, ";
	s += "T_DistributionFormat.Description" ;
	return s ;
}


// get the table name
string dbDistributionFormat::getTable()
{
	return "T_DistributionFormat" ;
}


// get the order by clause
string dbDistributionFormat::getOrderBy()
{
	string res ;
	res += privateGetOrderBy() ;
	return res ;
}


// get the order by clause
string dbDistributionFormat::privateGetOrderBy()
{
	string res ;
	return res ;
}


void dbDistributionFormat::writeTo(ostream &o) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	o
		 << "_format = " << (_formatSet ? _format : string("<null>")) << endl 
		 << "_description = " << (_descriptionSet ? _description : string("<null>")) << endl  ;
}


void dbDistributionFormat::writeTo(exostream &o) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	o
		 << "_format = " << (_formatSet ? _format : string("<null>")) << endl 
		 << "_description = " << (_descriptionSet ? _description : string("<null>")) << endl  ;
}


_ACS_END_NAMESPACE
