// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/27 08:45:59  damdec
	CSGACQ-86: PDS_OLD_SCHEMA flag removed. Code reviewed: field Format is no mandatory.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/19 13:53:46  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:53  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:21  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.18  2013/04/30 13:31:42  marpas
	dbPersistent interface changed
	
	Revision 2.17  2013/04/17 17:37:24  marpas
	dbPersistent interface changed
	
	Revision 2.16  2013/04/12 12:14:37  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.15  2013/03/29 19:51:28  marpas
	removing html related functions
	
	Revision 2.14  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.13  2013/02/07 15:04:23  enrcar
	EC:: Modified to handle the tag PDS_OLD_SCHEMA
	
	Revision 2.12  2012/11/16 13:01:13  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.10  2012/02/14 12:52:45  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.9  2011/09/28 13:16:12  danalt
	JobResponsible size is now 64
	
	Revision 2.8  2011/03/02 18:47:13  marpas
	serial 8 support
	
	Revision 2.7  2011/01/20 10:37:12  marpas
	debug improved
	
	Revision 2.6  2010/12/20 18:45:27  marpas
	improving debug
	
	Revision 2.5  2010/03/05 15:09:10  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.4  2009/09/29 15:30:42  marpas
	useless include removed
	
	Revision 2.3  2009/02/19 13:35:37  chicas
	string lenght check removed
	
	Revision 2.2  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.1  2008/07/14 13:15:15  marpas
	statistics improved
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.38  2005/06/15 07:44:49  integrator
	multiple storage manager implemented
	
	Revision 1.37  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.36  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.35  2004/10/04 15:13:52  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.34  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.33  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.32  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.31  2004/04/21 14:46:29  paoscu
	Bug fixed.
	
	Revision 1.30  2004/04/19 13:38:43  paoscu
	Field "format" added.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbDistribution.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbDistribution)

// constructor
dbDistribution::dbDistribution() :
	dbPersistent(),
	_packageIdSet(),
	_status() ,
	_statusSet() ,
	_distributedDate() ,
	_distributedDateSet() ,
	_jobResponsible() ,
	_jobResponsibleSet() ,
	_creationDate() ,
	_creationDateSet() ,
	_format() ,
	_formatSet()

{
}


// copy constructor
dbDistribution::dbDistribution(const dbDistribution &o):
	dbPersistent(o),
	_packageIdSet(o._packageIdSet),
	_status(o._status) ,
	_statusSet(o._statusSet) ,
	_distributedDate(o._distributedDate) ,
	_distributedDateSet(o._distributedDateSet) ,
	_jobResponsible(o._jobResponsible) ,
	_jobResponsibleSet(o._jobResponsibleSet) ,
	_creationDate(o._creationDate) ,
	_creationDateSet(o._creationDateSet) ,
	_format(o._format) ,
	_formatSet(o._formatSet)
{
}


dbDistribution::~dbDistribution() throw()
{
}


// operator =
dbDistribution &dbDistribution::operator=(const dbDistribution &o)
{
	Lock guard(*this); // PRQA S 3050  2
	Lock lo(o);

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_packageIdSet=o._packageIdSet;
		_status=o._status;
		_statusSet=o._statusSet;
		_distributedDate=o._distributedDate;
		_distributedDateSet=o._distributedDateSet;
		_jobResponsible=o._jobResponsible;
		_jobResponsibleSet=o._jobResponsibleSet;
		_creationDate=o._creationDate;
		_creationDateSet=o._creationDateSet;
		_format=o._format;
		_formatSet=o._formatSet;
	}
	return *this ;
}


dbPersistent *dbDistribution::clone() const
{
	Lock guard(*this); // PRQA S 3050

	return new dbDistribution(*this) ;
}


string dbDistribution::className() const
{
	return staticClassName() ;
}


string dbDistribution::staticClassName()
{
	return "dbDistribution" ;
}


// initialize the class
void dbDistribution::reset()
{
	Lock guard(*this); // PRQA S 3050

	// reset dbPersistent
	dbPersistent::reset() ;
	_packageIdSet = false ;
	_status="" ;
	_statusSet=false ;
	_distributedDate.reset() ;
	_distributedDateSet=false ;
	_jobResponsible="" ;
	_jobResponsibleSet=false ;
	_creationDate.reset() ;
	_creationDateSet=false ;
	_format=-1 ;
	_formatSet=false ;
}


// save the data in database
dbPersistent::IdType dbDistribution::save(dbConnection &conn) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	if (!isModified()) {
		return getId() ;
    } 

	if (isFromDatabase()) 
	{
		ACS_THROW(InvalidUse("Use the method update() instead of save().")) ; // PRQA S 3081
	}

	if(!_statusSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Status\" must be set.")) ; // PRQA S 3081
	}


    db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistribution_SAVE") ;
	conn.addStateWrapper(*this) ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "INSERT INTO T_DistributionQueue (" ;
		queryString += "Status" ;
		if(_distributedDateSet) {
			queryString += ", DistributedDate" ;
        }
		if(_jobResponsibleSet) {
			queryString += ", JobResponsible" ;
        }
		if(_creationDateSet) {
			queryString += ", CreationDate" ;
        }
		if(_formatSet) 
		{
			queryString += ", Format" ;
		}
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey,_status) ;
		if(_distributedDateSet) {
			queryString +=	", " + db::toSQL(dbKey,_distributedDate,dbConv::YearToFraction) ;
        }
		if(_jobResponsibleSet) {
			queryString +=	", " + db::toSQL(dbKey,_jobResponsible) ;
        }
		if(_creationDateSet) {
			queryString +=	", " + db::toSQL(dbKey,_creationDate,dbConv::YearToFraction) ;
        }
		if(_formatSet) 
		{
			queryString +=	", " + db::toSQL(dbKey,_format) ;
		}
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString,"SaveDistributionQueue") ;
	if (!query.execForStatus())
	{
			ACS_THROW(dbQuery::QueryExecuteException("Query Execution error: Command : " // PRQA S 3081
			    + queryString + " Error : " + query.errorString())) ;
	}

    // obtain the last serial just inserted
    setId(getLastSerial(conn, "T_DistributionQueue")) ;
    transaction.commit() ;

	// record that the values come from the database
	setFromDatabase() ; 
	return getId() ;
}


// load the class from the database. Return true if object exist
bool dbDistribution::load(dbConnection &conn , IdType id) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	IdType Id=id;

	if(Id == 0) {
		Id=getId() ;
    }
	if(Id==0)
	{
		ACS_THROW(IdNotProvided("Id not set")) ; // PRQA S 3081
	}

	dbDistribution tempRecord(*this); //store current record.


	reset() ; 


    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "SELECT " ;
		queryString +=	privateGetFields() ;
		queryString += " FROM T_DistributionQueue" ;
		queryString += " WHERE PackageId = " ;
		queryString +=	db::toSQL(dbKey,Id) ;
		string getOrderByString(privateGetOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos) {
				queryString += getOrderByString ;
            }
			else {
				queryString += " ORDER BY " + getOrderByString ;
            }
		}
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;
	dbQuery query(conn, sqlString,"LoadDistributionQueue") ;

	dbRow row(conn.getKey()) ;
	dbSet setQ;
	query.execForSet(setQ) ;
    if (setQ.size() > 1) // it should not occur
    {
        ACS_THROW(exIllegalValueException("Unexpected query result dimension: it should return just one row"));
    }
    else
    {
		if ( not setQ.getNextRow(row) )
        {
			*this = tempRecord;  //Nothing found: restore previuos situation.
			return false ;
        }
	}

	privateLoadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbDistribution::update(dbConnection &conn) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	if (0 == getId())
	{
		ACS_THROW(ObjectNotLoaded("Use the method save() instead.")) ;  // PRQA S 3081
	}

	if (!isFromDatabase())
	{
		ACS_THROW(ObjectNotLoaded("Use the method save() instead of update().")) ;  // PRQA S 3081
	}

	if (!isModified()) {
		return 0 ; 
    }

	if(!_statusSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Status\" must be set.")) ;// PRQA S 3081
	}

    db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistribution_UPDATE") ;

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "UPDATE T_DistributionQueue SET " ; 
		queryString += "Status= " + db::toSQL(dbKey,_status) ;
		if(_distributedDateSet) {
			queryString += ", DistributedDate= " + db::toSQL(dbKey,_distributedDate,dbConv::YearToFraction) ;
        }
		else {
			queryString += ", DistributedDate=  NULL " ; 
        }
		if(_jobResponsibleSet) {
			queryString += ", JobResponsible= " + db::toSQL(dbKey,_jobResponsible) ;
        }
		else {
			queryString += ", JobResponsible=  NULL " ; 
        }
		if(_creationDateSet) {
			queryString += ", CreationDate= " + db::toSQL(dbKey,_creationDate,dbConv::YearToFraction) ;
        }
		else {
			queryString += ", CreationDate=  NULL " ; 
        }
 		if(_formatSet) 
 		{
			queryString += ", Format= " + db::toSQL(dbKey,_format) ;
		}
		queryString += " WHERE " ;
		queryString += "PackageId = " + db::toSQL(dbKey,getId()) ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString,"UpdateDistributionQueue") ;

	query.execForStatus() ;
	transaction.commit() ;

	resetModifiedFlag() ;
	return getId() ;

}


// remove the class from the database
dbPersistent::IdType dbDistribution::remove(dbConnection &conn)
{
	Lock guard(*this); // PRQA S 3050

	if (0 == getId())
	{
		ACS_THROW(IdNotProvided("Id not set")) ; // PRQA S 3081
	}

    db::Transaction transaction(conn) ;
	transaction.begin_work("dbDistribution_REMOVE") ;

    const string &dbKey = conn.getKey() ;

	string queryString ;

	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "DELETE FROM T_DistributionQueue" ;
		queryString += " WHERE " ;
		queryString += "PackageId = " + db::toSQL(dbKey,getId()) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "RemoveDistributionQueue") ;

	query.execForStatus() ;

    transaction.commit() ;

	resetFromDatabase() ;
	setModifiedFlag() ;

	return getId() ;
}


// True if the class have valid parameters, false otherwise
bool dbDistribution::validate() const
{
	Lock guard(*this); // PRQA S 3050

	return true;
}


// export the class to stream
void dbDistribution::exportObj(rsResourceSet &s) const
{
	Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbDistribution") ;
	dbPersistent::exportObj(s) ;

	if(_packageIdSet) {
		s.setValue("_packageId", getId()) ;
    }
	s.setValue("_packageIdSet",_packageIdSet) ;

	if(_statusSet) {
		s.setValue("_status",_status) ;
    }
	s.setValue("_statusSet",_statusSet) ;

	if(_distributedDateSet)
	{
		rsPushNSpace rpns2(s,"_distributedDate") ;
		_distributedDate.exportObj(s) ;
	}
	s.setValue("_distributedDateSet",_distributedDateSet) ;

	if(_jobResponsibleSet) {
		s.setValue("_jobResponsible",_jobResponsible) ;
    }
	s.setValue("_jobResponsibleSet",_jobResponsibleSet) ;

	if(_creationDateSet)
	{
		rsPushNSpace rpns4(s,"_creationDate") ;
		_creationDate.exportObj(s) ;
	}
	s.setValue("_creationDateSet",_creationDateSet) ;

	if(_formatSet) {
		s.setValue("_format",_format) ;
    }
	s.setValue("_formatSet",_formatSet) ;

}


// import the class from a stream
void dbDistribution::importObj(rsResourceSet &s)
{
	Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbDistribution") ;
	dbPersistent::importObj(s) ;
	reset() ;
	s.getValue("_packageIdSet",_packageIdSet) ;
	if(_packageIdSet)
	{
		IdType id = 0 ;
		s.getValue("_packageId", id) ;
		setId(id) ;
	}

	s.getValue("_statusSet",_statusSet) ;
	if(_statusSet) {
		s.getValue("_status",_status) ;
    }

	s.getValue("_distributedDateSet",_distributedDateSet) ;
	if(_distributedDateSet)
	{
		rsPushNSpace rpns2(s,"_distributedDate") ;
		_distributedDate.importObj(s) ;
	}

	s.getValue("_jobResponsibleSet",_jobResponsibleSet) ;
	if(_jobResponsibleSet) {
		s.getValue("_jobResponsible",_jobResponsible) ;
    }

	s.getValue("_creationDateSet",_creationDateSet) ;
	if(_creationDateSet)
	{
		rsPushNSpace rpns4(s,"_creationDate") ;
		_creationDate.importObj(s) ;
	}

	s.getValue("_formatSet",_formatSet) ;
	if(_formatSet) {
		s.getValue("_format",_format) ;
    }

}


// export the class to XML stream
void dbDistribution::exportXML(XMLOstream &xst) const
{
	Lock guard(*this); // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbDistribution");
	dbPersistent::exportXML(xst) ;
    string null = "<null>" ;
	if(_packageIdSet)
	{
		ostringstream os;
		os << getId();
		XMLOstream::Tag txml0(xst, "_packageId", os.str(), "label=\"Package Id\"");
	}
	else
	{
		XMLOstream::Tag txml0(xst, "_packageId", null, "label=\"Package Id\"");
	}
	{
		XMLOstream::Tag txml0Set(xst, "_packageIdSet", (_packageIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_statusSet)
	{
		XMLOstream::Tag txml1(xst, "_status", _status, "label=\"Status\"");
	}
	else
	{
		XMLOstream::Tag txml1(xst, "_status", null, "label=\"Status\"");
	}
	{
		XMLOstream::Tag txml1Set(xst, "_statusSet", (_statusSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_distributedDateSet)
	{
		XMLOstream::Tag txml2(xst, "_distributedDate", "", "label=\"Distributed Date\"");
		_distributedDate.exportXML(xst) ;
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_distributedDate", null, "label=\"Distributed Date\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_distributedDateSet", (_distributedDateSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_jobResponsibleSet)
	{
		XMLOstream::Tag txml3(xst, "_jobResponsible", _jobResponsible, "label=\"Job Responsible\"");
	}
	else
	{
		XMLOstream::Tag txml3(xst, "_jobResponsible", null, "label=\"Job Responsible\"");
	}
	{
		XMLOstream::Tag txml3Set(xst, "_jobResponsibleSet", (_jobResponsibleSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_creationDateSet)
	{
		XMLOstream::Tag txml4(xst, "_creationDate", "", "label=\"Creation Date\"");
		_creationDate.exportXML(xst) ;
	}
	else
	{
		XMLOstream::Tag txml4(xst, "_creationDate", null, "label=\"Creation Date\"");
	}
	{
		XMLOstream::Tag txml4Set(xst, "_creationDateSet", (_creationDateSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_formatSet)
	{		
		ostringstream os;
		os << _format;
		XMLOstream::Tag txml5(xst, "_format", os.str(), "label=\"Format\"");
	}
	else
	{
		XMLOstream::Tag txml5(xst, "_format", null, "label=\"Format\"");
	}
	{
		XMLOstream::Tag txml5Set(xst, "_formatSet", (_formatSet ? "true" : "false")) ; // PRQA S 3380
	}

}




// load the object from a row
int dbDistribution::loadRow(const dbRow &row, int offset)
{
	Lock guard(*this); // PRQA S 3050

	return privateLoadRow(row, offset) ;

}


// load the object from a row
int dbDistribution::privateLoadRow(const dbRow &row, int offset)
{
	Lock guard(*this); // PRQA S 3050

	IdType id = 0;

	row.columnSet(offset + 0, id , _packageIdSet ) ; // PRQA S 3000, 3010

	setId(id) ;

	row.columnSet(offset + 1, _status, _statusSet) ; // PRQA S 3000, 3010 4
	row.columnSet(offset + 2, _distributedDate, _distributedDateSet) ; // PRQA S 4400 3
	row.columnSet(offset + 3, _jobResponsible, _jobResponsibleSet) ;
	row.columnSet(offset + 4, _creationDate, _creationDateSet) ;
	ACS_CLASS_BGN_DEBUG(ACS_MID_VERB)
		ostringstream os ; 
		os << id << " " ;
		
		try {
			if (_distributedDateSet ) { _distributedDate.sortableDateTimeString(os) << " " ; }
			if (_creationDateSet ) { _creationDate.sortableDateTimeString(os) ; }
		}
		catch(exception &x) {
			ACS_LOG_NOTIFY_EX(x) ;
		}
		ACS_CLASS_WRITE_DEBUG(ACS_MID_VERB, os.str()) ;
	ACS_CLASS_END_DEBUG
	row.columnSet(offset + 5, _format, _formatSet) ;// PRQA S 3000, 3010, 4400


	setFromDatabase() ;

	return offset + 6 ; // PRQA S 4400
}


string dbDistribution::getWhere()
{
	string res ;
	return res ;
}


string dbDistribution::getIdName()
{
	return "T_DistributionQueue.PackageId" ;
}




void dbDistribution::setPackageId(IdType v)
{
	Lock guard(*this); // PRQA S 3050

	if (getId() != v ) 
	{
		setId(v) ;
		setModifiedFlag() ;
	}
}


dbPersistent::IdType dbDistribution::getPackageId() const
{
	Lock guard(*this); // PRQA S 3050

	return getId() ;
}


void dbDistribution::setStatus(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")) ; // PRQA S 3081
	}

	_status = v ;
	_statusSet = true ;
	setModifiedFlag() ;
}


const string &dbDistribution::getStatus(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _statusSet ; }
	return _status ;
}


void dbDistribution::unsetStatus()
{
	Lock guard(*this); // PRQA S 3050
	if(_statusSet == true) {
		setModifiedFlag();
    }
	_statusSet = false;

}
void dbDistribution::setDistributedDate(const DateTime &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_distributedDateSet || (_distributedDate != v ) )
	{
		_distributedDate = v ;
		_distributedDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistribution::getDistributedDate(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _distributedDateSet ; }
	return _distributedDate ;
}


void dbDistribution::unsetDistributedDate()
{
	Lock guard(*this); // PRQA S 3050
	if(_distributedDateSet == true) {
		setModifiedFlag();
    }
	_distributedDateSet = false;

}
void dbDistribution::setJobResponsible(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 64) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")) ; // PRQA S 3081
	}

	if (!_jobResponsibleSet || (_jobResponsible != v ) )
	{
		_jobResponsible = v ;
		_jobResponsibleSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbDistribution::getJobResponsible(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _jobResponsibleSet ; }
	return _jobResponsible ;
}


void dbDistribution::unsetJobResponsible()
{
	Lock guard(*this); // PRQA S 3050
	if(_jobResponsibleSet == true) {
		setModifiedFlag();
    }
	_jobResponsibleSet = false;

}
void dbDistribution::setCreationDate(const DateTime &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_creationDateSet || (_creationDate != v ) )
	{
		_creationDate = v ;
		_creationDateSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbDistribution::getCreationDate(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _creationDateSet ; }
	return _creationDate ;
}


void dbDistribution::unsetCreationDate()
{
	Lock guard(*this); // PRQA S 3050
	if(_creationDateSet == true) {
		setModifiedFlag();
    }
	_creationDateSet = false;

}

void dbDistribution::setFormat(const int &v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_formatSet || (_format != v ) )
	{
		_format = v ;
		_formatSet = true ;
		setModifiedFlag() ;
	}
}

const int &dbDistribution::getFormat(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _formatSet ; }
	return _format ;
}


void dbDistribution::unsetFormat()
{
	Lock guard(*this); // PRQA S 3050
	if(_formatSet == true) {
		setModifiedFlag();
    }
	_formatSet = false;

}
// get the field names
string dbDistribution::getFields()
{
	string s ;
	s += privateGetFields() ;
	return s ;
}


// get the field names
string dbDistribution::privateGetFields()
{
	string s ;
	s += "T_DistributionQueue.PackageId, ";
	s += "T_DistributionQueue.Status, ";
	s += "T_DistributionQueue.DistributedDate, ";
	s += "T_DistributionQueue.JobResponsible, ";
	s += "T_DistributionQueue.CreationDate, ";
	s += "T_DistributionQueue.Format" ;
	return s ;
}


// get the table name
string dbDistribution::getTable()
{
	return "T_DistributionQueue" ;
}


// get the order by clause
string dbDistribution::getOrderBy()
{
	string res ;
	res += privateGetOrderBy() ;
	return res ;
}


// get the order by clause
string dbDistribution::privateGetOrderBy()
{
	string res ;
	return res ;
}


void dbDistribution::writeTo(ostream &o) const
{
	Lock guard(*this); // PRQA S 3050
    string null = "<null>" ;
	string tmp ; 
	ostringstream f ; if (_formatSet) { f << _format ; }
    const string dbKey = "" ;
	o
		 << "_packageId = " << (_packageIdSet ?  db::toSQL(dbKey,getId()) : null) << "\n"  // PRQA S 3380 6 
		 << "_status = " << (_statusSet ? _status : null) << "\n" 
		 << "_distributedDate = " << (_distributedDateSet ? _distributedDate.utcs(tmp) : null) << "\n" 
		 << "_jobResponsible = " << (_jobResponsibleSet ? _jobResponsible : null) << "\n" 
		 << "_creationDate = " << (_creationDateSet ? _creationDate.utcs(tmp) : null) << "\n" 
		 << "_format = " << (_formatSet ? f.str() : null) << "\n"  ;
}


void dbDistribution::writeTo(exostream &o) const
{
	Lock guard(*this); // PRQA S 3050
    string null = "<null>" ;
	string tmp ; 
	ostringstream f ; if (_formatSet) { f << _format ; }
    const string dbKey = "" ;
	o
		 << "_packageId = " << (_packageIdSet ?  db::toSQL(dbKey,getId()) : null) << "\n"   // PRQA S 3380 6
		 << "_status = " << (_statusSet ? _status : null) << "\n" 
		 << "_distributedDate = " << (_distributedDateSet ? _distributedDate.utcs(tmp) : null) << "\n" 
		 << "_jobResponsible = " << (_jobResponsibleSet ? _jobResponsible : null) << "\n" 
		 << "_creationDate = " << (_creationDateSet ? _creationDate.utcs(tmp) : null) << "\n" 
		 << "_format = " << (_formatSet ? f.str() : null) << "\n"  ;
}


_ACS_END_NAMESPACE
