/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.2  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:59  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:27  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.6  2013/03/29 19:51:29  marpas
	removing html related functions
	
	Revision 2.5  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.3  2012/02/14 12:52:48  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.2  2008/11/17 11:46:09  marpas
	useless comments removed
	
	Revision 2.1  2008/10/20 13:40:27  marpas
	dbInventorySite classes added
	
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbInventorySite.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbConnectionPool.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <XMLOstream.h>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbInventorySite)

// constructor
dbInventorySite::dbInventorySite(dbConnection &c) : dbSmartPersistent("t_invsiterelation",c)
{
}


// copy constructor
dbInventorySite::dbInventorySite(const dbInventorySite &o):
	dbSmartPersistent(o)
{
}


dbInventorySite::~dbInventorySite() throw()
{
}



dbPersistent *dbInventorySite::clone() const
{
	return new dbInventorySite(*this) ;
}


// operator =
dbInventorySite &dbInventorySite::operator=(const dbInventorySite &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


string dbInventorySite::className() const
{
	return staticClassName() ;
}


string dbInventorySite::staticClassName()
{
	return "dbInventorySite" ;
}

// export the class to stream
void dbInventorySite::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbInventorySite") ;
	dbPersistent::exportObj(s) ;
    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ;
    bool null ;
	if(isSet("filename"))
	{
		s.setValue("_filename",getFileName(null, c)) ;
	}
	s.setValue("_filenameSet",isSet("filename")) ;

	if(isSet("fileversion"))
	{
		s.setValue("_fileversion",getFileVersion(null, c)) ;
	}
	s.setValue("_fileversionSet",isSet("fileversion")) ;


}





// import the class from a stream
void dbInventorySite::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ;
	rsPushNSpace nsp(s,"dbInventorySite") ;
	dbSmartPersistent::importObj(s) ;
	bool is ;
	s.getValue("_filenameSet",is) ;
	if(is)
	{
		string v ;
		s.getValue("_filename",v) ;
		setFileName(v,c) ;
	}
	else
		unsetFileName() ;
		
	s.getValue("_fileversionSet",is) ;
	if(is)
	{
		string v ;
		s.getValue("_fileversion",v) ;
		setFileVersion(v,c) ;
	}
	else
		unsetFileVersion() ;
		
}




// export the class to XML stream
void dbInventorySite::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbInventorySite");
	dbSmartPersistent::exportXML(xst) ;
    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ;
    bool null ;
	if(isSet("filename"))
	{
		XMLOstream::Tag txml(xst, "_fileName", getFileName(null,c), "label=\"File Name\"");
	}
	else
	{
		XMLOstream::Tag txml(xst, "_fileName", string("<null>"), "label=\"File Name\"");
	}
	{
		XMLOstream::Tag txml(xst, "_fileNameSet", (isSet("filename") ? "true" : "false")) ;
	}
	
	
	if(isSet("fileversion"))
	{
		XMLOstream::Tag txml(xst, "_fileVersion", getFileVersion(null,c), "label=\"File Version\"");
	}
	else
	{
		XMLOstream::Tag txml(xst, "_fileVersion", string("<null>"), "label=\"File Version\"");
	}
	{
		XMLOstream::Tag txml(xst, "_fileVersionSet", (isSet("fileversion") ? "true" : "false")) ;
	}
}






void dbInventorySite::setFileName(const string &v, dbConnection &c)
{
	set<string>("filename",v,c) ;
}


string dbInventorySite::getFileName(bool &null, dbConnection &c) const
{
	string v ; 
	
	get<string>("filename",v, null, c) ;

	return v ;
}


void dbInventorySite::unsetFileName()
{
	unset("filename") ;
}

void dbInventorySite::setFileVersion(const string &v, dbConnection &c)
{
	set<string>("fileversion",v,c) ;
}


string dbInventorySite::getFileVersion(bool &null, dbConnection &c) const
{
	string v ; 
	
	get<string>("fileversion",v, null, c) ;

	return v ;
}


void dbInventorySite::unsetFileVersion()
{
	unset("fileversion") ;
}

void dbInventorySite::setSiteId(int v, dbConnection &c)
{
	set<int>("site",v,c) ;
}


int dbInventorySite::getSiteId(bool &null, dbConnection &c) const
{
	int v = 0 ; 
	
	get<int>("site",v, null, c) ;

	return v ;
}


void dbInventorySite::unsetSiteId()
{
	unset("site") ;
}




// get the field names
string dbInventorySite::getFields()
{
	string s ;
	s += getTable() + "." + "Id, ";
	s += getTable() + "." + "FileName, ";
	s += getTable() + "." + "FileVersion, ";
	s += getTable() + "." + "Site ";
	return s ;
}


// get the table name
string dbInventorySite::getTable()
{
	return "T_invsiterelation" ;
}


_ACS_END_NAMESPACE
