// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:57  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:25  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.9  2013/03/29 19:51:29  marpas
	removing html related functions
	
	Revision 2.8  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.6  2012/02/14 12:52:47  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.5  2008/11/17 11:46:09  marpas
	useless comments removed
	
	Revision 2.4  2007/03/14 17:45:39  marpas
	work in progress
	
	Revision 2.3  2007/03/13 14:19:00  marpas
	work in progress
	
	Revision 2.2  2007/03/13 13:56:27  marpas
	work in progress
	
	Revision 2.1  2007/03/12 18:08:10  marpas
	work in progress
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbInventoryMDS.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbConnectionPool.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <XMLOstream.h>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbInventoryMDS)

// constructor
dbInventoryMDS::dbInventoryMDS(dbConnection &conn) : dbSmartPersistent("t_inventorydataset", conn)
{
}


// copy constructor
dbInventoryMDS::dbInventoryMDS(const dbInventoryMDS &o):
	dbSmartPersistent(o)
{
}


dbInventoryMDS::~dbInventoryMDS() throw()
{
}



dbPersistent *dbInventoryMDS::clone() const
{
	return new dbInventoryMDS(*this) ;
}


// operator =
dbInventoryMDS &dbInventoryMDS::operator=(const dbInventoryMDS &o)
{
	Lock lock(*this) ; // PRQA S 3050 2
	Lock lo() ;

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


string dbInventoryMDS::className() const
{
	return staticClassName() ;
}


string dbInventoryMDS::staticClassName()
{
	return "dbInventoryMDS" ;
}

// export the class to stream
void dbInventoryMDS::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbInventoryMDS") ;
	dbPersistent::exportObj(s) ;
    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ; // PRQA S 3050
    bool null = false ;
	if(isSet("filename"))
	{
		s.setValue("_filename",getFileName(null, c)) ;
	}
	s.setValue("_filenameSet",isSet("filename")) ;

	if(isSet("fileversion"))
	{
		s.setValue("_fileversion",getFileVersion(null, c)) ;
	}
	s.setValue("_fileversionSet",isSet("fileversion")) ;


}





// import the class from a stream
void dbInventoryMDS::importObj(rsResourceSet &s)
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbInventoryMDS") ;
	dbSmartPersistent::importObj(s) ;
    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ; // PRQA S 3050
	bool is = false ;
	s.getValue("_filenameSet",is) ;
	if(is)
	{
		string v ;
		s.getValue("_filename",v) ;
		setFileName(v, c) ;
	}
	else {
		unsetFileName() ;
    }
		
	s.getValue("_fileversionSet",is) ;
	if(is)
	{
		string v ;
		s.getValue("_fileversion",v) ;
		setFileVersion(v, c) ;
	}
	else {
		unsetFileVersion() ;
    }
		
}




// export the class to XML stream
void dbInventoryMDS::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ; // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbInventoryMDS");
	dbSmartPersistent::exportXML(xst) ;
    dbConnectionWrapper cw(db::ConnPools::instance()->getPool(getKey())) ;
    dbConnection &c=cw ; // PRQA S 3050
    bool null = false ;
	if(isSet("filename"))
	{
		XMLOstream::Tag tag(xst, "_fileName", getFileName(null, c), "label=\"File Name\"");
	}
	else
	{
		XMLOstream::Tag tag(xst, "_fileName", string("<null>"), "label=\"File Name\""); // PRQA S 3081
	}
	{
		XMLOstream::Tag tag(xst, "_fileNameSet", (isSet("filename") ? "true" : "false")) ; // PRQA S 3380
	}
	
	
	if(isSet("fileversion"))
	{
		XMLOstream::Tag tag(xst, "_fileVersion", getFileVersion(null, c), "label=\"File Version\"");
	}
	else
	{
		XMLOstream::Tag tag(xst, "_fileVersion", string("<null>"), "label=\"File Version\""); // PRQA S 3081
	}
	{
		XMLOstream::Tag tag(xst, "_fileVersionSet", (isSet("fileversion") ? "true" : "false")) ; // PRQA S 3380
	}
}


void dbInventoryMDS::setFileName(const string &v, dbConnection &c)
{
	set<string>("filename",v,c) ;
}


string dbInventoryMDS::getFileName(bool &null, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("filename",v, null, c) ;

	return v ;
}


void dbInventoryMDS::unsetFileName()
{
	unset("filename") ;
}

void dbInventoryMDS::setFileVersion(const string &v, dbConnection &c)
{
	set<string>("fileversion",v,c) ;
}


string dbInventoryMDS::getFileVersion(bool &null, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("fileversion",v, null, c) ;

	return v ;
}


void dbInventoryMDS::unsetFileVersion()
{
	unset("fileversion") ;
}

void dbInventoryMDS::setMeasDataSetId(int v, dbConnection &c)
{
	set<int>("measdatasetid",v,c) ;
}


int dbInventoryMDS::getMeasDataSetId(bool &null, dbConnection &c) const // PRQA S 4214
{
	int v = 0 ; 
	
	get<int>("measdatasetid",v, null, c) ;

	return v ;
}


void dbInventoryMDS::unsetMeasDataSetId()
{
	unset("measdatasetid") ;
}


void dbInventoryMDS::setCount(int v, dbConnection &c)
{
	set<int>("count",v,c) ;
}


int dbInventoryMDS::getCount(bool &null, dbConnection &c) const // PRQA S 4214
{
	int v = 0 ; 
	
	get<int>("count",v, null,c) ;

	return v ;
}


void dbInventoryMDS::unsetCount()
{
	unset("count") ;
}



// get the field names
string dbInventoryMDS::getFields()
{
	string s ;
	s += getTable() + "." + "FileName, ";
	s += getTable() + "." + "FileVersion, ";
	s += getTable() + "." + "MeasDataSetId, ";
	s += getTable() + "." + "Count ";
	return s ;
}


// get the table name
string dbInventoryMDS::getTable()
{
	return "T_InventoryDataSet" ;
}



_ACS_END_NAMESPACE
