// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/14 10:50:21  marpas
	coding best practices applicationin progress
	somw qa warnings removed
	
	Revision 5.3  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.2  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.1  2016/03/14 16:57:28  marpas
	honor dbGeneralQuery::offset(...)
	coding best practices applied
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:58  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:26  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.4  2013/02/20 17:09:18  marpas
	qa warnings
	
	Revision 2.3  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.1  2012/02/14 12:52:47  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.15  2004/08/30 17:51:13  paoscu
	doQuery abstract I/F changed
	
	Revision 1.14  2004/04/28 13:08:40  paoscu
	Incremental query support.
	
	Revision 1.13  2004/04/13 16:51:54  paoscu
	_queriedType added.
	Copy constructor and operator= added
	clone() method added.
	
	Revision 1.12  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbInventoryObjectQuery_H_
#define _dbInventoryObjectQuery_H_

#include <acs_c++config.hpp>
#include <dbGeneralQuery.h>
#include <exException.h>

_ACS_BEGIN_NAMESPACE(acs)


class dbCryosatFactory ;
class dbInventoryObject ;

//
//
//
// class dbInventoryObjectQuery
//
//
//
class dbInventoryObjectQuery : // PRQA S 2109
	public dbGeneralQuery
{
public:
	friend class dbCryosatFactory ; // PRQA S 2107
	typedef dbInventoryObject _queriedType ;
	
	dbInventoryObjectQuery(dbInventoryObjectQuery const &) ;
	dbInventoryObjectQuery &operator=(dbInventoryObjectQuery const &) ;
	
	virtual dbGeneralQueryIF *clone() const ; // PRQA S 2502
	
	static  std::string staticClassName() ;
	virtual ~dbInventoryObjectQuery() throw() ;

	virtual unsigned long doQuery(dbConnection &, bool incremental=false, bool enabled = true)  ; 

	virtual dbInventoryObject *operator[](unsigned long i) ; 
	virtual const dbInventoryObject *operator[](unsigned long i) const ; 

protected:
	explicit dbInventoryObjectQuery(const std::string &dbkey);
private:
    dbInventoryObjectQuery() ; // not implemented 
private:

	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbInventoryObjectQuery)
} ;

_ACS_END_NAMESPACE

#endif // _dbInventoryObjectQuery_H_
