// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/07/04 15:11:45  damdec
	CSGACQ-82: new getFields interface adopted.
	
	Revision 5.4  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.3  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.2  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.1  2016/03/14 16:57:28  marpas
	honor dbGeneralQuery::offset(...)
	coding best practices applied
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:59  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:27  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.2  2012/02/14 12:52:48  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.1  2008/09/17 15:45:17  crivig
	porting to postgres8
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.3  2006/01/04 16:11:18  enrcar
	Updated to DBEXPRESS
	
	Revision 1.2  2005/10/11 08:42:28  enrcar
	getParameters method used
	
	Revision 1.1  2005/06/20 10:36:11  marpas
	gaps management added
	
	Revision 1.11  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.10  2004/12/30 22:47:59  paoscu
	headers fixed
	
	Revision 1.9  2004/09/22 14:58:39  ivafam
	If in _orderByString clause "ORDER BY" is present do not add clause
	
	Revision 1.8  2004/09/22 13:20:07  ivafam
	Bug Fixed in do query: Now the SQLCLAUSE "ORDER BY" is added if _orderByString
	is not empty.
	
	Revision 1.7  2004/08/30 17:51:13  paoscu
	doQuery abstract I/F changed
	
	Revision 1.6  2004/04/28 13:08:40  paoscu
	Incremental query support.
	
	Revision 1.5  2004/04/13 16:52:56  paoscu
	Copy constructor and operator= added
	clone() method added.
	
	Revision 1.4  2003/10/21 13:05:24  paoscu
	staticClassName method added.
	
	Revision 1.3  2003/07/29 12:22:50  paoscu
	progReset() moved.
	
	Revision 1.2  2003/07/25 15:17:53  paoscu
	potential memroy leaks removed
	order by management improved
	
	Revision 1.1  2003/05/02 16:05:43  andcol
	imported
	
	Revision 1.9  2003/04/24 09:33:00  paoscu
	Library generated again to get rid of ends insertions
	
	Revision 1.8  2003/04/17 16:36:34  paoscu
	ostrstream turned into ostringstream.
	
	Revision 1.7  2003/02/03 13:31:16  danalt
	aligned with DB mandatory fields and lengths + loadRow + output null if not set
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbInventoryObjectWithGapsCommentsQuery.h>
#include <dbInventoryObjectWithGapsComments.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbSet.h>
#include <dbPersistentFactoryChain.h>
#include <sstream>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbInventoryObjectWithGapsCommentsQuery)


string dbInventoryObjectWithGapsCommentsQuery::staticClassName()
{
	return "dbInventoryObjectWithGapsCommentsQuery" ;
}


// constructor
dbInventoryObjectWithGapsCommentsQuery::dbInventoryObjectWithGapsCommentsQuery(const string &dbkey) :
    dbGeneralQuery(dbkey)
{
}


dbInventoryObjectWithGapsCommentsQuery::dbInventoryObjectWithGapsCommentsQuery(dbInventoryObjectWithGapsCommentsQuery const &other) :
    dbGeneralQuery(other.getKey())
{
	*this=other ;
}

dbInventoryObjectWithGapsCommentsQuery &dbInventoryObjectWithGapsCommentsQuery::operator=(dbInventoryObjectWithGapsCommentsQuery const &other)
{
	if(this != &other)
	{
		Lock lock1(*this) ; // PRQA S 3050 2
		Lock lock2(other) ;
		
		dbGeneralQuery::operator=(other) ;
	}
	
	return *this ;
}


dbGeneralQueryIF * dbInventoryObjectWithGapsCommentsQuery::clone() const
{
	return new dbInventoryObjectWithGapsCommentsQuery(*this) ;
}


dbInventoryObjectWithGapsCommentsQuery::~dbInventoryObjectWithGapsCommentsQuery() throw() {}



unsigned long dbInventoryObjectWithGapsCommentsQuery::doQuery(dbConnection &conn, bool incremental, bool enabled) // PRQA S 4020
{
	ACS_COND_THROW(incremental,InvalidUse("Incremental query not implemented.")) ; // PRQA S 3081
	

	clear() ; // erase previous result set
	if(!enabled) {
		return 0;
    }

    SQLString queryString = _sqlString ;
    queryString.setType( SQLString::SELECT );
    if (maxItems() > 0) {
		queryString.setLimit( maxItems() ) ; // PRQA S 3000
        if (offset() > 0) {
            queryString.setOffset( offset() ) ; // PRQA S 3000

        }
    }
	const string &dbKey=conn.getKey();
	deque<string> fields = dbInventoryObjectWithGapsComments::getFieldArray(conn);
	for (uint i = 0; i < fields.size(); ++i)
	{
    	queryString.addSelectList( fields[i] );
	}

    queryString.addTableList( dbInventoryObjectWithGapsComments::getTable() );

// where parameters and orderby have been copied from _sqlString above 

	ACS_CLASS_WRITE_DEBUG(ACS_LOW_VERB, "Query string is : \"" << queryString.getSQL()) ;
	dbQuery query(conn, queryString, "dbInventoryObjectWithGapsCommentsQuery::doQuery") ;

	dbRow row(conn.getKey()) ;
	dbSet set ;

	query.execForSet(set) ;

	for (size_t i=0; set.getNextRow(row); i++) // PRQA S 4238
	{
		ACS_CLASS_WRITE_DEBUG(ACS_LOW_VERB, "Added a new InventoryObject") ;
        
		// record = new dbInventoryObjectWithGapsComments ;
		ACS_SMARTPTR<dbInventoryObjectWithGapsComments> record(dynamic_cast<dbInventoryObjectWithGapsComments*>( dbPersistentFactoryChain::instance()->newObject("dbInventoryObjectWithGapsComments", conn.getKey()))) ; // PRQA S 3050, 3081
		record->loadRow(conn, row,0) ;
		_objects.push_back(record.release()) ;
	}

	return size() ;
}
dbInventoryObjectWithGapsComments *dbInventoryObjectWithGapsCommentsQuery::operator[](unsigned long i)
{
	return dynamic_cast<dbInventoryObjectWithGapsComments *>(item(i)) ; // PRQA S 3081
}

const dbInventoryObjectWithGapsComments *dbInventoryObjectWithGapsCommentsQuery::operator[](unsigned long i) const
{
	return dynamic_cast<const dbInventoryObjectWithGapsComments *>(item(i)) ; // PRQA S 3081
}

_ACS_END_NAMESPACE
