// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.6  2016/07/04 14:17:21  damdec
	CSGACQ-82: new dbInventoryObject::getFields interface used.
	
	Revision 5.5  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.4  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.3  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.2  2016/03/15 12:24:02  marpas
	offset bug fixed
	
	Revision 5.1  2016/03/14 16:57:28  marpas
	honor dbGeneralQuery::offset(...)
	coding best practices applied
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:58  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:26  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.8  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.6  2012/02/15 13:29:04  chicas
	passing connection to dbInventoryObject::getFields in doQuery
	
	Revision 2.5  2012/02/14 12:52:47  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.4  2009/10/08 13:11:53  marpas
	statistics improved
	
	Revision 2.3  2008/12/15 16:39:36  marpas
	incremental mode returns the number o data retrieved, regardless the total number of object in the query result
	
	Revision 2.2  2008/12/02 17:40:15  marpas
	incremental mode implemented
	
	Revision 2.1  2008/09/17 15:45:17  crivig
	porting to postgres8
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.25  2006/01/04 16:08:00  enrcar
	Updated to DBEXPRESS
	
	Revision 1.24  2005/10/11 08:42:28  enrcar
	getParameters method used
	
	Revision 1.23  2005/03/09 18:03:23  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.22  2004/09/22 14:58:39  ivafam
	If in _orderByString clause "ORDER BY" is present do not add clause
	
	Revision 1.21  2004/09/22 13:20:07  ivafam
	Bug Fixed in do query: Now the SQLCLAUSE "ORDER BY" is added if _orderByString
	is not empty.
	
	Revision 1.20  2004/08/30 17:51:13  paoscu
	doQuery abstract I/F changed
	
	Revision 1.19  2004/04/28 13:08:40  paoscu
	Incremental query support.
	
	Revision 1.18  2004/04/13 16:52:56  paoscu
	Copy constructor and operator= added
	clone() method added.
	
	Revision 1.17  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbInventoryObjectQuery.h>
#include <dbInventoryObject.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbSet.h>
#include <dbPersistentFactoryChain.h>
#include <sstream>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbInventoryObjectQuery)

string dbInventoryObjectQuery::staticClassName()
{
	return "dbInventoryObjectQuery" ;
}


// constructor
dbInventoryObjectQuery::dbInventoryObjectQuery(const string &dbkey) :
    dbGeneralQuery(dbkey) 
{
}


dbInventoryObjectQuery::dbInventoryObjectQuery(dbInventoryObjectQuery const &other) :
    dbGeneralQuery(other.getKey()) 
{
	*this=other ;
}

dbInventoryObjectQuery &dbInventoryObjectQuery::operator=(dbInventoryObjectQuery const &other)
{
	if(this != &other)
	{
		Lock lock1(*this) ; // PRQA S 3050 2
		Lock lock2(other) ;
		
		dbGeneralQuery::operator=(other) ;
	}
	
	return *this ;
}


dbGeneralQueryIF * dbInventoryObjectQuery::clone() const
{
	return new dbInventoryObjectQuery(*this) ;
}


dbInventoryObjectQuery::~dbInventoryObjectQuery() throw() {}


unsigned long dbInventoryObjectQuery::doQuery(dbConnection &conn, bool incremental, bool enabled) // PRQA S 4020
{
	if (!incremental) {
		clear() ; // erase previous result set
    }
	if(!enabled) {
		return 0;
    }

    SQLString queryString = _sqlString ;
    queryString.setType( SQLString::SELECT );

    if (maxItems() > 0) {
		queryString.setLimit( maxItems() ) ; // PRQA S 3000
        if (offset() >0) {
            queryString.setOffset( offset() ) ; // PRQA S 3000

        }
    }
	deque<string> fields = dbInventoryObject::getFieldArray(conn);
	for (uint i = 0; i < fields.size(); ++i)
	{
    	queryString.addSelectList( fields[i] );
	}
    queryString.addTableList( dbInventoryObject::getTable() );

// where parameters and orderby have been copied from _sqlString above 

	ACS_CLASS_WRITE_DEBUG(ACS_LOW_VERB, "Query string is : \"" << queryString.getSQL()) ;

	dbQuery query(conn, queryString, dbInventoryObject::getTable()+"_Select") ;

	dbRow row(conn.getKey()) ;
	dbSet set ;

	query.execForSet(set) ;

	vector<dbInventoryObject *> newObjects ;
	for (size_t i=0; set.getNextRow(row); i++) // PRQA S 4238 
	{
		ACS_CLASS_WRITE_DEBUG(ACS_LOW_VERB, "Added a new InventoryObject") ;
		// record = new dbInventoryObject ;
		ACS_SMARTPTR<dbInventoryObject> record(dynamic_cast<dbInventoryObject*>( dbPersistentFactoryChain::instance()->newObject("dbInventoryObject", conn.getKey()))) ; // PRQA S 3050, 3081
		record->loadRow(conn, row,0) ;

		if (!incremental) {
			_objects.push_back(record.release()) ;
        }
		else {
            size_t objsize = _objects.size() ;
			for (size_t ne=0; ne<objsize;++ne) {
				dbInventoryObject *oe = dynamic_cast<dbInventoryObject *>(_objects[ne]) ; // PRQA S 3081
				if (oe->getId() == record->getId()) {
					record.reset() ;
					break ;
				}
			}
			if (0 != record.get()) {
				newObjects.push_back(record.release()) ;
			}
		}
	}
	if (incremental) {
        size_t neosize = newObjects.size() ;
		for (size_t i=0; i < neosize; ++i) {
			_objects.insert(_objects.begin(),newObjects[i]) ;
        }
	}

	return size() ;
}
dbInventoryObject *dbInventoryObjectQuery::operator[](unsigned long i)
{
	return dynamic_cast<dbInventoryObject *>(item(i)) ; // PRQA S 3081
}

const dbInventoryObject *dbInventoryObjectQuery::operator[](unsigned long i) const
{
	return dynamic_cast<const dbInventoryObject *>(item(i)) ; // PRQA S 3081
}

_ACS_END_NAMESPACE 
