// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Exprivia SpA.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.exprivia.com

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Exprivia, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/27 08:33:15  damdec
	CSGACS-86: Compilation warnings fixed.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:13  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:25  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:30:56  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:24  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.8  2013/03/29 19:51:29  marpas
	removing html related functions
	
	Revision 2.7  2012/11/16 13:01:13  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.5  2012/06/15 09:54:29  marpas
	removing warning related to virtual method hiding
	
	Revision 2.4  2012/02/14 12:52:47  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.3  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.2  2010/05/07 16:28:45  marpas
	db independence chould be complete now
	
	Revision 2.1  2008/11/17 11:46:28  marpas
	column name changed (text into comment)
	
	Revision 2.0  2006/02/28 09:09:35  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.18  2005/06/17 10:31:54  marpas
	std namespaces took into consideration
	
	Revision 1.17  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.16  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.15  2004/04/13 16:57:08  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.14  2004/02/04 10:12:35  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbInventoryComment_H_
#define _dbInventoryComment_H_

#include <exException.h>
#include <dbPersistent.h>
#include <DateTime.h>

#include <string>

namespace acs {

class dbCryosatFactory ;

class dbRow ;
class rsResourceSet ;
class XMLOstream ;
class SQLString ;
//
//
//
// class dbInventoryComment
//
//
//
class dbInventoryComment :
	public dbPersistent
{
public:
	friend class dbCryosatFactory ;

	virtual ~dbInventoryComment() throw() ;
	dbInventoryComment &operator=(const dbInventoryComment &) ; // operator =

	static  std::string staticClassName() ;
	virtual dbPersistent *clone() const ;

	// inherited from dbPersistent
	virtual std::string className() const ;
	virtual void reset() ; // initialize the class
	virtual IdType save(dbConnection &)  ; // save the data in database
	virtual bool load(dbConnection & , IdType id=0)  ; // load the class from the database. Return true if obect exist
	virtual IdType update(dbConnection &)  ; // update an existing instance in database
	virtual IdType remove(dbConnection &)  ; // remove the class from the database
	virtual bool validate() const  ; // True if the class have valid parameters, false otherwise
	virtual void exportObj(rsResourceSet &s) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &s)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &xst) const ; // export the class to XML stream

	int loadRow(const dbRow &, int offset=0) ;

	void setComment(const std::string &) ;
	const std::string &getComment(bool *set=0) const ;
	void unsetComment();

	void setDate(const DateTime &) ;
	const DateTime &getDate(bool *set=0) const ;
	void unsetDate();

	void setAuthor(const std::string &) ;
	const std::string &getAuthor(bool *set=0) const ;
	void unsetAuthor();

	void setFileName(const std::string &) ;
	const std::string &getFileName(bool *set=0) const ;
	void unsetFileName();

	void setFileVersion(const std::string &) ;
	const std::string &getFileVersion(bool *set=0) const ;
	void unsetFileVersion();

	static std::string getFields(SQLString *select=0) ;
	static std::string getTable() ;
	static std::string getOrderBy(SQLString *select=0) ;

	// output to stream
	virtual void writeTo(std::ostream &) const ;
	virtual void writeTo(exostream &) const ;


protected:
	dbInventoryComment() ;
	dbInventoryComment(const dbInventoryComment &) ;


private:
	std::string _comment ;
	bool _commentSet ;

	DateTime _date ;
	bool _dateSet ;

	std::string _author ;
	bool _authorSet ;

	std::string _fileName ;
	bool _fileNameSet ;

	std::string _fileVersion ;
	bool _fileVersionSet ;

	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbInventoryComment)
	
} ;


} // namespace

#endif // _dbInventoryComment_H_
