// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/26 10:12:48  damdec
	CSGACQ-86: handling of Id_MediaType added.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.1  2014/05/26 11:39:44  marpas
	dbConv casted to avoid problem with new libXMLResources templates for tags
	
	Revision 4.0  2013/09/30 12:31:01  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:29  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.12  2013/04/12 12:14:38  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.11  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.10  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.9  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.6  2012/02/14 12:52:49  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.5  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.4  2010/03/05 15:09:11  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.3  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.2  2006/06/09 12:45:58  giucas
	Fixed syntax error in update query.
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.31  2005/06/15 07:44:50  integrator
	multiple storage manager implemented
	
	Revision 1.30  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.29  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.28  2004/10/04 15:13:53  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.27  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.26  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.25  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.24  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.23  2004/04/13 16:57:09  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.22  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbMediaType.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbSet.h>
#include <dbConv.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>



_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbMediaType)

// constructor
dbMediaType::dbMediaType() :
	dbPersistent(),
	_id_mediaType(),
	_id_mediaTypeSet(),
	_mediaType(),
	_mediaTypeSet(),
	_uncompressedCapacity(),
	_uncompressedCapacitySet()

{
}


// copy constructor
dbMediaType::dbMediaType(const dbMediaType &o):
	dbPersistent(o),
	_id_mediaType(o._id_mediaType),
	_id_mediaTypeSet(o._id_mediaTypeSet),
	_mediaType(o._mediaType),
	_mediaTypeSet(o._mediaTypeSet),
	_uncompressedCapacity(o._uncompressedCapacity),
	_uncompressedCapacitySet(o._uncompressedCapacitySet)
{
}


dbMediaType::~dbMediaType() throw()
{
}


dbPersistent *dbMediaType::clone() const
{
	return new dbMediaType(*this) ;
}


// operator =
dbMediaType &dbMediaType::operator=(const dbMediaType &o)
{
	Lock lock(*this) ; // PRQA S 3050 2
    Lock lo(o) ;
	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_id_mediaType=o._id_mediaType;
		_id_mediaTypeSet=o._id_mediaTypeSet;
		_mediaType=o._mediaType;
		_mediaTypeSet=o._mediaTypeSet;
		_uncompressedCapacity=o._uncompressedCapacity;
		_uncompressedCapacitySet=o._uncompressedCapacitySet;
	}
	return *this ;
}


string dbMediaType::className() const
{
	return staticClassName() ;
}


string dbMediaType::staticClassName()
{
	return "dbMediaType" ;
}



// initialize the class
void dbMediaType::reset()
{
	Lock lock(*this) ; // PRQA S 3050

	// reset dbPersistent
	dbPersistent::reset() ;
	_id_mediaType=0 ;
	_id_mediaTypeSet=false ;
	_mediaType="" ;
	_mediaTypeSet=false ;
	_uncompressedCapacity=0 ;
	_uncompressedCapacitySet=false ;
}


// save the data in database
dbPersistent::IdType dbMediaType::save(dbConnection &conn) // PRQA S 4020
{
	Lock lock(*this) ; // PRQA S 3050

	if (!isModified()) {
		return 0 ; 
    }

	if (isFromDatabase()) 
	{
		ACS_THROW(InvalidUse("Use the method update() instead of save().")) ; // PRQA S 3081
	}
	if(!_id_mediaTypeSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Id Media Type\" must be set.")) ; // PRQA S 3081
	}
	if(!_mediaTypeSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Media Type\" must be set.")) ; // PRQA S 3081
	}
	if(!_uncompressedCapacitySet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Uncompressed Capacity\" must be set.")) ; // PRQA S 3081
	}

	string queryString ;
    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "INSERT INTO " + getTable() + " (" ;
		queryString += "Id_MediaType" ;
		queryString += ", MediaType" ;
		queryString += ", UncompressedCapacity" ;
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey, _id_mediaType) ;
		queryString +=	", " + db::toSQL(dbKey, _mediaType) ;
		queryString +=	", " + db::toSQL(dbKey,_uncompressedCapacity) ;
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString ) ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbMediaType::save") ;

	if (!query.execForStatus())
	{
		ACS_THROW(dbQuery::QueryExecuteException("Query Execution error: Command : "  // PRQA S 3081
            + queryString + " Error : " + query.errorString())) ;
	}

	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbMediaType::load(dbConnection &conn , IdType id) // PRQA S 4020
{
	Lock lock(*this) ; // PRQA S 3050

	dbMediaType tempRecord(*this); //store current record.


	reset() ; 

	string queryString ;

    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	getFields() ;
		queryString += " FROM " + getTable() ;
		queryString += " WHERE Id_MediaType " ;
		if(tempRecord._mediaTypeSet) {
			queryString +=	"= " + db::toSQL(dbKey, tempRecord._id_mediaType) ;
        }
		else {
			queryString +=	" IS NULL" ;
        }
		string getOrderByString(getOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos) {
				queryString += getOrderByString ;
            }
			else {
				queryString += " ORDER BY " + getOrderByString ;
            }
		}
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;


	dbQuery query(conn, sqlString, "dbMediaType::load") ;
	dbRow row(conn.getKey()) ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	try
	{
        dbSet set ;
		query.execForSet(set) ;
        ACS_COND_THROW(set.empty(), dbQuery::QueryNoDataFound("empty set")) ; // PRQA S 3081 2
        ACS_COND_THROW(set.size() > 1, exIllegalValueException("Set size > 1")) ;
        set.getNextRow(row) ; // first and only 
	}
	catch (dbQuery::QueryNoDataFound &e)
	{
		*this = tempRecord;  //Nothing found: restore previuos situation.
		return false ;
	}

	loadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbMediaType::update(dbConnection &conn) // PRQA S 4020
{
	Lock lock(*this) ; // PRQA S 3050

	if (!isFromDatabase())
	{
		ACS_THROW(ObjectNotLoaded("Use the method save() instead of update().")) ;  // PRQA S 3081
	}

	if (!isModified()) {
		return 0 ; 
    }

	string queryString ;

    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "UPDATE " + getTable() + " SET " ; 
		queryString += "MediaType= " + db::toSQL(dbKey, _mediaType) ;
		queryString += ", UncompressedCapacity= " + db::toSQL(dbKey, _uncompressedCapacity) ;
		queryString += " WHERE " ;
		queryString += "Id_MediaType " ;
        queryString +=	"= " + db::toSQL(dbKey, _id_mediaType) ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbMediaType::update") ;

	query.execForStatus() ;


	resetModifiedFlag() ;
	return 0 ;

}


// remove the class from the database
dbPersistent::IdType dbMediaType::remove(dbConnection &conn)
{
	Lock lock(*this) ; // PRQA S 3050

	string queryString ;
    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "DELETE FROM " + getTable() ;
		queryString += " WHERE " ;
		queryString += "Id_MediaType " ;
		if(_id_mediaTypeSet)  {
			queryString +=	"= " + db::toSQL(dbKey, _id_mediaType) ;
        }
		else {
			queryString +=	"IS NULL" ;
        }

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn,sqlString,"dbMediaType::remove") ;

	query.execForStatus() ;

	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbMediaType::validate() const
{
	return true;
}


// export the class to stream
void dbMediaType::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbMediaType") ;
	dbPersistent::exportObj(s) ;
	if(_id_mediaTypeSet)
	{
		s.setValue("_id_mediaType",_id_mediaType) ;
	}
	s.setValue("_id_mediaTypeSet",_id_mediaTypeSet) ;
	if(_mediaTypeSet)
	{
		s.setValue("_mediaType",_mediaType) ;
	}
	s.setValue("_mediaTypeSet",_mediaTypeSet) ;
	if(_uncompressedCapacitySet)
	{
		s.setValue("_uncompressedCapacity",_uncompressedCapacity) ;
	}
	s.setValue("_uncompressedCapacitySet",_uncompressedCapacitySet) ;
}


// import the class from a stream
void dbMediaType::importObj(rsResourceSet &s)
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbMediaType") ;
	dbPersistent::importObj(s) ;
	s.getValue("_id_mediaTypeSet",_id_mediaTypeSet) ;
	if(_id_mediaTypeSet)
	{
		s.getValue("_id_mediaType",_id_mediaType) ;
	}
	else {
		_id_mediaType = 0 ;
    }
	s.getValue("_mediaTypeSet",_mediaTypeSet) ;
	if(_mediaTypeSet)
	{
		s.getValue("_mediaType",_mediaType) ;
	}
	else {
		_mediaType = "" ;
    }
	s.getValue("_uncompressedCapacitySet",_uncompressedCapacitySet) ;
	if(_uncompressedCapacitySet)
	{
		s.getValue("_uncompressedCapacity",_uncompressedCapacity) ;
	}
	else {
		_uncompressedCapacity = 0 ;
    }
}


// export the class to XML stream
void dbMediaType::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ; // PRQA S 3050
    string null = "<null>" ;
	XMLOstream::Tag txml(xst, "dbMediaType");
	dbPersistent::exportXML(xst) ;
	if(_id_mediaTypeSet)
	{
	    XMLOstream::Tag txml0(xst, "_id_mediaType", db::toSQL("",_id_mediaType), "label=\"Id Media Type\"");
	}
	else
	{
	    XMLOstream::Tag txml0(xst, "_id_mediaType", null, "label=\"Id Media Type\"");
	}
	{
	    XMLOstream::Tag txml0Set(xst, "_id_mediaTypeSet", (_id_mediaTypeSet ? "true" : "false")) ; // PRQA S 3380
	}
	if(_mediaTypeSet)
	{
	    XMLOstream::Tag txml0(xst, "_mediaType", _mediaType, "label=\"Media Type\"");
	}
	else
	{
	    XMLOstream::Tag txml0(xst, "_mediaType", null, "label=\"Media Type\"");
	}
	{
	    XMLOstream::Tag txml0Set(xst, "_mediaTypeSet", (_mediaTypeSet ? "true" : "false")) ; // PRQA S 3380
	}
	if(_uncompressedCapacitySet)
	{
	    XMLOstream::Tag txml1(xst, "_uncompressedCapacity", db::toSQL("",_uncompressedCapacity), "label=\"Uncompressed Capacity\"");
	}
	else
	{
	    XMLOstream::Tag txml1(xst, "_uncompressedCapacity", null, "label=\"Uncompressed Capacity\"");
	}
	{
	    XMLOstream::Tag txml1Set(xst, "_uncompressedCapacitySet", (_uncompressedCapacitySet ? "true" : "false")) ; // PRQA S 3380
	}
}


// load the object from a row
int dbMediaType::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ; // PRQA S 3050

	row.columnSet(offset + 0, _id_mediaType, _id_mediaTypeSet) ; // PRQA S 3000, 3010 2
	row.columnSet(offset + 1, _mediaType, _mediaTypeSet) ; // PRQA S 3000, 3010 2
	row.columnSet(offset + 2, _uncompressedCapacity, _uncompressedCapacitySet) ;


	setFromDatabase() ;

	return offset + 3 ; // PRQA S 4400
}


void dbMediaType::setIdMediaType(const int &v)
{
	Lock lock(*this) ; // PRQA S 3050

	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	if (!_id_mediaTypeSet || _id_mediaType != v ) 
	{
		_id_mediaType = v ;
		_id_mediaTypeSet = true ;
		setModifiedFlag() ;
	}
}


int dbMediaType::getIdMediaType(bool *set) const
{
	Lock lock(*this) ; // PRQA S 3050

	if (set) { *set = _id_mediaTypeSet ; }
	return _id_mediaType ;
}


void dbMediaType::unsetIdMediaType()
{
	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	Lock lock(*this) ; // PRQA S 3050
	if(_id_mediaTypeSet == true) {
		setModifiedFlag();
    }
	_id_mediaTypeSet = false;

}
void dbMediaType::setMediaType(const string &v)
{
	Lock lock(*this) ; // PRQA S 3050

	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	if (v.size() > 16) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")) ; // PRQA S 3081
	}

	if (!_mediaTypeSet || _mediaType != v ) 
	{
		_mediaType = v ;
		_mediaTypeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbMediaType::getMediaType(bool *set) const
{
	Lock lock(*this) ; // PRQA S 3050

	if (set) { *set = _mediaTypeSet ; }
	return _mediaType ;
}


void dbMediaType::unsetMediaType()
{
	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	Lock lock(*this) ; // PRQA S 3050
	if(_mediaTypeSet == true) {
		setModifiedFlag();
    }
	_mediaTypeSet = false;

}
void dbMediaType::setUncompressedCapacity(int v)
{
	Lock lock(*this) ; // PRQA S 3050

	if (!_uncompressedCapacitySet || (_uncompressedCapacity != v ) )
	{
		_uncompressedCapacity = v ;
		_uncompressedCapacitySet = true ;
		setModifiedFlag() ;
	}
}


int dbMediaType::getUncompressedCapacity(bool *set) const
{
	Lock lock(*this) ; // PRQA S 3050

	if (set) {
		*set = _uncompressedCapacitySet ;
    }
	return _uncompressedCapacity ;
}


void dbMediaType::unsetUncompressedCapacity()
{
	Lock lock(*this) ; // PRQA S 3050
	if(_uncompressedCapacitySet == true) {
		setModifiedFlag();
    }
	_uncompressedCapacitySet = false;

}
// get the field names
string dbMediaType::getFields()
{
	string s ;
	s += getTable() + "." + "Id_MediaType, ";
	s += getTable() + "." + "MediaType, ";
	s += getTable() + "." + "UncompressedCapacity" ;
	return s ;
}


// get the table name
string dbMediaType::getTable()
{
	return "T_MediaTypes" ;
}


// get the order by clause
string dbMediaType::getOrderBy()
{
	return "" ;
}


void dbMediaType::writeTo(ostream &o) const
{
	Lock lock(*this) ; //  PRQA S 3050
    string null = "<null>" ;
	o
		 << "_id_mediaType = " << (_id_mediaTypeSet ? db::toSQL("",_id_mediaType) : null) << "\n" // PRQA S 3380 2
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : null) << "\n" // PRQA S 3380 2
		 << "_uncompressedCapacity = " << (_uncompressedCapacitySet ? db::toSQL("", _uncompressedCapacity) : null) << "\n"  ; // PRQA S 3385
}


void dbMediaType::writeTo(exostream &o) const
{
	Lock lock(*this) ; //  PRQA S 3050
    string null = "<null>" ;
	o
		 << "_id_mediaType = " << (_id_mediaTypeSet ? db::toSQL("", _id_mediaType) : null) << "\n" // PRQA S 3380 2
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : null) << "\n" // PRQA S 3380 2
		 << "_uncompressedCapacity = " << (_uncompressedCapacitySet ? db::toSQL("", _uncompressedCapacity) : null) << "\n"  ; // PRQA S 3385
}


_ACS_END_NAMESPACE
