// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/26 10:18:55  damdec
	CSGACQ-86: handling of disseminationpackingalgo_id added.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.4  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.3  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.2  2015/06/09 13:07:36  marpas
	qa warning remotion in progress
	
	Revision 5.1  2015/06/09 10:26:23  marpas
	i/f deal with big serial 8
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:01  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:29  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.9  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.8  2013/02/12 12:38:53  marpas
	interfaces improved over qa rules
	
	Revision 2.7  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.4  2012/06/15 09:54:30  marpas
	removing warning related to virtual method hiding
	
	Revision 2.3  2012/02/14 12:52:49  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.2  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.1  2009/07/28 13:57:28  marpas
	mediatype field added
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.19  2005/06/17 10:31:55  marpas
	std namespaces took into consideration
	
	Revision 1.18  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.17  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.16  2004/04/19 13:48:33  paoscu
	Field "format" added.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbOnDemandDistribution_H_
#define _dbOnDemandDistribution_H_

#include <acs_c++config.hpp>
#include <exException.h>
#include <dbPersistent.h>

#include <string>


_ACS_BEGIN_NAMESPACE(acs)

class dbCryosatFactory ;

class dbRow ;
class rsResourceSet ;
class XMLOstream ;

//
//
//
// class dbOnDemandDistribution
//
//
//
class dbOnDemandDistribution : // PRQA S 2109
	public dbPersistent
{
	friend class dbCryosatFactory ; // PRQA S 2107
public:

	virtual ~dbOnDemandDistribution() throw() ;
	dbOnDemandDistribution &operator=(const dbOnDemandDistribution &) ; // operator =

	static  std::string staticClassName() ;

	// inherited from dbPersistent
	virtual dbPersistent* clone() const ;   // PRQA S 2502
	virtual std::string className() const ;
	virtual void reset() ; // initialize the class
	virtual IdType save(dbConnection &)  ; // save the data in database
	virtual bool load(dbConnection & , IdType id=0)  ; // load the class from the database. Return true if obect exist
	virtual IdType update(dbConnection &)  ; // update an existing instance in database
	virtual IdType remove(dbConnection &)  ; // remove the class from the database // PRQA S 2502
	virtual bool validate() const  ; // True if the class have valid parameters, false otherwise
	virtual void exportObj(rsResourceSet &s) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &s)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &xst) const ; // export the class to XML stream

	int loadRow(const dbRow &, int offset=0) ;

	static std::string getWhere() ;
	static std::string getIdName() ;

	void setOrderId(dbPersistent::IdType) ;
	dbPersistent::IdType getOrderId(bool *set=0) const ;
	void unsetOrderId();

	void setUserId(const std::string &) ;
	const std::string &getUserId(bool *set=0) const ;
	void unsetUserId();

	void setFormat(const std::string &) ;
	const std::string &getFormat(bool *set=0) const ;
	void unsetFormat();

	void setMediaType(const std::string &) ;
	const std::string &getMediaType(bool *set=0) const ;
	void unsetMediaType();

	void setDisseminationAlgo(const std::string &) ;
	const std::string &getDisseminationAlgo(bool *set=0) const ;
	void unsetDisseminationAlgo();
	
	static std::string getFields() ;
	static std::string getTable() ;
	static std::string getOrderBy() ;

	// output to stream
	virtual void writeTo(std::ostream &) const ;
	virtual void writeTo(exostream &) const ;


protected:
	dbOnDemandDistribution() ;
	dbOnDemandDistribution(const dbOnDemandDistribution &) ;


private:
	int privateLoadRow(const dbRow &, int offset=0) ;
	static std::string privateGetFields() ;
	static std::string privateGetOrderBy() ;


private:
	dbPersistent::IdType _orderId ;
	bool _orderIdSet ;

	std::string _userId ;
	bool _userIdSet ;

	std::string _format ;
	bool _formatSet ;

	std::string _mediaType ;
	bool _mediaTypeSet ;
	
	std::string  _disseminationAlgo;
	bool _disseminationAlgoSet ;


	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbOnDemandDistribution)
} ;

_ACS_END_NAMESPACE

#endif // _dbOnDemandDistribution_H_
