// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/26 10:18:55  damdec
	CSGACQ-86: handling of disseminationpackingalgo_id added.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.4  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.3  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.2  2015/06/09 13:07:36  marpas
	qa warning remotion in progress
	
	Revision 5.1  2015/06/09 10:26:23  marpas
	i/f deal with big serial 8
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:01  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:29  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.18  2013/04/30 13:31:42  marpas
	dbPersistent interface changed
	
	Revision 2.17  2013/04/17 17:37:24  marpas
	dbPersistent interface changed
	
	Revision 2.16  2013/04/12 12:14:39  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.15  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.14  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.13  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.10  2012/03/14 16:00:35  marpas
	minoorg changes for QT interfaces
	
	Revision 2.9  2012/02/14 12:52:49  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.8  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.7  2010/03/05 15:09:11  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.6  2009/10/08 13:11:53  marpas
	statistics improved
	
	Revision 2.5  2009/07/28 13:57:28  marpas
	mediatype field added
	
	Revision 2.4  2009/07/28 09:46:54  marfav
	Format max size allowed is now 16
	
	Revision 2.3  2009/07/23 12:43:54  marpas
	format can be null
	
	Revision 2.2  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.32  2005/06/15 07:44:50  integrator
	multiple storage manager implemented
	
	Revision 1.31  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.30  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.29  2004/10/04 15:13:53  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.28  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.27  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.26  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.25  2004/04/19 13:48:33  paoscu
	Field "format" added.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbOnDemandDistribution.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbOnDemandDistribution)

// constructor
dbOnDemandDistribution::dbOnDemandDistribution() :
	dbPersistent(),
	_orderId(),
	_orderIdSet(),
	_userId() ,
	_userIdSet() ,
	_format() ,
	_formatSet(),
	_mediaType() ,
	_mediaTypeSet(),
	_disseminationAlgo(),
	_disseminationAlgoSet(false)
{
}


// copy constructor
dbOnDemandDistribution::dbOnDemandDistribution(const dbOnDemandDistribution &o):
	dbPersistent(o),
	_orderId(o._orderId),
	_orderIdSet(o._orderIdSet),
	_userId(o._userId) ,
	_userIdSet(o._userIdSet) ,
	_format(o._format) ,
	_formatSet(o._formatSet),
	_mediaType(o._mediaType) ,
	_mediaTypeSet(o._mediaTypeSet),
	_disseminationAlgo(o._disseminationAlgo),
	_disseminationAlgoSet(o._disseminationAlgoSet)
{
}


dbOnDemandDistribution::~dbOnDemandDistribution() throw()
{
}


// operator =
dbOnDemandDistribution &dbOnDemandDistribution::operator=(const dbOnDemandDistribution &o)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050 2
	ThreadSafe::Lock lo(o);

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_orderId=o._orderId;
		_orderIdSet=o._orderIdSet;
		_userId=o._userId;
		_userIdSet=o._userIdSet;
		_format=o._format;
		_formatSet=o._formatSet;
		_mediaType=o._mediaType;
		_mediaTypeSet=o._mediaTypeSet;
		_disseminationAlgo = o._disseminationAlgo;
		_disseminationAlgoSet = o._disseminationAlgoSet;
	}
	return *this ;
}


dbPersistent *dbOnDemandDistribution::clone() const
{

	return new dbOnDemandDistribution(*this) ;
}


string dbOnDemandDistribution::className() const
{
	return staticClassName() ;
}


string dbOnDemandDistribution::staticClassName()
{
	return "dbOnDemandDistribution" ;
}


// initialize the class
void dbOnDemandDistribution::reset()
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050 

	// reset dbPersistent
	dbPersistent::reset() ;
	_userId="" ;
	_userIdSet=false ;
	_orderId=0 ;
	_orderIdSet=false ;
	_format="" ;
	_formatSet=false ;
	_mediaType="" ;
	_mediaTypeSet=false ;
	_disseminationAlgo = "";
	_disseminationAlgoSet = false;
}


// save the data in database
dbPersistent::IdType dbOnDemandDistribution::save(dbConnection &conn) // PRQA S 4020
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050 

	if (!isModified()) {
		return getId() ;
    } 

	if ((getId() != 0) || isFromDatabase()) 
	{
		ACS_THROW(InvalidUse("Use the method update() instead of save().")) ; // PRQA S 3081
	}

	if(!_userIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Id\" must be set.")) ; // PRQA S 3081
	}
	
	if(!_disseminationAlgoSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Disseminationpackingalgo_Id\" must be set.")) ;  // PRQA S 3081
	}


	// inside a transaction
	db::Transaction transaction(conn) ;
	transaction.begin_work("dbOnDemandDistribution_SAVE") ;

	conn.addStateWrapper(*this) ;


    const string &dbKey = conn.getKey() ;

	SQLString queryString( dbKey, SQLString::INSERT ) ;
	queryString.addTableList ( getTable() );
	queryString.addValuesList("orderid", db::toSQL(dbKey, _orderId) ) ;
	queryString.addValuesList("userid", db::toSQL(dbKey, _userId) ) ;
	
	if (_formatSet)
	{
		queryString.addValuesList("format", db::toSQL(dbKey, _format) ) ;
	}
	if (_mediaTypeSet)
	{
		queryString.addValuesList("mediatype", db::toSQL(dbKey, _mediaType) ) ;
	}
	if (_disseminationAlgoSet)
	{
		queryString.addValuesList("disseminationpackingalgo_id", db::toSQL(dbKey, _disseminationAlgo) ) ;
	}
	
	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString.getSQL()) ;
	dbQuery query(conn, queryString, "t_ondemanddistribution_Insert") ;


	if (!query.execForStatus())
	{
        ACS_THROW(dbQuery::QueryExecuteException("Query Execution error: Command : " // PRQA S 3081
			+ queryString.getSQL() + " Error : " + query.errorString())) ;
	}

    transaction.commit() ;

	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbOnDemandDistribution::load(dbConnection &conn , IdType id) // PRQA S 4020
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050


	dbOnDemandDistribution tempRecord(*this); //store current record.


	reset() ; 


    const string &dbKey = conn.getKey() ;

	SQLString sqlString ( dbKey, SQLString::SELECT ) ; 
	sqlString.addTableList(getTable()) ;
    sqlString.addSelectList( privateGetFields() );
	//add where
    {
    	dbQueryParameters pp(dbKey);
		if (tempRecord._orderIdSet)
		{
	    	pp.addParameter( dbParam(dbKey, getTable(), "OrderId", dbParam::EQUAL_TO, db::toSQL(dbKey, tempRecord._orderId))); // PRQA S 3050, 3081
    	}  
		else
		{
	    	pp.addParameter( dbParam(dbKey, getTable(), "OrderId", dbParam::ISNULL)); // PRQA S 3050, 3081

		}
    	sqlString.addANDWhereParameter(pp);
	}
    {
    	dbQueryParameters pp(dbKey);
		if (tempRecord._userIdSet)
		{
	    	pp.addParameter( dbParam(dbKey, getTable(), "UserId", dbParam::EQUAL_TO, db::toSQL(dbKey, tempRecord._userId))); // PRQA S 3050, 3081
    	}  
		else
		{
	    	pp.addParameter( dbParam(dbKey, getTable(), "UserId", dbParam::ISNULL)); // PRQA S 3050, 3081

		}
    	sqlString.addANDWhereParameter(pp);
	}

	sqlString.setOrderByString(privateGetOrderBy());
	dbQuery query(conn, sqlString,"t_ondemanddistribution_Load") ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << sqlString.getSQL()) ;
	dbSet set;
	query.execForSet(set) ;
	dbRow row(dbKey) ;
    if (set.size() > 1) // it should not occur
    {
        ACS_THROW(InvalidUse("Unexpected query result dimension: it should return just one row"));
    }
    else
    {
		if ( not set.getNextRow(row) )
        {
        	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "No " << getTable() << " record found ");
			*this = tempRecord;  //Nothing found: restore previuos situation.
			return false ;
        }
	}


	privateLoadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbOnDemandDistribution::update(dbConnection &conn) // PRQA S 4020
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (!isFromDatabase())
	{
		ACS_THROW(ObjectNotLoaded("Use the method save() instead of update().")) ;  // PRQA S 3081
	}

	if (!isModified()) {
		return 0 ; 
    }

	if(!_orderIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Order Id\" must be set.")) ;  // PRQA S 3081
	}
	if(!_userIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Id\" must be set.")) ;  // PRQA S 3081
	}
	if(!_formatSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Format\" must be set.")) ;  // PRQA S 3081
	}
	if(!_disseminationAlgoSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Disseminationpackingalgo_Id\" must be set.")) ;  // PRQA S 3081
	}

	// inside a transaction
	db::Transaction transaction(conn) ;
	transaction.begin_work("dbOnDemandDistribution_UPDATE") ;


    const string &dbKey = conn.getKey() ;
	SQLString sqlString ( dbKey, SQLString::UPDATE ) ;
	sqlString.addTableList(getTable()) ;
    if (_formatSet)
	{
		sqlString.addSetList( "format", db::toSQL( dbKey, _format ) );
	}
	else
	{
		sqlString.addSetList( "format", db::toSQL( dbKey, NULL ) );
	}
    if (_mediaTypeSet)
	{
		sqlString.addSetList( "mediatype", db::toSQL( dbKey, _mediaType ) );
	}
	else
	{
		sqlString.addSetList( "mediatype", db::toSQL( dbKey, NULL ) );
	}
    if (_disseminationAlgoSet)
	{
		sqlString.addSetList( "disseminationpackingalgo_id", db::toSQL( dbKey, _disseminationAlgo ) );
	}
	else
	{
		sqlString.addSetList( "disseminationpackingalgo_id", db::toSQL( dbKey, NULL ) );
	}
	// Add where
    {
		dbQueryParameters pp(dbKey) ;
		if (_orderIdSet)
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "orderid" , dbParam::EQUAL_TO , db::toSQL(dbKey, _orderId ))) ;
		}
		else
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "orderid" , dbParam::ISNULL)) ;
			
		}
		if(_userIdSet)
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "userid" , dbParam::EQUAL_TO , db::toSQL(dbKey, _userId ))) ;			
		}
		else
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "userid" , dbParam::ISNULL)) ;
		}
		
		sqlString.addANDWhereParameter(pp) ;
	}
	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << sqlString.getSQL()) ;
	
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString,"t_ondemanddistribution_Update") ;

	query.execForStatus() ;
    transaction.commit() ;
	resetModifiedFlag() ;
	return 0 ;

}


// remove the class from the database
dbPersistent::IdType dbOnDemandDistribution::remove(dbConnection &conn)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	// inside a transaction
	db::Transaction transaction(conn) ;
	transaction.begin_work("dbOnDemandDistribution_REMOVE") ;
    

    const string &dbKey = conn.getKey() ;
	
	SQLString sqlString ( dbKey, SQLString::DELETE ) ;
	sqlString.addTableList(getTable()) ;
	// Add where
    {
		dbQueryParameters pp(dbKey) ;
		if (_orderIdSet)
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "orderid" , dbParam::EQUAL_TO , db::toSQL(dbKey, _orderId ))) ;
		}
		else
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "orderid" , dbParam::ISNULL)) ;
			
		}
		if(_userIdSet)
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "userid" , dbParam::EQUAL_TO , db::toSQL(dbKey, _userId ))) ;			
		}
		else
		{
       		pp.addParameter(dbParam(dbKey, getTable(), "userid" , dbParam::ISNULL)) ;
		}
		
		sqlString.addANDWhereParameter(pp) ;
	}
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString,"t_ondemanddistribution_Delete") ;

	query.execForStatus() ;
	transaction.commit() ;

	resetFromDatabase() ;
	setModifiedFlag() ;

	return getId() ;
}


// True if the class have valid parameters, false otherwise
bool dbOnDemandDistribution::validate() const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	return true;
}

// export the class to stream
void dbOnDemandDistribution::exportObj(rsResourceSet &s) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbOnDemandDistribution") ;
	dbPersistent::exportObj(s) ;

	if(_orderIdSet) {
		s.setValue("_orderId",_orderId ) ;
    }
	s.setValue("_orderIdSet",_orderIdSet) ;

	if(_userIdSet) {
		s.setValue("_userId",_userId) ;
    }
	s.setValue("_userIdSet",_userIdSet) ;

	if(_formatSet) {
		s.setValue("_format",_format) ;
    }
	s.setValue("_formatSet",_formatSet) ;

	if(_mediaTypeSet) {
		s.setValue("_mediaType",_mediaType) ;
    }
	s.setValue("_mediaTypeSet",_mediaTypeSet) ;
	
	if(_disseminationAlgoSet) {
		s.setValue("_disseminationAlgo",_mediaType) ;
    }
	s.setValue("_disseminationAlgoSet",_disseminationAlgoSet) ;

}


// import the class from a stream
void dbOnDemandDistribution::importObj(rsResourceSet &s)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbOnDemandDistribution") ;
	dbPersistent::importObj(s) ;
	reset() ;
	s.getValue("_orderIdSet",_orderIdSet) ;
	if(_orderIdSet) {
		s.getValue("_orderId",_orderId) ;
    }

	s.getValue("_userIdSet",_userIdSet) ;
	if(_userIdSet) {
		s.getValue("_userId",_userId) ;
    }

	s.getValue("_formatSet",_formatSet) ;
	if(_formatSet) {
		s.getValue("_format",_format) ;
    }

	s.getValue("_mediaTypeSet",_mediaTypeSet) ;
	if(_mediaTypeSet) {
		s.getValue("_mediaType",_mediaType) ;
    }
	s.getValue("_disseminationAlgoSet",_disseminationAlgoSet) ;
	if(_disseminationAlgoSet) {
		s.getValue("_disseminationAlgo",_disseminationAlgo) ;
    }

}


// export the class to XML stream
void dbOnDemandDistribution::exportXML(XMLOstream &xst) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbOnDemandDistribution");
	dbPersistent::exportXML(xst) ;
    string null = "<null>" ;
	if(_orderIdSet)
	{
		XMLOstream::Tag txml0(xst, "_orderId", _orderId, "label=\"Order Id\"");
	}
	else
	{
		XMLOstream::Tag txml0(xst, "_orderId", null, "label=\"Order Id\"");
	}
	{
		XMLOstream::Tag txml0Set(xst, "_orderIdSet", (_orderIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_userIdSet)
	{
		XMLOstream::Tag txml1(xst, "_userId", _userId, "label=\"User Id\"");
	}
	else
	{
		XMLOstream::Tag txml1(xst, "_userId", null, "label=\"User Id\"");
	}
	{
		XMLOstream::Tag txml1Set(xst, "_userIdSet", (_userIdSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_formatSet)
	{
		XMLOstream::Tag txml2(xst, "_format", _format, "label=\"Format\"");
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_format", null, "label=\"Format\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_formatSet", (_formatSet ? "true" : "false")) ; // PRQA S 3380
	}

	if(_mediaTypeSet)
	{
		XMLOstream::Tag txml2(xst, "_mediaType", _format, "label=\"Media Type\"");
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_mediaType", null, "label=\"Media Type\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_mediaTypeSet", (_mediaTypeSet ? "true" : "false")) ; // PRQA S 3380
	}
	if(_disseminationAlgoSet)
	{
		XMLOstream::Tag txml2(xst, "_disseminationAlgo", _format, "label=\"Dissemination Packing Algo\"");
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_disseminationAlgo", null, "label=\"Dissemination Packing Algo\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_disseminationAlgoSet", (_disseminationAlgoSet ? "true" : "false")) ; // PRQA S 3380
	}

}



// load the object from a row
int dbOnDemandDistribution::loadRow(const dbRow &row, int offset)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	return privateLoadRow(row, offset) ;

}


// load the object from a row
int dbOnDemandDistribution::privateLoadRow(const dbRow &row, int offset)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050


	row.columnSet(offset + 0, _orderId, _orderIdSet) ; // PRQA S 3000, 3010 4
	row.columnSet(offset + 1, _userId, _userIdSet) ;
	row.columnSet(offset + 2, _format, _formatSet) ; // PRQA S 4400 2
	row.columnSet(offset + 3, _mediaType, _mediaTypeSet) ;
	row.columnSet(offset + 4, _disseminationAlgo, _disseminationAlgoSet) ;


	setFromDatabase() ;

	return offset + 5 ; // PRQA S 4400 
}


string dbOnDemandDistribution::getWhere()
{
	string res ;
	return res ;
}


string dbOnDemandDistribution::getIdName()
{
	return "" ;
}



void dbOnDemandDistribution::setOrderId(dbPersistent::IdType v)
{
	ThreadSafe::Lock guard(*this);// PRQA S 3050

	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	if (!_orderIdSet || (_orderId != v ) )
	{
		_orderId = v ;
		_orderIdSet = true ;
		setModifiedFlag() ;
	}
}


dbPersistent::IdType dbOnDemandDistribution::getOrderId(bool *set) const
{
	ThreadSafe::Lock guard(*this);// PRQA S 3050

	if (set) { *set = _orderIdSet ; }
	return _orderId ;
}

void dbOnDemandDistribution::unsetOrderId()
{
	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	ThreadSafe::Lock guard(*this);// PRQA S 3050
	if(_orderIdSet == true) {
		setModifiedFlag();
    }
	_orderIdSet = false;

}

void dbOnDemandDistribution::setUserId(const string &v)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")); // PRQA S 3081
	}

	if (!_userIdSet || (_userId != v ) )
	{
		_userId = v ;
		_userIdSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbOnDemandDistribution::getUserId(bool *set) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (set) { *set = _userIdSet ; }
	return _userId ;
}


void dbOnDemandDistribution::unsetUserId()
{
	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database.")) ; // PRQA S 3081
	}

	ThreadSafe::Lock guard(*this); // PRQA S 3050
	if(_userIdSet == true) {
		setModifiedFlag();
    }
	_userIdSet = false;

}
void dbOnDemandDistribution::setFormat(const string &v)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (v.size() > 16) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long.")); // PRQA S 3081
	}

	if (!_formatSet || (_format != v ) )
	{
		_format = v ;
		_formatSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbOnDemandDistribution::getFormat(bool *set) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (set) {
		*set = _formatSet ;
    }
	return _format ;
}


void dbOnDemandDistribution::unsetFormat()
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050
	if(_formatSet == true) {
		setModifiedFlag();
    }
	_formatSet = false;

}

void dbOnDemandDistribution::setMediaType(const string &v)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050


	if (!_mediaTypeSet || (_mediaType != v ) )
	{
		_mediaType = v ;
		_mediaTypeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbOnDemandDistribution::getMediaType(bool *set) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (set) {*set = _mediaTypeSet ;}
	return _mediaType ;
}


void dbOnDemandDistribution::unsetMediaType()
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050
	if(_mediaTypeSet == true) {
		setModifiedFlag();
    }
	_mediaTypeSet = false;

}
void dbOnDemandDistribution::setDisseminationAlgo(const string &v)
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050


	if (!_disseminationAlgoSet || (_disseminationAlgo != v ) )
	{
		_disseminationAlgo = v ;
		_disseminationAlgoSet = true ;
		setModifiedFlag() ;
	}
}
const string &dbOnDemandDistribution::getDisseminationAlgo(bool *set) const
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050

	if (set) {*set = _disseminationAlgoSet ;}
	return _disseminationAlgo ;
}
void dbOnDemandDistribution::unsetDisseminationAlgo()
{
	ThreadSafe::Lock guard(*this); // PRQA S 3050
	if(_disseminationAlgoSet == true) {
		setModifiedFlag();
    }
	_disseminationAlgoSet = false;

}

// get the field names
string dbOnDemandDistribution::getFields()
{
	string s ;
	s += privateGetFields() ;
	return s ;
}


// get the field names
string dbOnDemandDistribution::privateGetFields()
{
	string s ;
	s += "t_ondemanddistribution.orderid, ";
	s += "t_ondemanddistribution.userid, ";
	s += "t_ondemanddistribution.format," ;
	s += "t_ondemanddistribution.mediatype, " ;
	s += "t_ondemanddistribution.disseminationpackingalgo_id" ;
	return s ;
}


// get the table name
string dbOnDemandDistribution::getTable()
{
	return "T_OnDemandDistribution" ;
}


// get the order by clause
string dbOnDemandDistribution::getOrderBy()
{
	string res ;
	res += privateGetOrderBy() ;
	return res ;
}


// get the order by clause
string dbOnDemandDistribution::privateGetOrderBy()
{
	string res ;
	res +="OrderId , UserId DESC" ;
	return res ;
}


void dbOnDemandDistribution::writeTo(ostream &o) const
{
	Lock lock(*this) ; //  PRQA S 3050
    string null = "<null>" ;
	o
		 << "_orderId = " << (_orderIdSet ? db::toSQL("", _orderId) : null) << "\n"  // PRQA S 3380, 3385 3
		 << "_userId = " << (_userIdSet ? _userId : null) << "\n" 
		 << "_format = " << (_formatSet ? _format : null) << "\n"  
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : null) << "\n"  
		 << "_disseminationAlgo = " << (_disseminationAlgoSet ? _disseminationAlgo : null) << "\n"  ;
}


void dbOnDemandDistribution::writeTo(exostream &o) const
{
	Lock lock(*this) ; //  PRQA S 3050
    string null = "<null>" ;
	o
		 << "_orderId = " << (_orderIdSet ? db::toSQL("", _orderId) : null) << "\n"  // PRQA S 3380, 3385 3
		 << "_userId = " << (_userIdSet ? _userId : null) << "\n" 
		 << "_format = " << (_formatSet ? _format : null) << "\n"  
		 << "_mediaType = " << (_mediaTypeSet ? _mediaType : null) << "\n"  
		 << "_disseminationAlgo = " << (_disseminationAlgoSet ? _disseminationAlgo : null) << "\n"  ;
}


_ACS_END_NAMESPACE
