// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 7.0  2017/05/31 17:32:59  nicvac
	OPMAN-260: Need PDS DB schema PDS_12-04.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:01  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:29  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.7  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.6  2013/02/12 12:38:53  marpas
	interfaces improved over qa rules
	
	Revision 2.5  2012/11/16 13:01:14  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.3  2012/06/15 09:54:30  marpas
	removing warning related to virtual method hiding
	
	Revision 2.2  2012/02/14 12:52:49  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.1  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.21  2005/06/17 10:31:55  marpas
	std namespaces took into consideration
	
	Revision 1.20  2004/10/01 16:50:39  paoscu
	file class added
	
	Revision 1.19  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.18  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.17  2004/04/13 16:57:09  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.16  2004/03/04 18:55:36  paoscu
	Now primary key is a serial id.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbOrderGeneration_H_
#define _dbOrderGeneration_H_

#include <acs_c++config.hpp>
#include <exException.h>
#include <dbPersistent.h>

#include <string>


_ACS_BEGIN_NAMESPACE(acs)
	
class dbCryosatFactory ;

class dbRow ;
class rsResourceSet ;
class XMLOstream ;

//
//
//
// class dbOrderGeneration
//
//
//
class dbOrderGeneration :   // PRQA S 2109
	public dbPersistent
{
public:
	friend class dbCryosatFactory ; // PRQA S 2107

	virtual ~dbOrderGeneration() throw() ;
	dbOrderGeneration &operator=(const dbOrderGeneration &) ; // operator =

	static  std::string staticClassName() ;
	virtual dbPersistent *clone() const ;   // PRQA S 2502

	// inherited from dbPersistent
	virtual std::string className() const ;
	virtual void reset() ; // initialize the class
	virtual IdType save(dbConnection &)  ; // save the data in database
	virtual bool load(dbConnection & , IdType id=0)  ; // load the class from the database. Return true if obect exist
	virtual IdType update(dbConnection &)  ; // update an existing instance in database
	virtual IdType remove(dbConnection &)  ; // remove the class from the database    // PRQA S 2502
	virtual bool validate() const  ; // True if the class have valid parameters, false otherwise
	virtual void exportObj(rsResourceSet &s) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &s)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &xst) const ; // export the class to XML stream

	int loadRow(const dbRow &, int offset=0) ;

	void setProcessorName(const std::string &) ;
	const std::string &getProcessorName(bool *set=0) const ;
	void unsetProcessorName();

	void setProcessorVersion(const std::string &) ;
	const std::string &getProcessorVersion(bool *set=0) const ;
	void unsetProcessorVersion();

	void setProcessorConfiguration(const std::string &) ;
	const std::string &getProcessorConfiguration(bool *set=0) const ;
	void unsetProcessorConfiguration();

	void setAlgorithm(const std::string &) ;
	const std::string &getAlgorithm(bool *set=0) const ;
	void unsetAlgorithm();

	void setOrderType(const std::string &) ;
	const std::string &getOrderType(bool *set=0) const ;
	void unsetOrderType();

	void setFileClass(const std::string &) ;
	const std::string &getFileClass(bool *set=0) const ;
	void unsetFileClass();

	void setFileType(const std::string &) ;
	const std::string &getFileType(bool *set=0) const ;
	void unsetFileType();

	void setActive(bool) ;
	bool getActive(bool *set=0) const ;
	void unsetActive();

	void setPriority(int) ;
	int getPriority(bool *set=0) const ;
	void unsetPriority();

	void setTroubleShooting(bool) ;
	bool getTroubleShooting(bool *set=0) const ;
	void unsetTroubleShooting();

	void setProcessingTimeWindow(int) ;
	int getProcessingTimeWindow(bool *set=0) const ;
	void unsetProcessingTimeWindow();

	static std::string getFields() ;
	static std::string getTable() ;
	static std::string getOrderBy() ;

	// output to stream
	virtual void writeTo(std::ostream &) const ;
	virtual void writeTo(exostream &) const ;


protected:
	dbOrderGeneration() ;
	dbOrderGeneration(const dbOrderGeneration &) ;


private:
	std::string _processorName ;
	bool _processorNameSet ;

	std::string _processorVersion ;
	bool _processorVersionSet ;

	std::string _processorConfiguration ;
	bool _processorConfigurationSet ;

	std::string _algorithm ;
	bool _algorithmSet ;

	std::string _orderType ;
	bool _orderTypeSet ;

	std::string _fileClass ;
	bool _fileClassSet ;

	std::string _fileType ;
	bool _fileTypeSet ;

	bool _active ;
	bool _activeSet ;

	int _priority ;
	bool _prioritySet ;

	bool _troubleShooting ;
	bool _troubleShootingSet ;

	int _processingTimeWindow ;
	bool _processingTimeWindowSet ;

	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbOrderGeneration) ;
} ;


_ACS_END_NAMESPACE

#endif // _dbOrderGeneration_H_
