// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/10/07 11:31:44  marpas
	moving all NameIdAssociator in libDbClient along all the others
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.1  2016/03/24 10:03:53  marpas
	fixed interface (wrong reference type for order id )
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:02  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:30  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.11  2013/04/30 13:31:43  marpas
	dbPersistent interface changed
	
	Revision 2.10  2013/04/17 17:37:24  marpas
	dbPersistent interface changed
	
	Revision 2.9  2013/04/05 09:36:19  marpas
	NameIdAssociator partial refactoring
	
	Revision 2.8  2012/11/16 13:01:15  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.6  2012/02/14 12:52:50  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.5  2011/03/02 17:00:49  marpas
	warning removed
	
	Revision 2.4  2009/02/11 16:23:43  marpas
	new methods added
	
	Revision 2.3  2008/10/14 15:01:58  marpas
	dbOrdersAttachmentQuery class added
	
	Revision 2.2  2008/10/14 13:36:20  marpas
	ordersattachment class implemented and tested
	
	Revision 2.1  2008/10/13 13:58:10  marpas
	dbOrdersAttachment class added (work in progress) still missing BLOB management
	
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbOrdersAttachment.h>
#include <OrdersAttachmentType.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <SQLString.h>
#include <dbQuery.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbOrdersAttachment)

// constructor
dbOrdersAttachment::dbOrdersAttachment(dbConnection &c) : dbSmartPersistent("t_ordersattachments", c)
{
	reset() ;
}


// copy constructor
dbOrdersAttachment::dbOrdersAttachment(const dbOrdersAttachment &o):
	dbSmartPersistent(o)
{
}


dbOrdersAttachment::~dbOrdersAttachment() throw()
{
}



dbPersistent *dbOrdersAttachment::clone() const
{
	return new dbOrdersAttachment(*this) ;
}


// operator =
dbOrdersAttachment &dbOrdersAttachment::operator=(const dbOrdersAttachment &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


string dbOrdersAttachment::className() const
{
	return staticClassName() ;
}


string dbOrdersAttachment::staticClassName()
{
	return "dbOrdersAttachment" ;
}


// export the class to stream
void dbOrdersAttachment::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbOrdersAttachment") ;
	dbPersistent::exportObj(s) ;
}





// import the class from a stream
void dbOrdersAttachment::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbOrdersAttachment") ;
	dbSmartPersistent::importObj(s) ;
}




// export the class to XML stream
void dbOrdersAttachment::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbOrdersAttachment");
	dbSmartPersistent::exportXML(xst) ;
}


void dbOrdersAttachment::setOrderId(dbPersistent::IdType v, dbConnection &c)
{
	set<dbPersistent::IdType>("orderid",v,c) ;
}


dbPersistent::IdType dbOrdersAttachment::getOrderId(bool &set, dbConnection &c) const
{
	dbPersistent::IdType v ; 
	
	get<dbPersistent::IdType>("orderid",v, set, c) ;

	return v ;
}


void dbOrdersAttachment::unsetOrderId()
{
	unset("orderid") ;
}

void dbOrdersAttachment::setAttachType(int v, dbConnection &c)
{
	set<int>("attachtype",v, c) ;
}


int dbOrdersAttachment::getAttachType(bool &set, dbConnection &c) const
{
	int v ; 
	
	get<int>("attachtype",v, set, c) ;

	return v ;
}


void dbOrdersAttachment::unsetAttachType()
{
	unset("attachtype") ;
}




void dbOrdersAttachment::setAttachName(const string & v, dbConnection &c)
{
	set<string>("attachname",v,c) ;
}


string dbOrdersAttachment::getAttachName(bool &set, dbConnection &c) const
{
	string v ; 
	
	get<string>("attachname",v, set, c) ;

	return v ;
}


void dbOrdersAttachment::unsetAttachName()
{
	unset("attachname") ;
}

void dbOrdersAttachment::setAttachment(const std::string &path, dbConnection &conn) 
{
	setFilePath("attachment",path, conn);
}


std::string dbOrdersAttachment::getAttachment(dbConnection &conn) const 
{
	return getFilePath("attachment", conn) ;
}

void dbOrdersAttachment::unsetAttachment(dbConnection &conn)
{
	unsetFilePath("attachment", conn) ;
}



// get the field names
string dbOrdersAttachment::getFields()
{
	string s ;
	s += getTable() + "." + "Id, ";
	s += getTable() + "." + "OrderId, ";
	s += getTable() + "." + "AttachType, ";
	s += getTable() + "." + "AttachName, ";
	s += getTable() + "." + "attachment ";
	return s ;
}


// get the table name
string dbOrdersAttachment::getTable()
{
	return "T_OrdersAttachments" ;
}


string dbOrdersAttachment::download(const string &path, dbConnection &conn) const 
{
	bool set ;
	string name = getAttachName(set, conn) ;
	ostringstream os ;
	if (name.empty()) {
		os << "OrderAttachment_" << OrdersAttachmentType::instance(conn.getKey())->name(getAttachType(set, conn)) << "_" ;
	}
	else {
		os << name << "_" ;
	}
	os << getId() ;
	downloadFile("attachment",path+"/"+os.str(), conn) ;
	return os.str() ;
}
	
_ACS_END_NAMESPACE
