// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/21 16:07:01  damdec
	Compilation warnings fixed
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:02  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:30  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.7  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.6  2013/02/13 18:04:23  marpas
	qa rules warnings removed
	
	Revision 2.5  2012/11/16 13:01:15  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.3  2012/06/15 09:54:30  marpas
	removing warning related to virtual method hiding
	
	Revision 2.2  2012/02/14 12:52:50  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.1  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.18  2005/06/17 10:31:55  marpas
	std namespaces took into consideration
	
	Revision 1.17  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.16  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.15  2004/04/13 16:57:09  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.14  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbOrderType_H_
#define _dbOrderType_H_

#include <acs_c++config.hpp>
#include <exException.h>
#include <dbPersistent.h>

#include <string>

_ACS_BEGIN_NAMESPACE(acs)


class dbRow ;
class rsResourceSet ;
class XMLOstream ;

//
//
//
// class dbOrderType
//
//
//
class dbOrderType :
	public dbPersistent
{
public:
	friend class dbCryosatFactory ; // PRQA S 2107

	virtual ~dbOrderType() throw() ;
	dbOrderType &operator=(const dbOrderType &) ; // operator =

	static  std::string staticClassName() ;
	virtual dbPersistent *clone() const ; // PRQA S 2502

	// inherited from dbPersistent
	virtual std::string className() const ;
	virtual void reset() ; // initialize the class
	virtual IdType save(dbConnection &)  ; // save the data in database
	virtual bool load(dbConnection & , IdType id=0)  ; // load the class from the database. Return true if obect exist
	virtual IdType update(dbConnection &)  ; // update an existing instance in database
	virtual IdType remove(dbConnection &)  ; // remove the class from the database // PRQA S 2502
	virtual bool validate() const  ; // True if the class have valid parameters, false otherwise
	virtual void exportObj(rsResourceSet &s) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &s)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &xst) const ; // export the class to XML stream

	int loadRow(const dbRow &, int offset=0) ;

	void setOrderType(const std::string &) ;
	const std::string &getOrderType(bool *set=0) const ;
	void unsetOrderType();

	void setOrderTypeDescription(const std::string &) ;
	const std::string &getOrderTypeDescription(bool *set=0) const ;
	void unsetOrderTypeDescription();

	static std::string getFields() ;
	static std::string getTable() ;
	static std::string getOrderBy() ;

	// output to stream
	virtual void writeTo(std::ostream &) const ;
	virtual void writeTo(exostream &) const ;


protected:
	dbOrderType() ;
	dbOrderType(const dbOrderType &) ;


private:
	std::string _orderType ;
	bool _orderTypeSet ;

	std::string _orderTypeDescription ;
	bool _orderTypeDescriptionSet ;

	
	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbOrderType)
} ;

_ACS_END_NAMESPACE


#endif // _dbOrderType_H_
