/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.1  2014/05/26 11:39:45  marpas
	dbConv casted to avoid problem with new libXMLResources templates for tags
	
	Revision 4.0  2013/09/30 12:31:02  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:29  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.9  2013/04/12 12:14:39  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.8  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.7  2012/11/16 13:01:15  marpas
	realignement of MAIN STREAM
	Introducing ADCS1FixedHeaderFactory class
	
	Revision 2.5  2012/03/20 10:24:59  marpas
	informix column name fixed
	
	Revision 2.4  2012/03/14 16:00:35  marpas
	minoorg changes for QT interfaces
	
	Revision 2.3  2012/02/14 12:52:49  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.2  2011/03/02 18:47:14  marpas
	serial 8 support
	
	Revision 2.1  2008/11/17 11:34:34  marpas
	column names changed (timestamp) into tstamp
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.24  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.23  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.22  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.21  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.20  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.19  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.18  2004/04/13 16:57:09  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.17  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbOrderStateTransition.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>



using namespace acs ;
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbOrderStateTransition)

// constructor
dbOrderStateTransition::dbOrderStateTransition() :
	dbPersistent(),
	_orderId(),
	_orderIdSet(),
	_tstamp(),
	_tstampSet(),
	_status(),
	_statusSet()

{
	reset() ;
}


// copy constructor
dbOrderStateTransition::dbOrderStateTransition(const dbOrderStateTransition &o):
	dbPersistent(o),
	_orderId(o._orderId),
	_orderIdSet(o._orderIdSet),
	_tstamp(o._tstamp),
	_tstampSet(o._tstampSet),
	_status(o._status),
	_statusSet(o._statusSet)
{
}


dbOrderStateTransition::~dbOrderStateTransition() throw()
{
}


dbPersistent *dbOrderStateTransition::clone() const
{
	return new dbOrderStateTransition(*this) ;
}


// operator =
dbOrderStateTransition &dbOrderStateTransition::operator=(const dbOrderStateTransition &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_orderId=o._orderId;
		_orderIdSet=o._orderIdSet;
		_tstamp=o._tstamp;
		_tstampSet=o._tstampSet;
		_status=o._status;
		_statusSet=o._statusSet;
	}
	return *this ;
}


string dbOrderStateTransition::className() const
{
	return staticClassName() ;
}


string dbOrderStateTransition::staticClassName()
{
	return "dbOrderStateTransition" ;
}



// initialize the class
void dbOrderStateTransition::reset()
{
	Lock lock(*this) ;

	// reset dbPersistent
	dbPersistent::reset() ;
	_orderId=0 ;
	_orderIdSet=false ;
	_tstamp.reset() ;
	_tstampSet=false ;
	_status="" ;
	_statusSet=false ;
}


// save the data in database
dbPersistent::IdType dbOrderStateTransition::save(dbConnection &conn)
{
	Lock lock(*this) ;

	InvalidUse e("Error: dbOrderStateTransition::save(), the table doesn't allow save") ;
	ACS_THROW(e) ;

	return 0 ; 
}

// load the class from the database. Return true if object exist
bool dbOrderStateTransition::load(dbConnection &conn, IdType id)
{
	Lock lock(*this) ;

	InvalidUse e("Error: dbOrderStateTransition::load(), the table doesn't allow to load") ;
	ACS_THROW(e) ;

	return false ; 
}

// update an existing instance in database
dbPersistent::IdType dbOrderStateTransition::update(dbConnection &conn)
{
	Lock lock(*this) ;

	InvalidUse e("Error: dbOrderStateTransition::update(), the table doesn't allow to update") ;
	ACS_THROW(e) ;

	return 0 ; 
}

// remove the class from the database
dbPersistent::IdType dbOrderStateTransition::remove(dbConnection &conn)
{
	Lock lock(*this) ;

	InvalidUse e("Error: dbOrderStateTransition::remove(), the table doesn't allow to remove") ;
	ACS_THROW(e) ;

	return 0 ; 
}

// True if the class have valid parameters, false otherwise
bool dbOrderStateTransition::validate() const
{
	Lock lock(*this) ;

	return true;
}

// export the class to stream
void dbOrderStateTransition::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbOrderStateTransition") ;
	dbPersistent::exportObj(s) ;
	if(_orderIdSet)
	{
		s.setValue("_orderId",_orderId) ;
	}
	s.setValue("_orderIdSet",_orderIdSet) ;
	if(_tstampSet)
	{
		{
		rsPushNSpace rpns1(s,"_tstamp") ;
		_tstamp.exportObj(s) ;
		}
	}
	s.setValue("_tstampSet",_tstampSet) ;
	if(_statusSet)
	{
		s.setValue("_status",_status) ;
	}
	s.setValue("_statusSet",_statusSet) ;
}


// import the class from a stream
void dbOrderStateTransition::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbOrderStateTransition") ;
	dbPersistent::importObj(s) ;
	s.getValue("_orderIdSet",_orderIdSet) ;
	if(_orderIdSet)
	{
		s.getValue("_orderId",_orderId) ;
	}
	else
		_orderId = 0 ;
	s.getValue("_tstampSet",_tstampSet) ;
	if(_tstampSet)
	{
		{
		rsPushNSpace rpns1(s,"_tstamp") ;
		_tstamp.importObj(s) ;
		}
	}
	else
		_tstamp.reset() ;
	s.getValue("_statusSet",_statusSet) ;
	if(_statusSet)
	{
		s.getValue("_status",_status) ;
	}
	else
		_status = "" ;
}


// export the class to XML stream
void dbOrderStateTransition::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbOrderStateTransition");
	dbPersistent::exportXML(xst) ;
	if(_orderIdSet)
	{
	XMLOstream::Tag txml0(xst, "_orderId", string(db::toSQL("",_orderId)), "label=\"Order Id\"");
	}
	else
	{
	XMLOstream::Tag txml0(xst, "_orderId", string("<null>"), "label=\"Order Id\"");
	}
	{
	XMLOstream::Tag txml0Set(xst, "_orderIdSet", (_orderIdSet ? "true" : "false")) ;
	}
	if(_tstampSet)
	{
		XMLOstream::Tag txml1(xst, "_tstamp", "", "label=\"TStamp\"");
		_tstamp.exportXML(xst) ;
	}
	else
	{
	XMLOstream::Tag txml1(xst, "_tstamp", string("<null>"), "label=\"TStamp\"");
	}
	{
	XMLOstream::Tag txml1Set(xst, "_tstampSet", (_tstampSet ? "true" : "false")) ;
	}
	if(_statusSet)
	{
	XMLOstream::Tag txml2(xst, "_status", _status, "label=\"Status\"");
	}
	else
	{
	XMLOstream::Tag txml2(xst, "_status", string("<null>"), "label=\"Status\"");
	}
	{
	XMLOstream::Tag txml2Set(xst, "_statusSet", (_statusSet ? "true" : "false")) ;
	}
}




// load the object from a row
int dbOrderStateTransition::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ;

	row.columnSet(offset + 0, _orderId, _orderIdSet) ;
	row.columnSet(offset + 1, _tstamp, _tstampSet) ;
	row.columnSet(offset + 2, _status, _statusSet) ;


	setFromDatabase() ;

	return offset + 3 ;
}


void dbOrderStateTransition::setOrderId(int v)
{
	Lock lock(*this) ;

	if (!_orderIdSet || _orderId != v ) 
	{
		_orderId = v ;
		_orderIdSet = true ;
		setModifiedFlag() ;
	}
}


int dbOrderStateTransition::getOrderId(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _orderIdSet ;
	return _orderId ;
}


void dbOrderStateTransition::unsetOrderId()
{
	Lock lock(*this) ;
	if(_orderIdSet == true)
		setModifiedFlag();
	_orderIdSet = false;

}
void dbOrderStateTransition::setTStamp(const DateTime &v)
{
	Lock lock(*this) ;

	if (!_tstampSet || _tstamp != v ) 
	{
		_tstamp = v ;
		_tstampSet = true ;
		setModifiedFlag() ;
	}
}


const DateTime &dbOrderStateTransition::getTStamp(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _tstampSet ;
	return _tstamp ;
}


void dbOrderStateTransition::unsetTStamp()
{
	Lock lock(*this) ;
	if(_tstampSet == true)
		setModifiedFlag();
	_tstampSet = false;

}
void dbOrderStateTransition::setStatus(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 32)
	{
		InvalidUse e("Error: dbOrderStateTransition::setStatus(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_statusSet || _status != v ) 
	{
		_status = v ;
		_statusSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbOrderStateTransition::getStatus(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _statusSet ;
	return _status ;
}


void dbOrderStateTransition::unsetStatus()
{
	Lock lock(*this) ;
	if(_statusSet == true)
		setModifiedFlag();
	_statusSet = false;

}
// get the field names
string dbOrderStateTransition::getFields()
{
	string s ;
	s += getTable() + "." + "OrderId, ";
#warning MP conn is needed for dialectName()
	const string dialectName = SQLDialectFactory::dialectName("");
	if( dialectName == "Postgres8" || dialectName == "Oracle11" ) {
	    s += getTable() + "." + "tstamp, ";
    }
	else if (dialectName == "Informix9" ) {
	    s += getTable() + "." + "timestamp, ";
    } else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
    s += getTable() + "." + "Status" ;
	return s ;
}


// get the table name
string dbOrderStateTransition::getTable()
{
	return "T_OrderStateTransitions" ;
}


// get the order by clause
string dbOrderStateTransition::getOrderBy()
{
	return "" ;
}


void dbOrderStateTransition::writeTo(ostream &o) const
{
	Lock lock(*this) ;

	string tmp ; 

	o
		 << "_orderId = " << (_orderIdSet ? string(db::toSQL("",_orderId)) : string("<null>")) << "\n" 
		 << "_tstamp = " << (_tstampSet ? _tstamp.utcs(tmp) : string("<null>")) << "\n" 
		 << "_status = " << (_statusSet ? _status : string("<null>")) << "\n"  ;
}


void dbOrderStateTransition::writeTo(exostream &o) const
{
	Lock lock(*this) ;

	string tmp ; 

	o
		 << "_orderId = " << (_orderIdSet ? string(db::toSQL("",_orderId)) : string("<null>")) << "\n" 
		 << "_tstamp = " << (_tstampSet ? _tstamp.utcs(tmp) : string("<null>")) << "\n" 
		 << "_status = " << (_statusSet ? _status : string("<null>")) << "\n"  ;
}


