/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/26 10:09:50  damdec
	Compilation warnings fixed. CSGACQ-86: remove method uses now SQLString
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:02  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:30  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.13  2013/04/12 12:14:39  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.12  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.11  2012/02/14 12:52:50  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.10  2011/03/02 18:47:15  marpas
	serial 8 support
	
	Revision 2.9  2010/03/05 15:09:11  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.8  2009/02/09 15:46:51  marpas
	loading a processor with only its name set will return a record with the lexicographically greater version for that name
	
	Revision 2.7  2008/09/23 13:16:08  crivig
	porting to postgres8
	
	Revision 2.6  2007/03/23 15:29:41  marpas
	update method fixed again
	
	Revision 2.5  2007/03/23 15:27:16  marpas
	update method fixed
	
	Revision 2.4  2007/03/23 14:46:23  marpas
	aligned to new schema for ADM
	
	Revision 2.3  2007/03/19 11:29:09  marpas
	ADM work in progress
	
	Revision 2.2  2006/06/09 12:45:59  giucas
	Fixed syntax error in update query.
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.30  2005/06/15 07:44:50  integrator
	multiple storage manager implemented
	
	Revision 1.29  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.28  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.27  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.26  2004/07/07 10:34:32  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.25  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.24  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.23  2004/04/13 16:57:09  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.22  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbProcessor.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>



using namespace acs ;
using namespace std ;


ACS_CLASS_DEFINE_DEBUG_LEVEL(dbProcessor)

// constructor
dbProcessor::dbProcessor():
	_processorName(""),
	_processorNameSet(false),
	_processorVersion(""),
	_processorVersionSet(false),
	_description(""),
	_descriptionSet(false),
	_baseline(""),
	_baselineSet(false) 
{
	dbPersistent::reset() ;
}


// copy constructor
dbProcessor::dbProcessor(const dbProcessor &o):
	dbPersistent(o),
	_processorName(o._processorName),
	_processorNameSet(o._processorNameSet),
	_processorVersion(o._processorVersion),
	_processorVersionSet(o._processorVersionSet),
	_description(o._description),
	_descriptionSet(o._descriptionSet),
	_baseline(o._baseline),
	_baselineSet(o._baselineSet)
{
}


dbProcessor::~dbProcessor() throw()
{
}



dbPersistent *dbProcessor::clone() const
{
	return new dbProcessor(*this) ;
}


// operator =
dbProcessor &dbProcessor::operator=(const dbProcessor &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_processorName=o._processorName;
		_processorNameSet=o._processorNameSet;
		_processorVersion=o._processorVersion;
		_processorVersionSet=o._processorVersionSet;
		_description=o._description;
		_descriptionSet=o._descriptionSet;
		_baseline=o._baseline;
		_baselineSet=o._baselineSet;
	}
	return *this ;
}


string dbProcessor::className() const
{
	return staticClassName() ;
}


string dbProcessor::staticClassName()
{
	return "dbProcessor" ;
}


// initialize the class
void dbProcessor::reset()
{
	Lock lock(*this) ;

	// reset dbPersistent
	dbPersistent::reset() ;
	_processorName="" ;
	_processorNameSet=false ;
	_processorVersion="" ;
	_processorVersionSet=false ;
	_description="" ;
	_descriptionSet=false ;
	_baseline="" ;
	_baselineSet=false ;
}


// save the data in database
dbPersistent::IdType dbProcessor::save(dbConnection &conn)
{
	Lock lock(*this) ;

	if (!isModified())
		return 0 ; 

	if (isFromDatabase()) 
	{
		InvalidUse e("Error: dbProcessor::save(). Use the method update() instead of save().") ;
		ACS_THROW(e) ;
	}
	if(!_processorNameSet) 
	{
		InvalidUse e("Mandatory field \"Processor Name\" must be set.") ;
		ACS_THROW(e) ;
	}
	if(!_processorVersionSet) 
	{
		InvalidUse e("Mandatory field \"Processor Version\" must be set.") ;
		ACS_THROW(e) ;
	}


    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "INSERT INTO " + getTable() + " (" ;
		queryString += "ProcessorName" ;
		queryString += ", ProcessorVersion" ;
		if(_descriptionSet)
			queryString += ", Description" ;
		if(_baselineSet)
			queryString += ", Baseline" ;
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey, _processorName);
		queryString +=	", " + db::toSQL(dbKey, _processorVersion);
		if(_descriptionSet)
			queryString +=	", " + db::toSQL(dbKey, _description);
		if(_baselineSet)
			queryString +=	", " + db::toSQL(dbKey, _baseline) ;
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB,"SQL = " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbProcessor::save") ;

	if (!query.execForStatus())
	{
		dbQuery::QueryExecuteException e(string("Query Execution error: Command : ")
		+ string(queryString)
		+ string(" Error : ")
		+ string(query.errorString())) ;
		ACS_THROW (e) ;
	}

	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbProcessor::load(dbConnection &conn , IdType id)
{
	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB) ;
	Lock lock(*this) ;

	dbProcessor tempRecord(*this); //store current record.

	reset() ; 

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	getFields() ;
		queryString += " FROM " + getTable() ;
		queryString += " WHERE ProcessorName " ;
		if(tempRecord._processorNameSet)
			queryString +=	string("= ") + db::toSQL(dbKey, tempRecord._processorName);
		else
			queryString +=	" IS NULL" ;
		if(tempRecord._processorVersionSet)
			queryString += " AND ProcessorVersion = " + db::toSQL(dbKey, tempRecord._processorVersion) ;
/*
		else
			queryString += " AND ProcessorVersion IS NULL ";
*/
		string getOrderByString(getOrderBy()) ;
		if(!getOrderByString.empty() )
			queryString += " ORDER BY " + getOrderByString ;

	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbProcessor::load") ;
	dbRow row(dbKey) ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB,"SQL = " << queryString) ;

	try
	{
        dbSet set ;
		query.execForSet(set) ;
        ACS_COND_THROW(set.empty(), dbQuery::QueryNoDataFound("empty set")) ; // PRQA S 3081 2
        ACS_COND_THROW(set.size() > 1, exIllegalValueException("Set size > 1")) ;
        set.getNextRow(row) ; // first and only 
	}
	catch (dbQuery::QueryNoDataFound &e)
	{
		*this = tempRecord;  //Nothing found: restore previuos situation.
		return false ;
	}

	loadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB,"Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbProcessor::update(dbConnection &conn)
{
	Lock lock(*this) ;

	if (!isFromDatabase())
	{
		ObjectNotLoaded ex("Error: dbProcessor::update(). Use the method save() instead of update().") ; 
		ACS_THROW(ex)
	}

	if (!isModified())
		return 0 ; 

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = string("UPDATE ") + getTable() + " SET " ; 
		if(_descriptionSet)
			queryString += "Description= " + db::toSQL(dbKey, _description);
		else
			queryString += "Description=  NULL " ; 
		if(_baselineSet)
			queryString += ", Baseline= " + db::toSQL(dbKey, _baseline) ;
		else
			queryString += ", Baseline=  NULL " ; 
		queryString += " WHERE " ;
		queryString += "ProcessorName " ;
		queryString +=	string("= ") + db::toSQL(dbKey, _processorName) + " AND " ;
		queryString += "ProcessorVersion " ;
		queryString +=	string("= ") + db::toSQL(dbKey, _processorVersion) ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB,"SQL = " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbProcessor::update") ;

	query.execForStatus() ;


	resetModifiedFlag() ;
	return 0 ;

}


// remove the class from the database
dbPersistent::IdType dbProcessor::remove(dbConnection &conn)
{
	Lock lock(*this) ;

    const string &dbKey = conn.getKey() ;

	SQLString sqlString ( dbKey, SQLString::DELETE ) ;
	sqlString.addTableList(getTable());
    // Build Where clause
    {
        dbQueryParameters pp(dbKey) ;
		if(_processorNameSet)
		{
	    	pp.addParameter(dbParam(dbKey, getTable(),"ProcessorName" , dbParam::EQUAL_TO , db::toSQL(dbKey, _processorName) )) ;
		}
		else
		{
	    	pp.addParameter(dbParam(dbKey, getTable(),"ProcessorName" , dbParam::ISNULL )) ;
		}
		if(_processorVersionSet)
		{
	    	pp.addParameter(dbParam(dbKey, getTable(),"ProcessorVersion" , dbParam::EQUAL_TO , db::toSQL(dbKey, _processorVersion) )) ;
		}
		else
		{
	    	pp.addParameter(dbParam(dbKey, getTable(),"ProcessorVersion" , dbParam::ISNULL )) ;
		}
	    sqlString.addORWhereParameter(pp) ;
    }

	dbQuery query(conn, sqlString, "dbProcessor::remove") ;

	query.execForStatus() ;

	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbProcessor::validate() const
{
	Lock lock(*this) ;

	return true;
}


// export the class to stream
void dbProcessor::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbProcessor") ;
	dbPersistent::exportObj(s) ;
	if(_processorNameSet)
	{
		s.setValue("_processorName",_processorName) ;
	}
	s.setValue("_processorNameSet",_processorNameSet) ;
	if(_processorVersionSet)
	{
		s.setValue("_processorVersion",_processorVersion) ;
	}
	s.setValue("_processorVersionSet",_processorVersionSet) ;
	if(_descriptionSet)
	{
		s.setValue("_description",_description) ;
	}
	s.setValue("_descriptionSet",_descriptionSet) ;
	if(_baselineSet)
	{
		s.setValue("_baseline",_baseline) ;
	}
	s.setValue("_baselineSet",_baselineSet) ;
}


// import the class from a stream
void dbProcessor::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbProcessor") ;
	dbPersistent::importObj(s) ;
	s.getValue("_processorNameSet",_processorNameSet) ;
	if(_processorNameSet)
	{
		s.getValue("_processorName",_processorName) ;
	}
	else
		_processorName = "" ;
	s.getValue("_processorVersionSet",_processorVersionSet) ;
	if(_processorVersionSet)
	{
		s.getValue("_processorVersion",_processorVersion) ;
	}
	else
		_processorVersion = "" ;
	s.getValue("_descriptionSet",_descriptionSet) ;
	if(_descriptionSet)
	{
		s.getValue("_description",_description) ;
	}
	else
		_description = "" ;
	if(_baselineSet)
	{
		s.getValue("_baseline",_baseline) ;
	}
	else
		_baseline = "" ;
}


// export the class to XML stream
void dbProcessor::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbProcessor");
	dbPersistent::exportXML(xst) ;
	if(_processorNameSet)
	{
	XMLOstream::Tag txml0(xst, "_processorName", _processorName, "label=\"Processor Name\"");
	}
	else
	{
	XMLOstream::Tag txml0(xst, "_processorName", string("<null>"), "label=\"Processor Name\"");
	}
	{
	XMLOstream::Tag txml0Set(xst, "_processorNameSet", (_processorNameSet ? "true" : "false")) ;
	}
	if(_processorVersionSet)
	{
	XMLOstream::Tag txml1(xst, "_processorVersion", _processorVersion, "label=\"Processor Version\"");
	}
	else
	{
	XMLOstream::Tag txml1(xst, "_processorVersion", string("<null>"), "label=\"Processor Version\"");
	}
	{
	XMLOstream::Tag txml1Set(xst, "_processorVersionSet", (_processorVersionSet ? "true" : "false")) ;
	}
	if(_descriptionSet)
	{
		XMLOstream::Tag txml2(xst, "_description", _description, "label=\"Description\"");
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_description", string("<null>"), "label=\"Description\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_descriptionSet", (_descriptionSet ? "true" : "false")) ;
	}

	if(_baselineSet)
	{
		XMLOstream::Tag txml2(xst, "_baseline", _baseline, "label=\"Baseline\"");
	}
	else
	{
		XMLOstream::Tag txml2(xst, "_baseline", string("<null>"), "label=\"Baseline\"");
	}
	{
		XMLOstream::Tag txml2Set(xst, "_baselineSet", (_baselineSet ? "true" : "false")) ;
	}
}



// load the object from a row
int dbProcessor::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ;

	row.columnSet(offset + 0, _processorName, _processorNameSet) ;
	row.columnSet(offset + 1, _processorVersion, _processorVersionSet) ;
	row.columnSet(offset + 2, _description, _descriptionSet) ;
	row.columnSet(offset + 3, _baseline, _baselineSet) ;

	setFromDatabase() ;

	return offset + 4 ;
}



void dbProcessor::setProcessorName(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbProcessor::setProcessorName(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 32)
	{
		InvalidUse e("Error: dbProcessor::setProcessorName(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_processorNameSet || _processorName != v ) 
	{
		_processorName = v ;
		_processorNameSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbProcessor::getProcessorName(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _processorNameSet ;
	return _processorName ;
}


void dbProcessor::unsetProcessorName()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbProcessor::unsetProcessorName(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_processorNameSet == true)
		setModifiedFlag();
	_processorNameSet = false;

}
void dbProcessor::setProcessorVersion(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbProcessor::setProcessorVersion(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 8)
	{
		InvalidUse e("Error: dbProcessor::setProcessorVersion(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_processorVersionSet || _processorVersion != v ) 
	{
		_processorVersion = v ;
		_processorVersionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbProcessor::getProcessorVersion(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _processorVersionSet ;
	return _processorVersion ;
}


void dbProcessor::unsetProcessorVersion()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbProcessor::unsetProcessorVersion(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_processorVersionSet == true)
		setModifiedFlag();
	_processorVersionSet = false;

}


void dbProcessor::setDescription(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 64)
	{
		InvalidUse e("Error: dbProcessor::setDescription(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_descriptionSet || _description != v ) 
	{
		_description = v ;
		_descriptionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbProcessor::getDescription(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _descriptionSet ;
	return _description ;
}


void dbProcessor::unsetDescription()
{
	Lock lock(*this) ;
	if(_descriptionSet == true)
		setModifiedFlag();
	_descriptionSet = false;

}


void dbProcessor::setBaseline(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 16)
	{
		InvalidUse e("Error: dbProcessor::setBaseline(). String too long.") ;
		ACS_THROW(e) ;
	}
	
	if (!_baselineSet || _baseline != v ) 
	{
		_baseline = v ;
		_baselineSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbProcessor::getBaseline(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _baselineSet ;
	return _baseline ;
}


void dbProcessor::unsetBaseline()
{
	Lock lock(*this) ;
	if(_baselineSet == true)
		setModifiedFlag();
	_baselineSet = false;

}



// get the field names
string dbProcessor::getFields()
{
	string s ;
	s += getTable() + "." + "ProcessorName, ";
	s += getTable() + "." + "ProcessorVersion, ";
	s += getTable() + "." + "Description, " ;
	s += getTable() + "." + "Baseline" ;
	return s ;
}


// get the table name
string dbProcessor::getTable()
{
	return "T_Processors" ;
}


// get the order by clause
string dbProcessor::getOrderBy()
{
	return "ProcessorName, ProcessorVersion DESC" ;
}


void dbProcessor::writeTo(ostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_processorName = " << (_processorNameSet ? _processorName : string("<null>")) << endl 
		 << "_processorVersion = " << (_processorVersionSet ? _processorVersion : string("<null>")) << endl 
		 << "_description = " << (_descriptionSet ? _description : string("<null>")) << endl
		 << "_baseline = " << (_baselineSet ? _baseline : string("<null>")) << endl ;
}


void dbProcessor::writeTo(exostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_processorName = " << (_processorNameSet ? _processorName : string("<null>")) << endl 
		 << "_processorVersion = " << (_processorVersionSet ? _processorVersion : string("<null>")) << endl 
		 << "_description = " << (_descriptionSet ? _description : string("<null>")) << endl
		 << "_baseline = " << (_baselineSet ? _baseline : string("<null>")) << endl ;
}


