// PRQA S 1050 EOF
/*

	Copyright 2012-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod:  $

	$Id$

	$Author$

	$Log$
	Revision 7.0  2017/05/31 17:32:59  nicvac
	OPMAN-260: Need PDS DB schema PDS_12-04.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:03  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:31  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.2  2012/11/28 13:16:05  marpas
	work in proegress
	
	Revision 2.1  2012/11/19 22:51:15  marpas
	compile with PDS_OLD_SCHEMA to use old pds schema.
	dbReceptionRule and related Query class introduced
	
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbReceptionRule.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <File.h>
#include <FileGuard.h>
#include <Filterables.h>
#include <exException.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;

ACS_CLASS_DEFINE_DEBUG_LEVEL(dbReceptionRule)

// constructor
dbReceptionRule::dbReceptionRule(dbConnection &conn) : dbSmartPersistent(table(), conn)
{
}


// copy constructor
dbReceptionRule::dbReceptionRule(const dbReceptionRule &o):
	dbSmartPersistent(o)
{
}


dbReceptionRule::~dbReceptionRule() throw()
{
}


// operator =
dbReceptionRule &dbReceptionRule::operator=(const dbReceptionRule &o)
{
	Lock lt(*this) ; // PRQA S 3050 2
	Lock lo(o) ;

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


void dbReceptionRule::getTTParameters(ostream &theStream, dbConnection& conn) const 
{
    string tempFileName = File::tempname("/tmp/dbRecRuleParamFileTemp"); // PRQA S 3050
	// The temporary file will be deleted by the guard when exiting this method
	FileGuard theGuard (tempFileName);

	downloadFile("tt_parameters",tempFileName,conn) ;

    // Now the parameter file is downlaoded in tmp repository
	// transfer it into the stream

	ifstream theFile (tempFileName.c_str());

	// Assuming here that the parameter file is not an HUGE file!!
	size_t theFileSize = File::size(tempFileName); // PRQA S 3000

	char buffer[theFileSize];
	theFile.read(buffer, theFileSize); // PRQA S 3000 2
	theStream.write(buffer, theFileSize);

	theFile.close();

	// work complete !!
}

_ACS_END_NAMESPACE
