// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod:  $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.4  2016/04/28 09:50:34  marpas
	interface fixed for SMID type
	
	Revision 5.3  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.1  2014/12/11 12:18:22  marpas
	coding best practices and warning remotion
	
	Revision 4.0  2013/09/30 12:31:03  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:31  marfav
	dbSMactions now include inventory id pointers
	
	Revision 1.6  2013/04/30 13:31:43  marpas
	dbPersistent interface changed
	
	Revision 1.5  2013/04/17 17:37:24  marpas
	dbPersistent interface changed
	
	Revision 1.4  2012/02/14 12:52:50  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 1.3  2009/01/27 12:28:20  crivig
	added enddate field
	
	Revision 1.2  2008/10/20 15:47:09  crivig
	 bug fixed
	
	Revision 1.1  2008/10/20 09:38:07  crivig
	source code added
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbSMactions.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <SQLString.h>
#include <dbQuery.h>


using namespace acs ;
using namespace std ;

// constructor
dbSMactions::dbSMactions(dbConnection &conn) : dbSmartPersistent("t_SMactions", conn)
{
	dbSMactions::reset() ;
}


// copy constructor
dbSMactions::dbSMactions(const dbSMactions &o):
	dbSmartPersistent(o)
{
}


dbSMactions::~dbSMactions() throw()
{
}



dbPersistent *dbSMactions::clone() const
{
	return new dbSMactions(*this) ;
}


// operator =
dbSMactions &dbSMactions::operator=(const dbSMactions &o)
{
	Lock lock(*this) ; // PRQA S 3050 

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


string dbSMactions::className() const
{
	return staticClassName() ;
}


string dbSMactions::staticClassName()
{
	return "dbSMactions" ;
}



// export the class to stream
void dbSMactions::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbSMactions") ;
	dbPersistent::exportObj(s) ;
}





// import the class from a stream
void dbSMactions::importObj(rsResourceSet &s)
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbSMactions") ;
	dbSmartPersistent::importObj(s) ;
}




// export the class to XML stream
void dbSMactions::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ; // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbSMactions");
	dbSmartPersistent::exportXML(xst) ;
}


void dbSMactions::setSMId(IdType v, dbConnection &c)
{
	set<IdType>("smid",v, c) ;
}


dbPersistent::IdType dbSMactions::getSMId(bool &set, dbConnection &c) const // PRQA S 4214
{
	IdType v = 0 ; 
	
	get<IdType>("smid",v, set, c) ;

	return v ;
}


void dbSMactions::unsetSMId()
{
	unset("smid") ;
}

void dbSMactions::setPackageId(IdType v, dbConnection &c)
{
	set("packageid",v, c) ;
}


dbPersistent::IdType dbSMactions::getPackageId(bool &set, dbConnection &c) const // PRQA S 4214
{
	int v = 0 ; 
	
	get("packageid",v, set, c) ;

	return v ;
}


void dbSMactions::unsetPackageId()
{
	unset("packageid") ;
}


void dbSMactions::setOperation(const string & v, dbConnection &c)
{
	set<string>("operation",v, c) ;
}


string dbSMactions::getOperation(bool &set, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("operation",v, set, c) ;

	return v ;
}


void dbSMactions::unsetOperation()
{
	unset("operation") ;
}



void dbSMactions::setCreationDate(const DateTime & v, dbConnection &c)
{
	set<DateTime>("creationdate",v, c) ;
}


const DateTime dbSMactions::getCreationDate(bool &set, dbConnection &c) const // PRQA S 4214
{
	DateTime v ; 
	
	get<DateTime>("creationdate",v, set, c) ;

	return v ;
}


void dbSMactions::unsetCreationDate()
{
	unset("creationdate") ;
}

void dbSMactions::setEndDate(const DateTime & v, dbConnection &c)
{
	set<DateTime>("enddate",v, c) ;
}


const DateTime dbSMactions::getEndDate(bool &set, dbConnection &c) const // PRQA S 4214
{
	DateTime v ; 
	
	get<DateTime>("enddate",v, set, c) ;

	return v ;
}


void dbSMactions::unsetEndDate()
{
	unset("enddate") ;
}


void dbSMactions::setFileName(const string & v, dbConnection &c)
{
	set<string>("filename",v, c) ;
}


string dbSMactions::getFileName(bool &set, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("filename",v, set, c) ;

	return v ;
}


void dbSMactions::unsetFileName()
{
	unset("filename") ;
}

void dbSMactions::setFileVersion(const string & v, dbConnection &c)
{
	set<string>("fileversion",v, c) ;
}


string dbSMactions::getFileVersion(bool &set, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("fileversion",v, set, c) ;

	return v ;
}


void dbSMactions::unsetFileVersion()
{
	unset("fileversion") ;
}


void dbSMactions::setInventoryId(IdType id, dbConnection &c)
{
	set("inv_id",id, c) ;
}


dbPersistent::IdType dbSMactions::getInventoryId(bool &set, dbConnection &c) const // PRQA S 4214
{
	long long id = 0 ; 
	
	get("inv_id",id, set, c) ;

	return id ;
}


void dbSMactions::unsetInventoryId()
{
	unset("inv_id") ;
}

void dbSMactions::setUniqueId (const string& id, dbConnection &c)
{
    set<string>("unique_id",id, c) ;
}

string dbSMactions::getUniqueId (bool &set, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("unique_id",v, set, c) ;

	return v ;
}

void dbSMactions::unsetUniqueid()
{
    unset("unique_id");
}

// get the field names
string dbSMactions::getFields()
{
	string s ;
	s += getTable() + "." + "Id, ";
	s += getTable() + "." + "FileName, ";
	s += getTable() + "." + "FileVersion, ";
	s += getTable() + "." + "SMId, ";
	s += getTable() + "." + "Operation, ";
	s += getTable() + "." + "Parameter, ";
	s += getTable() + "." + "CreationDate, ";
	s += getTable() + "." + "PackageId, ";
	s += getTable() + "." + "EndDate, ";
	s += getTable() + "." + "Inv_Id, ";
	s += getTable() + "." + "Unique_Id ";
	return s ;
}


// get the table name
string dbSMactions::getTable()
{
	return "T_SMactions" ;
}


string dbSMactions::download(const string &path, dbConnection &conn) const 
{
	ostringstream os ;
	os << "SMactions_" <<  getId() ;
	downloadFile("parameter",path+"/"+os.str(), conn) ;
	return os.str() ;
}
	
