// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod:  $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.4  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.3  2016/04/15 10:13:44  marpas
	coding best practices application in progress
	QA warning fixing in progress
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:03  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:31  marfav
	dbSMactions now include inventory id pointers
	
	Revision 1.4  2012/02/14 12:52:50  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 1.3  2009/01/27 12:28:50  crivig
	added functions to set/get start/stop date
	
	Revision 1.2  2008/10/21 08:15:35  crivig
	bug fixed
	
	Revision 1.1  2008/10/20 09:38:07  crivig
	source code added
	
*/

// This file is automatically generated by dbGenerator tool

#include <dbSMqueue.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <SQLString.h>
#include <dbQuery.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;

ACS_CLASS_DEFINE_DEBUG_LEVEL(dbSMqueue)

// constructor
dbSMqueue::dbSMqueue(dbConnection &conn) : dbSmartPersistent("t_SMqueue", conn)
{
}


// copy constructor
dbSMqueue::dbSMqueue(const dbSMqueue &o):
	dbSmartPersistent(o)
{
}


dbSMqueue::~dbSMqueue() throw()
{
}



dbPersistent *dbSMqueue::clone() const
{
	return new dbSMqueue(*this) ;
}


// operator =
dbSMqueue &dbSMqueue::operator=(const dbSMqueue &o)
{
	Lock lock(*this) ; // PRQA S 3050

	if(this != &o)
	{
		dbSmartPersistent::operator=(o) ;
	}
	return *this ;
}


string dbSMqueue::className() const
{
	return staticClassName() ;
}


string dbSMqueue::staticClassName()
{
	return "dbSMqueue" ;
}


// export the class to stream
void dbSMqueue::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbSMqueue") ;
	dbPersistent::exportObj(s) ;
}





// import the class from a stream
void dbSMqueue::importObj(rsResourceSet &s)
{
	Lock lock(*this) ; // PRQA S 3050

	rsPushNSpace nsp(s,"dbSMqueue") ;
	dbSmartPersistent::importObj(s) ;
}




// export the class to XML stream
void dbSMqueue::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ; // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbSMqueue");
	dbSmartPersistent::exportXML(xst) ;
}


void dbSMqueue::setSMId(int v, dbConnection &c)
{
	set<int>("smid",v,c) ;
}


int dbSMqueue::getSMId(bool &s, dbConnection &c) const// PRQA S 4214
{
	int v = 0 ; 
	
	get<int>("smid",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetSMId()
{
	unset("smid") ;
}

void dbSMqueue::setPackageId(IdType v, dbConnection &c)
{
	set("packageid",v,c) ;
}


dbPersistent::IdType dbSMqueue::getPackageId(bool &s, dbConnection &c) const // PRQA S 4214
{
	IdType v = 0 ; 
	
	get("packageid",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetPackageId()
{
	unset("packageid") ;
}


void dbSMqueue::setOperation(const string & v, dbConnection &c)
{
	set<string>("operation",v,c) ;
}


string dbSMqueue::getOperation(bool &s, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("operation",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetOperation()
{
	unset("operation") ;
}


void dbSMqueue::setCreationDate(const DateTime & v, dbConnection &c)
{
	set<DateTime>("creationdate",v,c) ;
}


const DateTime dbSMqueue::getCreationDate(bool &s, dbConnection &c) const // PRQA S 4214
{
	DateTime v ; 
	
	get<DateTime>("creationdate",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetCreationDate()
{
	unset("creationdate") ;
}

void dbSMqueue::setStartDate(const DateTime & v, dbConnection &c)
{
	set<DateTime>("startdate",v,c) ;
}


const DateTime dbSMqueue::getStartDate(bool &s, dbConnection &c) const // PRQA S 4214
{
	DateTime v ; 
	
	get<DateTime>("startdate",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetStartDate()
{
	unset("startdate") ;
}

void dbSMqueue::setStopDate(const DateTime & v, dbConnection &c)
{
	set<DateTime>("stopdate",v,c) ;
}


const DateTime  dbSMqueue::getStopDate(bool &s, dbConnection &c) const // PRQA S 4214
{
	DateTime v ; 
	
	get<DateTime>("stopdate",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetStopDate()
{
	unset("stopdate") ;
}


void dbSMqueue::setPackageFileName(const string & v, dbConnection &c)
{
	set<string>("packagefilename",v,c) ;
}


string dbSMqueue::getPackageFileName(bool &s, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("packagefilename",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetPackageFileName()
{
	unset("packagefilename") ;
}

void dbSMqueue::setStatus(const string & v, dbConnection &c)
{
	set<string>("status",v,c) ;
}


string dbSMqueue::getStatus(bool &s, dbConnection &c) const // PRQA S 4214
{
	string v ; 
	
	get<string>("status",v, s, c) ;

	return v ;
}


void dbSMqueue::unsetStatus()
{
	unset("status") ;
}


// get the field names
string dbSMqueue::getFields(dbConnection &conn)
{
    return dbSchemaMetaDataProvider::instance(conn.getKey()) -> getFields( getTable(), conn ) ;
}

// get the field names
string dbSMqueue::getFields()
{
	string s ;
	s += getTable() + "." + "PackageId, ";
	s += getTable() + "." + "Status, ";
	s += getTable() + "." + "Operation, ";
	s += getTable() + "." + "SMId, ";
	s += getTable() + "." + "CreationDate, ";
	s += getTable() + "." + "Parameter, ";
	s += getTable() + "." + "StartDate, ";
	s += getTable() + "." + "StopDate, ";
	s += getTable() + "." + "PackageFileName ";
	return s ;
}


// get the table name
string dbSMqueue::getTable()
{
	return "T_SMqueue" ;
}


string dbSMqueue::download(const string &path, dbConnection &conn) const  // PRQA S 4214
{
	ostringstream os ;
    bool null = false ;
	os << "SMqueue_" << getPackageId(null, conn) ;
	downloadFile("parameter",path+"/"+os.str(), conn) ;
	return os.str() ;
}
	
_ACS_END_NAMESPACE
