// PRQA S 1050 EOF
/*

	Copyright 1995-2016, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: $

	$Id$

	$Author$

	$Log$
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.6  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.5  2016/04/18 15:22:52  marpas
	coding best practices application in progress
	
	Revision 5.4  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.3  2016/04/15 10:13:44  marpas
	coding best practices application in progress
	QA warning fixing in progress
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:04  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:31  marfav
	dbSMactions now include inventory id pointers
	
	Revision 1.4  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 1.3  2012/02/14 12:52:51  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 1.2  2009/01/27 12:28:50  crivig
	added functions to set/get start/stop date
	
	Revision 1.1  2008/10/20 09:38:07  crivig
	source code added
	
	
	
*/

// This file is automatically generated by dbGenerator tool

#ifndef _dbSMqueue_H_
#define _dbSMqueue_H_

#include <exException.h>
#include <dbSmartPersistent.h>
#include <DateTime.h>

#include <string>

_ACS_BEGIN_NAMESPACE(acs)

class dbCryosatFactory ;

class dbRow ;
class rsResourceSet ;
class XMLOstream ;


//
//
//
// class dbSMqueue
//
//
//
class dbSMqueue : public dbSmartPersistent // PRQA S 2109, 2153
{
public:
	friend class dbCryosatFactory ; // PRQA S 2107

	virtual ~dbSMqueue() throw() ;
	dbSMqueue &operator=(const dbSMqueue &) ; // operator =

	static  std::string staticClassName() ;
	virtual dbPersistent *clone() const ; // PRQA S 2502

	// inherited from dbPersistent
	virtual std::string className() const ;

	virtual void exportObj(rsResourceSet &) const ; // export the class to rsResourceSet
	virtual void importObj(rsResourceSet &)  ; // import the class from a rsResourceSet
	virtual void exportXML(XMLOstream &) const ; // export the class to XML stream

	void setSMId(int, dbConnection&) ;
	int getSMId(bool &, dbConnection&) const ;
	void unsetSMId();

	void setPackageId(IdType, dbConnection&) ;
	dbPersistent::IdType getPackageId(bool &, dbConnection&) const ;
	void unsetPackageId();

	void setPackageFileName(const std::string &, dbConnection&) ;
	std::string getPackageFileName(bool &, dbConnection&) const ;
	void unsetPackageFileName();

	void setStatus(const std::string &, dbConnection&) ;
	std::string getStatus(bool &, dbConnection&) const ;
	void unsetStatus();

	void setOperation(const std::string &, dbConnection&) ;
	std::string getOperation(bool &, dbConnection&) const ;
	void unsetOperation();

	void setCreationDate(const DateTime &, dbConnection&) ;
	const DateTime getCreationDate(bool &, dbConnection&) const ;
	void unsetCreationDate();

	void setStartDate(const DateTime &, dbConnection&) ;
	const DateTime getStartDate(bool &, dbConnection&) const ;
	void unsetStartDate();

	void setStopDate(const DateTime &, dbConnection&) ;
	const DateTime getStopDate(bool &, dbConnection&) const ;
	void unsetStopDate();

	static std::string getFields(dbConnection &) ;
	static std::string getFields() ;
	static std::string getTable() ;

	std::string download(const std::string &path, dbConnection &) const ;
	
protected:
	explicit dbSMqueue(dbConnection &) ;
	dbSMqueue(const dbSMqueue &) ;
private:
	dbSMqueue() ; // not implemented


private:
	ACS_CLASS_DECLARE_DEBUG_LEVEL(dbSMqueue)
} ;


_ACS_END_NAMESPACE

#endif // _dbSMqueue_H_
