// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/26 10:06:09  damdec
	Compilation warnings fixed.
	
	Revision 6.0  2016/07/07 13:44:05  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/05/10 21:19:54  danalt
	use of ACS_THROW and ACS_COND_THROW
	
	Revision 5.4  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.0  2013/09/30 12:31:04  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:32  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.9  2013/04/12 12:14:39  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.8  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.7  2013/02/22 11:58:56  marpas
	using StringUtils::findNoCase
	
	Revision 2.6  2012/02/14 12:52:51  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.5  2011/03/02 18:47:15  marpas
	serial 8 support
	
	Revision 2.4  2010/03/05 15:09:11  enrcar
	EC:: Oracle11 dialect supported whenever no specific code was required (was: Postgres8 || Informix9)
	
	Revision 2.3  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.2  2006/06/09 12:45:59  giucas
	Fixed syntax error in update query.
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.32  2005/06/15 07:44:50  integrator
	multiple storage manager implemented
	
	Revision 1.31  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.30  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.29  2004/10/04 15:13:53  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.28  2004/09/01 17:22:13  marpas
	*** empty log message ***
	
	Revision 1.27  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.26  2004/07/07 10:34:33  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.25  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.24  2004/04/16 12:49:34  paoscu
	Bug fixed in Lock usage
	
	Revision 1.23  2004/04/13 16:57:09  paoscu
	ThreadSafe::Lock used.
	clobe() method added.
	
	Revision 1.22  2004/02/04 10:12:36  paoscu
	Library generated again. dbPersistent interface changed.
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbUserType.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>



using namespace acs ;
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbUserType)

// constructor
dbUserType::dbUserType():
	_userType(),
	_userTypeSet(false),
	_description(),
	_descriptionSet(false)
{
	dbPersistent::reset() ;
}


// copy constructor
dbUserType::dbUserType(const dbUserType &o):
	dbPersistent(o),
	_userType(o._userType),
	_userTypeSet(o._userTypeSet),
	_description(o._description),
	_descriptionSet(o._descriptionSet)
{
}


dbUserType::~dbUserType() throw()
{
}



dbPersistent *dbUserType::clone() const
{
	return new dbUserType(*this) ;
}

// operator =
dbUserType &dbUserType::operator=(const dbUserType &o)
{
	Lock lock(*this) ;

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_userType=o._userType;
		_userTypeSet=o._userTypeSet;
		_description=o._description;
		_descriptionSet=o._descriptionSet;
	}
	return *this ;
}


string dbUserType::className() const
{
	return staticClassName() ;
}


string dbUserType::staticClassName()
{
	return "dbUserType" ;
}



// initialize the class
void dbUserType::reset()
{
	Lock lock(*this) ;

	// reset dbPersistent
	dbPersistent::reset() ;
	_userType="" ;
	_userTypeSet=false ;
	_description="" ;
	_descriptionSet=false ;
}


// save the data in database
dbPersistent::IdType dbUserType::save(dbConnection &conn)
{
	Lock lock(*this) ;

	if (!isModified())
		return 0 ; 

	if (isFromDatabase()) 
	{
		InvalidUse e("Error: dbUserType::save(). Use the method update() instead of save().") ;
		ACS_THROW(e) ;
	}
	if(!_userTypeSet) 
	{
		InvalidUse e("Mandatory field \"User Type\" must be set.") ;
		ACS_THROW(e) ;
	}
	if(!_descriptionSet) 
	{
		InvalidUse e("Mandatory field \"Description\" must be set.") ;
		ACS_THROW(e) ;
	}

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "INSERT INTO " + getTable() + " (" ;
		queryString += "UserType" ;
		queryString += ", Description" ;
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey, _userType) ;
		queryString +=	", " + db::toSQL(dbKey, _description) ;
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString ) ;
	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbUserType::save") ;

	if (!query.execForStatus())
	{
		dbQuery::QueryExecuteException e(string("Query Execution error: Command : ")
		+ string(queryString)
		+ string(" Error : ")
		+ string(query.errorString())) ;
		ACS_THROW (e) ;
	}

	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbUserType::load(dbConnection &conn , IdType id)
{
		
	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB ) ;
	Lock lock(*this) ;

	dbUserType tempRecord(*this); //store current record.


	reset() ; 

    const string &dbKey = conn.getKey() ;

	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	getFields() ;
		queryString += " FROM " + getTable() ;
		queryString += " WHERE UserType " ;
		if(tempRecord._userTypeSet)
			queryString +=	string("= ") + db::toSQL(dbKey, tempRecord._userType)  ;
		else
			queryString +=	" IS NULL" ;
		string getOrderByString(getOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos)
				queryString += getOrderByString ;
			else
				queryString += " ORDER BY " + getOrderByString ;
		}

	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbUserType::load") ;
	dbRow row(dbKey) ;
	dbSet setQ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString ) ;

	query.execForSet(setQ) ;
    if (setQ.size() > 1) // it should not occur
    {
        ACS_THROW(InvalidUse("Unexpected query result dimension: it should return just one row"));
    }
    else
    {
		if ( not setQ.getNextRow(row) )
        {
        	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "No " << getTable() << " record found ");
			*this = tempRecord;  //Nothing found: restore previuos situation.
			return false ;
        }
	}

	loadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

    ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "Dump: \"" << *this);

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbUserType::update(dbConnection &conn)
{
	Lock lock(*this) ;

	if (!isFromDatabase())
	{
		ObjectNotLoaded ex("Error: dbUserType::update(). Use the method save() instead of update().") ; 
		ACS_THROW(ex)
	}

	if (!isModified())
		return 0 ; 

    const string &dbKey = conn.getKey() ;
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = string("UPDATE ") + getTable() + " SET " ; 
		queryString += "Description= " + db::toSQL(dbKey, _description)  ;
		queryString += " WHERE " ;
		queryString += "UserType " ;
		queryString +=	string("= ") + db::toSQL(dbKey, _userType);

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString ) ;

	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbUserType::update") ;

	query.execForStatus() ;


	resetModifiedFlag() ;
	return 0 ;

}


// remove the class from the database
dbPersistent::IdType dbUserType::remove(dbConnection &conn)
{
	Lock lock(*this) ;

	string queryString ;
    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "DELETE FROM " + getTable() ;
		queryString += " WHERE " ;
		queryString += "UserType " ;
		if(_userTypeSet)
			queryString +=	string("= ") + db::toSQL(dbKey, _userType);
		else
			queryString +=	"IS NULL" ;

	} else {
		ACS_THROW( exIllegalValueException(string("Unknown db: ")+dialectName ));
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;

	dbQuery query(conn, sqlString, "dbUserType::remove") ;

	query.execForStatus() ;

	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbUserType::validate() const
{
	Lock lock(*this) ;

	return true;
}



// export the class to stream
void dbUserType::exportObj(rsResourceSet &s) const
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbUserType") ;
	dbPersistent::exportObj(s) ;
	if(_userTypeSet)
	{
		s.setValue("_userType",_userType) ;
	}
	s.setValue("_userTypeSet",_userTypeSet) ;
	if(_descriptionSet)
	{
		s.setValue("_description",_description) ;
	}
	s.setValue("_descriptionSet",_descriptionSet) ;
}


// import the class from a stream
void dbUserType::importObj(rsResourceSet &s)
{
	Lock lock(*this) ;

	rsPushNSpace nsp(s,"dbUserType") ;
	dbPersistent::importObj(s) ;
	s.getValue("_userTypeSet",_userTypeSet) ;
	if(_userTypeSet)
	{
		s.getValue("_userType",_userType) ;
	}
	else
		_userType = "" ;
	s.getValue("_descriptionSet",_descriptionSet) ;
	if(_descriptionSet)
	{
		s.getValue("_description",_description) ;
	}
	else
		_description = "" ;
}


// export the class to XML stream
void dbUserType::exportXML(XMLOstream &xst) const
{
	Lock lock(*this) ;

	XMLOstream::Tag txml(xst, "dbUserType");
	dbPersistent::exportXML(xst) ;
	if(_userTypeSet)
	{
	XMLOstream::Tag txml0(xst, "_userType", _userType, "label=\"User Type\"");
	}
	else
	{
	XMLOstream::Tag txml0(xst, "_userType", string("<null>"), "label=\"User Type\"");
	}
	{
	XMLOstream::Tag txml0Set(xst, "_userTypeSet", (_userTypeSet ? "true" : "false")) ;
	}
	if(_descriptionSet)
	{
	XMLOstream::Tag txml1(xst, "_description", _description, "label=\"Description\"");
	}
	else
	{
	XMLOstream::Tag txml1(xst, "_description", string("<null>"), "label=\"Description\"");
	}
	{
	XMLOstream::Tag txml1Set(xst, "_descriptionSet", (_descriptionSet ? "true" : "false")) ;
	}
}

// load the object from a row
int dbUserType::loadRow(const dbRow &row, int offset)
{
	Lock lock(*this) ;

	row.columnSet(offset + 0, _userType, _userTypeSet) ;
	row.columnSet(offset + 1, _description, _descriptionSet) ;


	setFromDatabase() ;

	return offset + 2 ;
}


void dbUserType::setUserType(const string &v)
{
	Lock lock(*this) ;

	if (isFromDatabase())
	{
		InvalidUse e("Error: dbUserType::setUserType(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	if (v.size() > 12)
	{
		InvalidUse e("Error: dbUserType::setUserType(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_userTypeSet || _userType != v ) 
	{
		_userType = v ;
		_userTypeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUserType::getUserType(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _userTypeSet ;
	return _userType ;
}


void dbUserType::unsetUserType()
{
	if (isFromDatabase())
	{
		InvalidUse e("Error: dbUserType::unsetUserType(). Primary Key is from Database.") ;
		ACS_THROW(e) ;
	}

	Lock lock(*this) ;
	if(_userTypeSet == true)
		setModifiedFlag();
	_userTypeSet = false;

}
void dbUserType::setDescription(const string &v)
{
	Lock lock(*this) ;

	if (v.size() > 64)
	{
		InvalidUse e("Error: dbUserType::setDescription(). String too long.") ;
		ACS_THROW(e) ;
	}

	if (!_descriptionSet || _description != v ) 
	{
		_description = v ;
		_descriptionSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUserType::getDescription(bool *set) const
{
	Lock lock(*this) ;

	if (set)
		*set = _descriptionSet ;
	return _description ;
}


void dbUserType::unsetDescription()
{
	Lock lock(*this) ;
	if(_descriptionSet == true)
		setModifiedFlag();
	_descriptionSet = false;

}
// get the field names
string dbUserType::getFields()
{
	string s ;
	s += getTable() + "." + "UserType, ";
	s += getTable() + "." + "Description" ;
	return s ;
}


// get the table name
string dbUserType::getTable()
{
	return "T_UserTypes" ;
}


// get the order by clause
string dbUserType::getOrderBy()
{
	return "" ;
}


void dbUserType::writeTo(ostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_userType = " << (_userTypeSet ? _userType : string("<null>")) << endl 
		 << "_description = " << (_descriptionSet ? _description : string("<null>")) << endl  ;
}


void dbUserType::writeTo(exostream &o) const
{
	Lock lock(*this) ;

	o
		 << "_userType = " << (_userTypeSet ? _userType : string("<null>")) << endl 
		 << "_description = " << (_descriptionSet ? _description : string("<null>")) << endl  ;
}


