// PRQA S 1050 EOF
/*

	Copyright 1995-2021, Advanced Computer Systems , Inc.
	Via Della Bufalotta, 378 - 00139 Roma - Italy
	http://www.acsys.it

	All Rights Reserved.

	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
	the contents of this file may not be disclosed to third parties, copied or
	duplicated in any form, in whole or in part, without the prior written
	permission of Advanced Computer Systems, Inc.

	$Prod: A.C.S. Db Cryosat Library $

	$Id$

	$Author$

	$Log$
	Revision 6.1  2016/07/26 10:04:32  damdec
	Deprecated execOneRow replaced.
	
	Revision 6.0  2016/07/07 13:44:04  damdec
	CSGACQ-82: special queries modified to be compatible with Oracle
	
	Revision 5.5  2016/05/02 17:27:08  marpas
	adopting new convenience macros from dbPersistent
	code rationalization
	coding best practices applied
	
	Revision 5.4  2016/04/19 13:53:47  marpas
	coding best practice application in progress
	useless virtual filedName method removed
	
	Revision 5.3  2016/04/15 14:37:04  marpas
	coding best practices application in progress
	
	Revision 5.2  2016/04/11 13:28:14  marpas
	adopting new db interfaces
	coding best practices application in progress
	
	Revision 5.1  2016/03/26 21:42:50  marpas
	using new db I/F
	
	Revision 5.0  2015/02/17 11:25:26  marfav
	Field unique_id added to table t_smactions
	
	Revision 4.1  2014/05/26 11:39:45  marpas
	dbConv casted to avoid problem with new libXMLResources templates for tags
	
	Revision 4.0  2013/09/30 12:31:04  marpas
	the following classes have been removed:
	dbDistributionPolicy
	dbDistributionPolicyQuery
	dbIORepository
	dbIORepositoryQuery
	dbReceptionPolicy
	dbReceptionPolicyQuery
	
	Revision 3.0  2013/09/19 14:57:32  marfav
	dbSMactions now include inventory id pointers
	
	Revision 2.12  2013/05/14 19:04:51  marpas
	SQLDialectFactory::sqlDialect() mthods now requires db connection key
	
	Revision 2.11  2013/04/12 12:14:39  marpas
	SQLDialectFactory::dialectName() needs a db connection key
	
	Revision 2.10  2013/03/29 19:51:30  marpas
	removing html related functions
	
	Revision 2.9  2013/02/22 11:58:55  marpas
	using StringUtils::findNoCase
	
	Revision 2.8  2012/02/14 12:52:51  marpas
	 refactoring and introducing dbInventory::uniqueId
	
	Revision 2.7  2011/03/02 18:47:15  marpas
	serial 8 support
	
	Revision 2.6  2010/03/05 15:05:37  enrcar
	EC:: Reserved column MODE handled
	
	Revision 2.5  2009/06/16 11:09:18  marpas
	VEN-1235 development: usermode for reception policies and distribution policies added
	
	Revision 2.4  2008/09/23 08:27:38  crivig
	porting to postgres8
	
	Revision 2.3  2007/03/19 11:29:09  marpas
	ADM work in progress
	
	Revision 2.2  2006/06/09 12:45:59  giucas
	Fixed syntax error in update query.
	
	Revision 2.1  2006/06/09 11:53:21  giucas
	Update method fixed.
	
	Revision 2.0  2006/02/28 09:09:36  marpas
	Exception 2.1 I/F adopted
	
	Revision 1.37  2005/06/15 07:44:50  integrator
	multiple storage manager implemented
	
	Revision 1.36  2005/03/09 18:03:24  marpas
	some messages fixed
	namespaces fixed
	
	Revision 1.35  2005/03/04 22:49:07  marpas
	dbWaitingOrder and dbWaitingOrderQuery classes  and their tests added , db_values script updated accordingly
	
	Revision 1.34  2004/10/04 15:13:53  ivafam
	When set orderBy control if orderBySQLDString contain already clause "ORDER BY"
	
	Revision 1.33  2004/09/01 17:22:13  marpas
	*** empty log message ***
	
	Revision 1.32  2004/07/19 17:50:59  paoscu
	dbEMailAddress and dbEMailAddressQuery removed
	dbUser has set and get EMAIL ADDRESS
	
	Revision 1.31  2004/07/13 15:15:44  paoscu
	using namespace std no longer in includes
	exDbPersistent is an abstract class
	
	Revision 1.30  2004/07/07 10:34:33  paoscu
	dbPersistent I/F chnaged
	
	Revision 1.29  2004/05/03 14:55:34  paoscu
	Paramer "id" removed in method "remove"
	
	Revision 1.28  2004/04/19 15:34:52  paoscu
	Better name for methods.
	ACE include removed
		

*/

// This file is automatically generated by dbGenerator tool

#include <dbUser.h>
#include <dbQuery.h>
#include <dbRow.h>
#include <dbConv.h>
#include <dbSet.h>
#include <dbConnectionPool.h>
#include <Transaction.h>
#include <rsResourceSet.h>
#include <rsPushNSpace.h>
#include <sstream>
#include <XMLOstream.h>


_ACS_BEGIN_NAMESPACE(acs)
using namespace std ;



ACS_CLASS_DEFINE_DEBUG_LEVEL(dbUser)

// constructor
dbUser::dbUser() :
	dbPersistent(),
	_userId() ,
	_userIdSet() ,
	_firstName() ,
	_firstNameSet() ,
	_lastName() ,
	_lastNameSet() ,
	_title() ,
	_titleSet() ,
	_organization() ,
	_organizationSet() ,
	_department() ,
	_departmentSet() ,
	_fax() ,
	_faxSet() ,
	_phone() ,
	_phoneSet() ,
	_postalAddress() ,
	_postalAddressSet() ,
	_projectAndProcessing() ,
	_projectAndProcessingSet() ,
	_packageRequired() ,
	_packageRequiredSet() ,
	_compressPackage() ,
	_compressPackageSet() ,
	_compressionMode() ,
	_compressionModeSet() ,
	_userType() ,
	_userTypeSet() ,
	_packageMaxSize() ,
	_packageMaxSizeSet() ,
	_progMediaNumber() ,
	_progMediaNumberSet(),
	_eMailAddress() ,
	_eMailAddressSet(),
	_allQualified() ,
	_allQualifiedSet(),
	_mode(),
	_modeSet() 
{
}


// copy constructor
dbUser::dbUser(const dbUser &o):
	dbPersistent(o),
	_userId(o._userId) ,
	_userIdSet(o._userIdSet) ,
	_firstName(o._firstName) ,
	_firstNameSet(o._firstNameSet) ,
	_lastName(o._lastName) ,
	_lastNameSet(o._lastNameSet) ,
	_title(o._title) ,
	_titleSet(o._titleSet) ,
	_organization(o._organization) ,
	_organizationSet(o._organizationSet) ,
	_department(o._department) ,
	_departmentSet(o._departmentSet) ,
	_fax(o._fax) ,
	_faxSet(o._faxSet) ,
	_phone(o._phone) ,
	_phoneSet(o._phoneSet) ,
	_postalAddress(o._postalAddress) ,
	_postalAddressSet(o._postalAddressSet) ,
	_projectAndProcessing(o._projectAndProcessing) ,
	_projectAndProcessingSet(o._projectAndProcessingSet) ,
	_packageRequired(o._packageRequired) ,
	_packageRequiredSet(o._packageRequiredSet) ,
	_compressPackage(o._compressPackage) ,
	_compressPackageSet(o._compressPackageSet) ,
	_compressionMode(o._compressionMode) ,
	_compressionModeSet(o._compressionModeSet) ,
	_userType(o._userType) ,
	_userTypeSet(o._userTypeSet) ,
	_packageMaxSize(o._packageMaxSize) ,
	_packageMaxSizeSet(o._packageMaxSizeSet) ,
	_progMediaNumber(o._progMediaNumber) ,
	_progMediaNumberSet(o._progMediaNumberSet),
	_eMailAddress(o._eMailAddress) ,
	_eMailAddressSet(o._eMailAddressSet),
	_allQualified(o._allQualified) ,
	_allQualifiedSet(o._allQualifiedSet),
	_mode(o._mode),
	_modeSet(o._modeSet) 

{
}


dbUser::~dbUser() throw()
{
}


// operator =
dbUser &dbUser::operator=(const dbUser &o)
{
	Lock guard(*this); // PRQA S 3050

	if(this != &o)
	{
		dbPersistent::operator=(o) ;
		_userId=o._userId;
		_userIdSet=o._userIdSet;
		_firstName=o._firstName;
		_firstNameSet=o._firstNameSet;
		_lastName=o._lastName;
		_lastNameSet=o._lastNameSet;
		_title=o._title;
		_titleSet=o._titleSet;
		_organization=o._organization;
		_organizationSet=o._organizationSet;
		_department=o._department;
		_departmentSet=o._departmentSet;
		_fax=o._fax;
		_faxSet=o._faxSet;
		_phone=o._phone;
		_phoneSet=o._phoneSet;
		_postalAddress=o._postalAddress;
		_postalAddressSet=o._postalAddressSet;
		_projectAndProcessing=o._projectAndProcessing;
		_projectAndProcessingSet=o._projectAndProcessingSet;
		_packageRequired=o._packageRequired;
		_packageRequiredSet=o._packageRequiredSet;
		_compressPackage=o._compressPackage;
		_compressPackageSet=o._compressPackageSet;
		_compressionMode=o._compressionMode;
		_compressionModeSet=o._compressionModeSet;
		_userType=o._userType;
		_userTypeSet=o._userTypeSet;
		_packageMaxSize=o._packageMaxSize;
		_packageMaxSizeSet=o._packageMaxSizeSet;
		_progMediaNumber=o._progMediaNumber;
		_progMediaNumberSet=o._progMediaNumberSet;
		_eMailAddress=o._eMailAddress;
		_eMailAddressSet=o._eMailAddressSet;
		_allQualified=o._allQualified;
		_allQualifiedSet=o._allQualifiedSet;
		_mode=o._mode;
		_modeSet=o._modeSet;
	}
	return *this ;
}


dbPersistent *dbUser::clone() const
{
	Lock guard(*this); // PRQA S 3050

	return new dbUser(*this) ;
}


string dbUser::className() const
{
	return staticClassName() ;
}


string dbUser::staticClassName()
{
	return "dbUser" ;
}



// initialize the class
void dbUser::reset()
{
	Lock guard(*this); // PRQA S 3050

	// reset dbPersistent
	dbPersistent::reset() ;
	_userId="" ;
	_userIdSet=false ;
	_firstName="" ;
	_firstNameSet=false ;
	_lastName="" ;
	_lastNameSet=false ;
	_title="" ;
	_titleSet=false ;
	_organization="" ;
	_organizationSet=false ;
	_department="" ;
	_departmentSet=false ;
	_fax="" ;
	_faxSet=false ;
	_phone="" ;
	_phoneSet=false ;
	_postalAddress="" ;
	_postalAddressSet=false ;
	_projectAndProcessing="" ;
	_projectAndProcessingSet=false ;
	_packageRequired=false ;
	_packageRequiredSet=false ;
	_compressPackage=false ;
	_compressPackageSet=false ;
	_compressionMode="" ;
	_compressionModeSet=false ;
	_userType="" ;
	_userTypeSet=false ;
	_packageMaxSize=0 ;
	_packageMaxSizeSet=false ;
	_progMediaNumber=0 ;
	_progMediaNumberSet=false ;
	_eMailAddress="" ;
	_eMailAddressSet=false ;
	_allQualified=false ;
	_allQualifiedSet=false ;
	_mode=0 ;
	_modeSet=false ;
}


// save the data in database
dbPersistent::IdType dbUser::save(dbConnection &conn) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	if (!isModified()) { return 0 ; }

	if (isFromDatabase()) 
	{
		ACS_THROW(InvalidUse("Use the method update() instead of save().")) ; // PRQA S 3081
	}

	if(!_userIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Id\" must be set.")) ; // PRQA S 3081
	}
	if(!_packageRequiredSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Package Required\" must be set.")) ; // PRQA S 3081
	}
	if(!_userTypeSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Type\" must be set.")) ; // PRQA S 3081
	}
	if(!_progMediaNumberSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Last Media\" must be set.")) ; // PRQA S 3081
	}

    db::Transaction transaction(conn) ;
    transaction.begin_work("dbUser_SAVE") ;
	conn.addStateWrapper(*this) ;

	string queryString ;
    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {

		queryString = "INSERT INTO T_Users (" ;
		queryString += "UserId" ;
		if(_firstNameSet) {
			queryString += ", FirstName" ;
        }
		if(_lastNameSet) {
			queryString += ", LastName" ;
        }
		if(_titleSet) {
			queryString += ", Title" ;
        }
		if(_organizationSet) {
			queryString += ", Organization" ;
        }
		if(_departmentSet) {
			queryString += ", Department" ;
        }
		if(_faxSet) {
			queryString += ", Fax" ;
        }
		if(_phoneSet) {
			queryString += ", Phone" ;
        }
		if(_postalAddressSet) {
			queryString += ", PostalAddress" ;
        }
		if(_projectAndProcessingSet) {
			queryString += ", ProjectAndProcessing" ;
        }
		queryString += ", PackageRequired" ;
		if(_compressPackageSet) {
			queryString += ", CompressPackage" ;
        }
		if(_compressionModeSet) {
			queryString += ", CompressionMode" ;
        }
		queryString += ", UserType" ;
		if(_packageMaxSizeSet) {
			queryString += ", PackageMaxSize" ;
        }
		queryString += ", ProgMediaNumber" ;
		if(_eMailAddressSet) {
			queryString += ", EMailAddress" ;
        }
		if(_allQualifiedSet) {
			queryString += ", AllQualified" ;
        }
		if(_modeSet) {
			queryString += ", " + (SQLDialectFactory::sqlDialect(dbKey).translateColumnName("Mode")) ;
        }
		queryString +=	") VALUES ( " ;
		queryString +=	db::toSQL(dbKey, _userId) ;
		if(_firstNameSet) {
			queryString +=	", " + db::toSQL(dbKey, _firstName) ;
        }
		if(_lastNameSet) {
			queryString +=	", " + db::toSQL(dbKey, _lastName) ;
        }
		if(_titleSet) {
			queryString +=	", " + db::toSQL(dbKey, _title) ;
        }
		if(_organizationSet) {
			queryString +=	", " + db::toSQL(dbKey, _organization) ;
        }
		if(_departmentSet) {
			queryString +=	", " + db::toSQL(dbKey, _department) ;
        }
		if(_faxSet) {
			queryString +=	", " + db::toSQL(dbKey, _fax) ;
        }
		if(_phoneSet) {
			queryString +=	", " + db::toSQL(dbKey, _phone) ;
        }
		if(_postalAddressSet) {
			queryString +=	", " + db::toSQL(dbKey, _postalAddress) ;
        }
		if(_projectAndProcessingSet) {
			queryString +=	", " + db::toSQL(dbKey, _projectAndProcessing) ;
        }
		queryString +=	", " + db::toSQL(dbKey, _packageRequired) ;
		if(_compressPackageSet) {
			queryString +=	", " +db::toSQL(dbKey, _compressPackage) ;
        }
		if(_compressionModeSet) {
			queryString +=	", " + db::toSQL(dbKey, _compressionMode) ;
        }
		queryString +=	", " + db::toSQL(dbKey, _userType) ;
		if(_packageMaxSizeSet) {
			queryString +=	", " + db::toSQL(dbKey, _packageMaxSize) ;
        }
		queryString +=	", " + db::toSQL(dbKey, _progMediaNumber) ;
		if(_eMailAddressSet) {
			queryString +=	", " + db::toSQL(dbKey, _eMailAddress) ;
        }
		if(_allQualifiedSet) {
			queryString +=	", " + db::toSQL(dbKey, _allQualified) ;
        }
		if(_modeSet) {
			queryString +=	", " + db::toSQL(dbKey, _mode) ;
        }
		queryString +=	") " ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL command : " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbUser::save") ;

	if (!query.execForStatus())
	{
			ACS_THROW(dbQuery::QueryExecuteException("Query Execution error: Command : " // PRQA S 3081
			+ queryString
			+ " Error : "
			+ query.errorString())) ;
	}

    transaction.commit() ;	// record that the values come from the database
	setFromDatabase() ; 
	return 0 ;
}


// load the class from the database. Return true if object exist
bool dbUser::load(dbConnection &conn , IdType id) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050

	ACS_CLASS_ANNOUNCE_DEBUG(ACS_VLO_VERB) ;

	dbUser tempRecord(*this); //store current record.


	reset() ; 

    const string &dbKey = conn.getKey() ;
	dbRow row(dbKey) ;
	dbSet set;
	
	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "SELECT " ;
		queryString +=	privateGetFields() ;
		queryString += " FROM T_Users" ;
		queryString += " WHERE UserId " ;
		if(tempRecord._userIdSet) {
			queryString +=	"= " + db::toSQL(dbKey, tempRecord._userId) ;
        }
		else {
			queryString +=	" IS NULL" ;
        }
		string getOrderByString(privateGetOrderBy()) ;
		if(!getOrderByString.empty() )
		{
			string orderby= "ORDER BY";
			if(StringUtils::findNoCase(getOrderByString,orderby) != string::npos) {
				queryString += getOrderByString ;
            }
			else {
				queryString += " ORDER BY " + getOrderByString ;
            }
		}
		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB,"dbUser::load SQL = " << queryString) ;
	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	dbQuery query(conn, sqlString, "dbUser_LOAD") ;

    query.execForSet(set);
    if (set.size() > 1)
    {
        // it should not occur
        ACS_THROW(exIllegalValueException("Unexpected query result: it should return just one row."));
    }
    if(not set.getNextRow(row))
    {
		*this = tempRecord;  //Nothing found: restore previuos situation.
		return false ;
    }

		
	privateLoadRow(row, 0) ;

	setFromDatabase() ;

	resetModifiedFlag() ;

	ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB,"Dump : \"" << *this) ;

	return true;
}


// update an existing instance in database
dbPersistent::IdType dbUser::update(dbConnection &conn) // PRQA S 4020
{
	Lock guard(*this); // PRQA S 3050
    const string &dbKey = conn.getKey() ;

	ACS_COND_THROW (!isFromDatabase(),ObjectNotLoaded("Use the method save() instead of update().")) ;  // PRQA S 3081

	if (!isModified()) { return getId() ; }

	if(!_userIdSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Id\" must be set."))  ; // PRQA S 3081
	}
	if(!_packageRequiredSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Package Required\" must be set."))  ; // PRQA S 3081
	}
	if(!_userTypeSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"User Type\" must be set."))  ; // PRQA S 3081
	}
	if(!_progMediaNumberSet) 
	{
		ACS_THROW(InvalidUse("Mandatory field \"Last Media\" must be set."))  ; // PRQA S 3081
	}

    db::Transaction transaction(conn) ;
    transaction.begin_work("dbUser_UPDATE") ;

	string queryString ;
	const string dialectName = SQLDialectFactory::dialectName(conn.getKey());
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "UPDATE T_Users SET " ; 
		if(_firstNameSet) {
			queryString += "FirstName= " + db::toSQL(dbKey, _firstName) ;
        }
		else {
			queryString += "FirstName=  NULL " ; 
        }
		if(_lastNameSet) {
			queryString += ", LastName= " + db::toSQL(dbKey, _lastName) ;
        }
		else {
			queryString += ", LastName=  NULL " ; 
        }
		if(_titleSet) {
			queryString += ", Title= " + db::toSQL(dbKey, _title) ;
        }
		else {
			queryString += ", Title=  NULL " ; 
        }
		if(_organizationSet) {
			queryString += ", Organization= " + db::toSQL(dbKey, _organization) ;
        }
		else {
			queryString += ", Organization=  NULL " ; 
        }
		if(_departmentSet) {
			queryString += ", Department= " + db::toSQL(dbKey, _department) ;
        }
		else {
			queryString += ", Department=  NULL " ; 
        }
		if(_faxSet) {
			queryString += ", Fax= " + db::toSQL(dbKey, _fax) ;
        }
		else {
			queryString += ", Fax=  NULL " ; 
        }
		if(_phoneSet) {
			queryString += ", Phone= " + db::toSQL(dbKey, _phone) ;
        }
		else {
			queryString += ", Phone=  NULL " ; 
        }
		if(_postalAddressSet) {
			queryString += ", PostalAddress= " + db::toSQL(dbKey, _postalAddress) ;
        }
		else {
			queryString += ", PostalAddress=  NULL " ; 
        }
		if(_projectAndProcessingSet) {
			queryString += ", ProjectAndProcessing= " + db::toSQL(dbKey, _projectAndProcessing) ;
        }
		else {
			queryString += ", ProjectAndProcessing=  NULL " ; 
        }
		queryString += ", PackageRequired= " + db::toSQL(dbKey, _packageRequired) ;
		if(_compressPackageSet) {
			queryString += ", CompressPackage= " + db::toSQL(dbKey, _compressPackage) ;
        }
		else {
			queryString += ", CompressPackage=  NULL " ; 
		}
        if(_compressionModeSet) {
			queryString += ", CompressionMode= " + db::toSQL(dbKey, _compressionMode) ;
        }
		else {
			queryString += ", CompressionMode=  NULL " ; 
        }
		queryString += ", UserType= " + db::toSQL(dbKey, _userType) ;
		if(_packageMaxSizeSet) {
			queryString += ", PackageMaxSize= " + db::toSQL(dbKey, _packageMaxSize) ;
        }
		else {
			queryString += ", PackageMaxSize=  NULL " ; 
        }
		queryString += ", ProgMediaNumber= " + db::toSQL(dbKey, _progMediaNumber) ;
		if(_eMailAddressSet) {
			queryString += ", EMailAddress= " + db::toSQL(dbKey, _eMailAddress) ;
        }
		else {
			queryString += ", EMailAddress=  NULL " ; 
        }
		if(_allQualifiedSet) {
			queryString += ", AllQualified= " + db::toSQL(dbKey, _allQualified) ;
        }
		else {
			queryString += ", AllQualified=  NULL " ; 
        }
		if(_modeSet) {
            queryString += ", " + (SQLDialectFactory::sqlDialect(dbKey).translateColumnName("Mode")) + " = " + db::toSQL(dbKey, _mode) ;
        }
		else {
			queryString += ", " + (SQLDialectFactory::sqlDialect(dbKey).translateColumnName("Mode")) + " = NULL " ; 
        }
        queryString += " WHERE " ;
		queryString += "UserId " ;
		queryString +=	"= " + db::toSQL(dbKey, _userId) ;

		ACS_CLASS_WRITE_DEBUG(ACS_VLO_VERB, "SQL = " << queryString) ;

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "dbUser::update") ;

	query.execForStatus() ;
    transaction.commit() ;
	resetModifiedFlag() ;
	return 0 ;

}


// remove the class from the database
dbPersistent::IdType dbUser::remove(dbConnection &conn)
{
	Lock guard(*this); // PRQA S 3050

    db::Transaction transaction(conn) ;
    transaction.begin_work("dbUser_REMOVE") ;

	string queryString ;
    const string &dbKey = conn.getKey() ;
	const string dialectName = SQLDialectFactory::dialectName(dbKey);
	if( dialectName == "Informix9" || dialectName == "Postgres8" || dialectName == "Oracle11" ) {
		queryString = "DELETE FROM T_Users" ;
		queryString += " WHERE " ;
		queryString += "UserId " ;
		if(_userIdSet) {
			queryString +=	"= " + db::toSQL(dbKey, _userId) ;
        }
		else {
			queryString +=	"IS NULL" ;
        }

	} else {
		ACS_THROW( exIllegalValueException("Unknown db: "+dialectName )); // PRQA S 3081
	}
	SQLString sqlString(dbKey, SQLString::COMMAND) ;
	sqlString.forceSQLString(queryString) ;
	conn.addStateWrapper(*this) ;
	dbQuery query(conn, sqlString, "dbUser::remove") ;

	query.execForStatus() ;
    transaction.commit() ;

	resetFromDatabase() ;
	setModifiedFlag() ;

	return 0 ;
}


// True if the class have valid parameters, false otherwise
bool dbUser::validate() const
{
	Lock guard(*this); // PRQA S 3050

	return true;
}

// export the class to stream
void dbUser::exportObj(rsResourceSet &s) const
{
	Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbUser") ;
	dbPersistent::exportObj(s) ;
    RSSetM(s, _userIdSet, _userId) ;
    RSSetM(s, _firstNameSet, _firstName) ;
    RSSetM(s, _lastNameSet, _lastName) ;
    RSSetM(s, _titleSet, _title) ;
    RSSetM(s, _organizationSet, _organization) ;
    RSSetM(s, _departmentSet, _department) ;
    RSSetM(s, _faxSet, _fax) ;
    RSSetM(s, _phoneSet, _phone) ;
    RSSetM(s, _postalAddressSet, _postalAddress) ;
    RSSetM(s, _projectAndProcessingSet, _projectAndProcessing) ;
    RSSetM(s, _packageRequiredSet, _packageRequired) ;
    RSSetM(s, _compressPackageSet, _compressPackage) ;
    RSSetM(s, _compressionModeSet, _compressionMode) ;
    RSSetM(s, _userTypeSet, _userType) ;
    RSSetM(s, _packageMaxSizeSet, _packageMaxSize) ;
    RSSetM(s, _progMediaNumberSet, _progMediaNumber) ;
    RSSetM(s, _eMailAddressSet, _eMailAddress) ;
    RSSetM(s, _allQualifiedSet, _allQualified) ;
    RSSetM(s, _modeSet, _mode) ;

}


// import the class from a stream
void dbUser::importObj(rsResourceSet &s)
{
	Lock guard(*this); // PRQA S 3050

	rsPushNSpace nsp(s,"dbUser") ;
	dbPersistent::importObj(s) ;
	reset() ;
    RSGetM(s, _userIdSet, _userId) ;
    RSGetM(s, _firstNameSet, _firstName) ;
    RSGetM(s, _lastNameSet, _lastName) ;
    RSGetM(s, _titleSet, _title) ;
    RSGetM(s, _organizationSet, _organization) ;
    RSGetM(s, _departmentSet, _department) ;
    RSGetM(s, _faxSet, _fax) ;
    RSGetM(s, _phoneSet, _phone) ;
    RSGetM(s, _postalAddressSet, _postalAddress) ;
    RSGetM(s, _projectAndProcessingSet, _projectAndProcessing) ;
    RSGetM(s, _packageRequiredSet, _packageRequired) ;
    RSGetM(s, _compressPackageSet, _compressPackage) ;
    RSGetM(s, _compressionModeSet, _compressionMode) ;
    RSGetM(s, _userTypeSet, _userType) ;
    RSGetM(s, _packageMaxSizeSet, _packageMaxSize) ;
    RSGetM(s, _progMediaNumberSet, _progMediaNumber) ;
    RSGetM(s, _eMailAddressSet, _eMailAddress) ;
    RSGetM(s, _allQualifiedSet, _allQualified) ;
    RSGetM(s, _modeSet, _mode) ;

}


// export the class to XML stream
void dbUser::exportXML(XMLOstream &xst) const
{
	Lock guard(*this); // PRQA S 3050

	XMLOstream::Tag txml(xst, "dbUser");
	dbPersistent::exportXML(xst) ;
    XMLTagM(xst, _userIdSet, _userId, "User Id") ;
    XMLTagM(xst, _firstNameSet, _firstName, "First Name") ;
    XMLTagM(xst, _lastNameSet, _lastName, "Last Name") ;
    XMLTagM(xst, _titleSet, _title, "Title") ;
    XMLTagM(xst, _organizationSet, _organization, "Organization") ;
    XMLTagM(xst, _departmentSet, _department, "Department") ;
    XMLTagM(xst, _faxSet, _fax, "Fax") ;
    XMLTagM(xst, _phoneSet, _phone, "Phone") ;
    XMLTagM(xst, _postalAddressSet, _postalAddress, "Postal Address") ;
    XMLTagM(xst, _projectAndProcessingSet, _projectAndProcessing, "Project And Processing") ;
    XMLTagM(xst, _packageRequiredSet, _packageRequired, "Package Required") ;
    XMLTagM(xst, _compressPackageSet, _compressPackage, "Compress Package") ;
    XMLTagM(xst, _compressionModeSet, _compressionMode, "Compression Mode") ;
    XMLTagM(xst, _userTypeSet, _userType, "User Type") ;
    XMLTagM(xst, _packageMaxSizeSet, _packageMaxSize, "Package Max Size (Kb)") ;
    XMLTagM(xst, _progMediaNumberSet, _progMediaNumber, "Last Media") ;
    XMLTagM(xst, _eMailAddressSet, _eMailAddress, "EMail Address") ;
    XMLTagM(xst, _allQualifiedSet, _allQualified, "All Qualified") ;
    XMLTagM(xst, _modeSet, _mode, "Mode") ;

}


// load the object from a row
int dbUser::loadRow(const dbRow &row, int offset)
{
	Lock guard(*this); // PRQA S 3050

	return privateLoadRow(row, offset) ;

}


// load the object from a row
int dbUser::privateLoadRow(const dbRow &row, int offset)
{
	Lock guard(*this); // PRQA S 3050

	row.columnSet(offset + 0, _userId, _userIdSet) ; // PRQA S 3000, 3010, 4400 L1
	row.columnSet(offset + 1, _firstName, _firstNameSet) ;
	row.columnSet(offset + 2, _lastName, _lastNameSet) ;
	row.columnSet(offset + 3, _title, _titleSet) ;
	row.columnSet(offset + 4, _organization, _organizationSet) ;
	row.columnSet(offset + 5, _department, _departmentSet) ;
	row.columnSet(offset + 6, _fax, _faxSet) ;
	row.columnSet(offset + 7, _phone, _phoneSet) ;
	row.columnSet(offset + 8, _postalAddress, _postalAddressSet) ;
	row.columnSet(offset + 9, _projectAndProcessing, _projectAndProcessingSet) ;
	row.columnSet(offset + 10, _packageRequired, _packageRequiredSet) ;
	row.columnSet(offset + 11, _compressPackage, _compressPackageSet) ;
	row.columnSet(offset + 12, _compressionMode, _compressionModeSet) ;
	row.columnSet(offset + 13, _userType, _userTypeSet) ;
	row.columnSet(offset + 14, _packageMaxSize, _packageMaxSizeSet) ;
	row.columnSet(offset + 15, _progMediaNumber, _progMediaNumberSet) ;
	row.columnSet(offset + 16, _eMailAddress, _eMailAddressSet) ;
	row.columnSet(offset + 17, _allQualified, _allQualifiedSet) ;
	row.columnSet(offset + 18, _mode, _modeSet) ;
    // PRQA L:L1

	setFromDatabase() ;

	return offset + 19 ; // PRQA S 4400
}


string dbUser::getWhere()
{
	string res ;
	return res ;
}


string dbUser::getIdName()
{
	return "T_Users.UserId" ;
}


void dbUser::setUserId(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database."))  ; // PRQA S 3081
	}

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_userIdSet || _userId != v ) 
	{
		_userId = v ;
		_userIdSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getUserId(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _userIdSet ; }
	return _userId ;
}


void dbUser::unsetUserId()
{
	if (isFromDatabase())
	{
		ACS_THROW(InvalidUse("Primary Key is from Database."))  ; // PRQA S 3081
	}

	Lock guard(*this); // PRQA S 3050
	if(_userIdSet == true) { setModifiedFlag(); }
	_userIdSet = false;

}
void dbUser::setFirstName(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_firstNameSet || _firstName != v ) 
	{
		_firstName = v ;
		_firstNameSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getFirstName(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _firstNameSet ; }
	return _firstName ;
}


void dbUser::unsetFirstName()
{
	Lock guard(*this); // PRQA S 3050
	if(_firstNameSet == true) { setModifiedFlag(); }
	_firstNameSet = false;

}
void dbUser::setLastName(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_lastNameSet || _lastName != v ) 
	{
		_lastName = v ;
		_lastNameSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getLastName(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _lastNameSet ; }
	return _lastName ;
}


void dbUser::unsetLastName()
{
	Lock guard(*this); // PRQA S 3050
	if(_lastNameSet == true) { setModifiedFlag(); }
	_lastNameSet = false;

}
void dbUser::setTitle(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 8) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_titleSet || _title != v ) 
	{
		_title = v ;
		_titleSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getTitle(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _titleSet ; }
	return _title ;
}


void dbUser::unsetTitle()
{
	Lock guard(*this); // PRQA S 3050
	if(_titleSet == true) { setModifiedFlag(); }
	_titleSet = false;

}
void dbUser::setOrganization(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_organizationSet || _organization != v ) 
	{
		_organization = v ;
		_organizationSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getOrganization(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _organizationSet ; }
	return _organization ;
}


void dbUser::unsetOrganization()
{
	Lock guard(*this); // PRQA S 3050
	if(_organizationSet == true) { setModifiedFlag(); }
	_organizationSet = false;

}
void dbUser::setDepartment(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 32) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_departmentSet || _department != v ) 
	{
		_department = v ;
		_departmentSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getDepartment(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _departmentSet ; }
	return _department ;
}


void dbUser::unsetDepartment()
{
	Lock guard(*this); // PRQA S 3050
	if(_departmentSet == true) { setModifiedFlag(); }
	_departmentSet = false;

}
void dbUser::setFax(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 24) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_faxSet || _fax != v ) 
	{
		_fax = v ;
		_faxSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getFax(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _faxSet ; }
	return _fax ;
}


void dbUser::unsetFax()
{
	Lock guard(*this); // PRQA S 3050
	if(_faxSet == true) { setModifiedFlag(); }
	_faxSet = false;

}
void dbUser::setPhone(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 24) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_phoneSet || _phone != v ) 
	{
		_phone = v ;
		_phoneSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getPhone(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _phoneSet ; }
	return _phone ;
}


void dbUser::unsetPhone()
{
	Lock guard(*this); // PRQA S 3050
	if(_phoneSet == true) { setModifiedFlag(); }
	_phoneSet = false;

}


void dbUser::setPostalAddress(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 128) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_postalAddressSet || _postalAddress != v ) 
	{
		_postalAddress = v ;
		_postalAddressSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getPostalAddress(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _postalAddressSet ; }
	return _postalAddress ;
}


void dbUser::unsetPostalAddress()
{
	Lock guard(*this); // PRQA S 3050
	if(_postalAddressSet == true) { setModifiedFlag(); }
	_postalAddressSet = false;

}

void dbUser::setEMailAddress(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 64) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_eMailAddressSet || _eMailAddress != v ) 
	{
		_eMailAddress = v ;
		_eMailAddressSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getEMailAddress(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _eMailAddressSet ; }
	return _eMailAddress ;
}


void dbUser::unsetEMailAddress()
{
	Lock guard(*this); // PRQA S 3050
	if(_eMailAddressSet == true) { setModifiedFlag(); }
	_eMailAddressSet = false;

}

void dbUser::setProjectAndProcessing(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 128) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_projectAndProcessingSet || _projectAndProcessing != v ) 
	{
		_projectAndProcessing = v ;
		_projectAndProcessingSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getProjectAndProcessing(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _projectAndProcessingSet ; }
	return _projectAndProcessing ;
}


void dbUser::unsetProjectAndProcessing()
{
	Lock guard(*this); // PRQA S 3050
	if(_projectAndProcessingSet == true) { setModifiedFlag(); }
	_projectAndProcessingSet = false;

}
void dbUser::setPackageRequired(bool v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_packageRequiredSet || (_packageRequired != v) ) 
	{
		_packageRequired = v ;
		_packageRequiredSet = true ;
		setModifiedFlag() ;
	}
}


bool dbUser::getPackageRequired(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _packageRequiredSet ; }
	return _packageRequired ;
}


void dbUser::unsetPackageRequired()
{
	Lock guard(*this); // PRQA S 3050
	if(_packageRequiredSet == true) { setModifiedFlag(); }
	_packageRequiredSet = false;

}
void dbUser::setCompressPackage(bool v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_compressPackageSet || (_compressPackage != v ) )
	{
		_compressPackage = v ;
		_compressPackageSet = true ;
		setModifiedFlag() ;
	}
}


bool dbUser::getCompressPackage(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _compressPackageSet ; }
	return _compressPackage ;
}


void dbUser::unsetCompressPackage()
{
	Lock guard(*this); // PRQA S 3050
	if(_compressPackageSet == true) { setModifiedFlag(); }
	_compressPackageSet = false;

}
void dbUser::setCompressionMode(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 16) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_compressionModeSet || _compressionMode != v ) 
	{
		_compressionMode = v ;
		_compressionModeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getCompressionMode(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _compressionModeSet ; }
	return _compressionMode ;
}


void dbUser::unsetCompressionMode()
{
	Lock guard(*this); // PRQA S 3050
	if(_compressionModeSet == true) { setModifiedFlag(); }
	_compressionModeSet = false;

}
void dbUser::setUserType(const string &v)
{
	Lock guard(*this); // PRQA S 3050

	if (v.size() > 12) // PRQA S 4400
	{
		ACS_THROW(InvalidUse("String too long."))  ; // PRQA S 3081
	}

	if (!_userTypeSet || _userType != v ) 
	{
		_userType = v ;
		_userTypeSet = true ;
		setModifiedFlag() ;
	}
}


const string &dbUser::getUserType(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _userTypeSet ; }
	return _userType ;
}


void dbUser::unsetUserType()
{
	Lock guard(*this); // PRQA S 3050
	if(_userTypeSet == true) { setModifiedFlag(); }
	_userTypeSet = false;

}
void dbUser::setPackageMaxSize(int v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_packageMaxSizeSet || (_packageMaxSize != v ) )
	{
		_packageMaxSize = v ;
		_packageMaxSizeSet = true ;
		setModifiedFlag() ;
	}
}


int dbUser::getPackageMaxSize(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _packageMaxSizeSet ; }
	return _packageMaxSize ;
}


void dbUser::unsetPackageMaxSize()
{
	Lock guard(*this); // PRQA S 3050
	if(_packageMaxSizeSet == true) { setModifiedFlag(); }
	_packageMaxSizeSet = false;

}
void dbUser::setProgMediaNumber(int v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_progMediaNumberSet || (_progMediaNumber != v ) )
	{
		_progMediaNumber = v ;
		_progMediaNumberSet = true ;
		setModifiedFlag() ;
	}
}


int dbUser::getProgMediaNumber(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _progMediaNumberSet ; }
	return _progMediaNumber ;
}


void dbUser::unsetProgMediaNumber()
{
	Lock guard(*this); // PRQA S 3050
	if(_progMediaNumberSet == true) { setModifiedFlag(); }
	_progMediaNumberSet = false;

}


void dbUser::setAllQualified(bool v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_allQualifiedSet || ( _allQualified != v ) )
	{
		_allQualified = v ;
		_allQualifiedSet = true ;
		setModifiedFlag() ;
	}
}

bool dbUser::getAllQualified(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _allQualifiedSet ; }
	return _allQualified ;
}


void dbUser::unsetAllQualified()
{
	Lock guard(*this); // PRQA S 3050
	if(_allQualifiedSet == true) { setModifiedFlag(); }
	_allQualifiedSet = false;

}

void dbUser::setMode(int v)
{
	Lock guard(*this); // PRQA S 3050

	if (!_modeSet || (_mode != v ) )
	{
		_mode = v ;
		_modeSet = true ;
		setModifiedFlag() ;
	}
}


int dbUser::getMode(bool *set) const
{
	Lock guard(*this); // PRQA S 3050

	if (set) { *set = _modeSet ; } 
	return _mode ;
}


void dbUser::unsetMode()
{
	Lock guard(*this); // PRQA S 3050
	if(_modeSet == true) { setModifiedFlag(); }
	_modeSet = false;

}


// get the field names
string dbUser::getFields()
{
	string s ;
	s += privateGetFields() ;
	return s ;
}


// get the field names
string dbUser::privateGetFields()
{
	string s ;
	s += "T_Users.UserId, ";
	s += "T_Users.FirstName, ";
	s += "T_Users.LastName, ";
	s += "T_Users.Title, ";
	s += "T_Users.Organization, ";
	s += "T_Users.Department, ";
	s += "T_Users.Fax, ";
	s += "T_Users.Phone, ";
	s += "T_Users.PostalAddress, ";
	s += "T_Users.ProjectAndProcessing, ";
	s += "T_Users.PackageRequired, ";
	s += "T_Users.CompressPackage, ";
	s += "T_Users.CompressionMode, ";
	s += "T_Users.UserType, ";
	s += "T_Users.PackageMaxSize, ";
	s += "T_Users.ProgMediaNumber, " ;
	s += "T_Users.EMailAddress, " ;
	s += "T_Users.AllQualified, " ;
#warning MP to be removed when dbPersistent I/F will have explicit conn
	s += (SQLDialectFactory::sqlDialect("").translateColumnName("T_Users.Mode")) ;
	return s ;
}


// get the table name
string dbUser::getTable()
{
	return "T_Users" ;
}


// get the order by clause
string dbUser::getOrderBy()
{
	string res ;
	res += privateGetOrderBy() ;
	return res ;
}


// get the order by clause
string dbUser::privateGetOrderBy()
{
	string res ;
	return res ;
}


void dbUser::writeTo(ostream &o) const
{
	Lock guard(*this); // PRQA S 3050
    writeToM(o, _userIdSet, _userId) ;
    writeToM(o, _firstNameSet, _firstName) ;
    writeToM(o, _lastNameSet, _lastName) ;
    writeToM(o, _titleSet, _title) ;
    writeToM(o, _organizationSet, _organization) ;
    writeToM(o, _departmentSet, _department) ;
    writeToM(o, _faxSet, _fax) ;
    writeToM(o, _phoneSet, _phone) ;
    writeToM(o, _postalAddressSet, _postalAddress) ;
    writeToM(o, _projectAndProcessingSet, _projectAndProcessing) ;
    writeToM(o, _packageRequiredSet, _packageRequired) ;
    writeToM(o, _compressPackageSet, _compressPackage) ;
    writeToM(o, _compressionModeSet, _compressionMode) ;
    writeToM(o, _userTypeSet, _userType) ;
    writeToM(o, _packageMaxSizeSet, _packageMaxSize) ;
    writeToM(o, _progMediaNumberSet, _progMediaNumber) ;
    writeToM(o, _eMailAddressSet, _eMailAddress) ;
    writeToM(o, _allQualified, _allQualified) ;
    writeToM(o, _modeSet, _mode) ;
}


void dbUser::writeTo(exostream &o) const
{
	Lock guard(*this); // PRQA S 3050
    writeToM(o, _userIdSet, _userId) ;
    writeToM(o, _firstNameSet, _firstName) ;
    writeToM(o, _lastNameSet, _lastName) ;
    writeToM(o, _titleSet, _title) ;
    writeToM(o, _organizationSet, _organization) ;
    writeToM(o, _departmentSet, _department) ;
    writeToM(o, _faxSet, _fax) ;
    writeToM(o, _phoneSet, _phone) ;
    writeToM(o, _postalAddressSet, _postalAddress) ;
    writeToM(o, _projectAndProcessingSet, _projectAndProcessing) ;
    writeToM(o, _packageRequiredSet, _packageRequired) ;
    writeToM(o, _compressPackageSet, _compressPackage) ;
    writeToM(o, _compressionModeSet, _compressionMode) ;
    writeToM(o, _userTypeSet, _userType) ;
    writeToM(o, _packageMaxSizeSet, _packageMaxSize) ;
    writeToM(o, _progMediaNumberSet, _progMediaNumber) ;
    writeToM(o, _eMailAddressSet, _eMailAddress) ;
    writeToM(o, _allQualified, _allQualified) ;
    writeToM(o, _modeSet, _mode) ;
}


_ACS_END_NAMESPACE
