#
#	Copyright 2013, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: $
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 1.1.1.1  2013/06/28 16:28:59  lucio.pulvirenti
#	Import libSafePreInventory
#	
#	
#	
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libSafePreInventory

VERSIONFILE = SafePreInventoryV.C

CUSTOM_INCLUDEPATH =

CUSTOM_LIBPATH =

CSOURCES =	

CINCLUDE =	

C++SOURCES = SafePreInventory.C \
	SafePreInventoryFactory.C \
	ManifestDataExtractor.C \
	ManifestDataExtractorSingleton.C \
	S3AuxManifestDataExtractor.C \
	S3ProdManifestDataExtractor.C \
	ManifestDataExtractorFactory.C \
	SafePreInventoryV.C \
	LTAS1SafePreInventory.C \
	S1ProdManifestDataExtractor.C  \
	S1AuxManifestDataExtractor.C 
	

C++INCLUDE = SafePreInventory.h \
	SafePreInventoryFactory.h \
	ManifestDataExtractor.h \
	ManifestDataExtractorSingleton.h \
	S3AuxManifestDataExtractor.h \
	S3ProdManifestDataExtractor.h \
	S3AuxManifestDataExtractor.h \
	ManifestDataExtractorFactory.h \
	LTAS1SafePreInventory.h \
	S1ProdManifestDataExtractor.h


DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

DSOSPECIFICDEPS =




