#
#	Copyright 1995-2012, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libACSSafeFormatter$
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 1.1.1.1  2012/03/15 09:17:48  damdec
#	Import libACSSafeFormatter
#	
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libACSSafeFormatter

VERSIONFILE = ACSSafeFormatterV.C

C++SOURCES = SafeManifest.C \
	WrappedMetadata.C \
	AcquisitionPeriod.C \
	Platform.C \
	OrbitReference.C \
	FrameSet.C \
	Processing.C \
	QualityInformation.C \
	ACSSafeFormatterV.C

C++INCLUDE = 	SafeManifest.h \
		WrappedMetadata.h \
		AcquisitionPeriod.h \
		Platform.h \
		OrbitReference.h \
		FrameSet.h \
		Processing.h \
		QualityInformation.h \
		SafeObjectDescriptor.h \


#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

