#
#    Copyright 2019, Exprivia - DFDA-AS
#
#    All Rights Reserved.
#
#    This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA;
#    the contents of this file may not be disclosed to third parties, copied or
#    duplicated in any form, in whole or in part, without the prior written
#    permission of Exprivia SpA.
#
#    $Author: $
#
#    $Prod: OAuth2 Utils library $
#


include ../../common/commondefs.mk

  LIBRARYNAME = libOAuth2Utils

  VERSIONFILE = libOAuth2UtV.C

     CSOURCES =

     CINCLUDE =

   C++SOURCES = \
        AccessTokenPayload.C \
        OAuth2ClientCredentialsTokenProvider.C \
        libOAuth2UtV.C

   C++INCLUDE = \
        AccessTokenPayload.h \
        OAuth2ClientCredentialsTokenProvider.h \



COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)


# DO NOT DELETE
#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:

include ../../common/commonrules.mk

