#
#	Copyright 1995-2006, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: ADGSStandalone Application Library $


include ../../common/commondefs.mk
  

  LIBRARYNAME =	libADGSStandaloneApp

  VERSIONFILE = ladgssaV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = ADGSStandaloneApp.C \
 		ADGSLogFmtFactory.C \
		ladgssaV.C

   C++INCLUDE = ADGSStandaloneApp.h \
		ADGSLogFmtFactory.h 
	 

  DSOSPECIFICDEPS =

COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)




include ../../common/commonrules.mk

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:

DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared 



# DO NOT DELETE


