#
#
#	Copyright (c) 2021 EXPRIVIA
#	License: Proprietary
#   ADGS RemoteConnections_PublicKeys Header 
#

include ../../common/commondefs.mk

  LIBRARYNAME =	ADGS_RemoteConnections_PublicKeys

  VERSIONFILE = pubkV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = pubkV.C fake.C

   C++INCLUDE = RemoteConnections_RSAPublicKey.h
                


include ../../common/commonrules.mk

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:




# DO NOT DELETE


