/*

Copyright 2010-2020, Advanced Computer Systems , Inc.
Via Della Bufalotta, 378 - 00139 Roma - Italy
http://www.acsys.itA.C.S. - Advanced Computer Systems S.p.A.

This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems, S.p.A.;
the contents of this file may not be disclosed to third parties, copied or
duplicated in any form, in whole or in part, without the prior written
permission of Advanced Computer Systems, S.p.A.


	$Prod: A.C.S. Databases schema comments script $

	$Id$

	$Author$
	
*/





--------------------------------------------------------------------------------
--                                                                            --
--                                  COMMENTS                                  --
--                                                                            --
--------------------------------------------------------------------------------


/* ------------------------------
	t_asyncsm_operations
*/ ------------------------------
COMMENT ON TABLE t_asyncsm_operations IS 'Contains the list of the ingestions statuses';
COMMENT ON COLUMN t_asyncsm_operations.id_asyncsm_operation IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_asyncsm_operations.unique_id IS 'Unique ID of the LTA Product. It is the ID of the PDI at datastrip level';
COMMENT ON COLUMN t_asyncsm_operations.tstamp IS 'The timestamp of the instant when the product entered in the status specified into the field "status"';
COMMENT ON COLUMN t_asyncsm_operations.operation_id IS 'Type of operation. It is a reference to t_operationtypes';
COMMENT ON COLUMN t_asyncsm_operations.sm_id IS 'The storage in which the LTA product is archived. It is a reference to t_storagemanager';
COMMENT ON COLUMN t_asyncsm_operations.status_id IS 'The status in which the LTA product is. It is a reference to t_stati';
COMMENT ON COLUMN t_asyncsm_operations.status_reason IS 'Description of the reason why the product is in the status defined into the field "status"';


/* ------------------------------
	t_localtransfermodes  
*/ ------------------------------
COMMENT ON TABLE t_localtransfermodes IS 'Contains the list of possible local data transfer methods';
COMMENT ON COLUMN t_localtransfermodes.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_localtransfermodes.localtransfermode IS 'The type of transfer mode (eg: COPY, HARDLINK...)';


/* ------------------------------
	t_proc_ftype_generation
*/ ------------------------------
COMMENT ON TABLE t_proc_ftype_generation IS 'Cross table that links processors and filetypes that can be generated by processors';
COMMENT ON COLUMN t_proc_ftype_generation.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_proc_ftype_generation.proc_id IS 'Processor identifier. References the t_processors table';
COMMENT ON COLUMN t_proc_ftype_generation.ftype_id IS 'FileType identifier. References the t_filetypes table';


/* ------------------------------
	t_sm_sync_missingactions
*/ ------------------------------
COMMENT ON TABLE t_sm_sync_missingactions IS 'Contains the list of the failed and still pending operations performed on synch storage managers';
COMMENT ON COLUMN t_sm_sync_missingactions.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_sm_sync_missingactions.operation IS 'Identifies the type of the operation. Can be UPLOAD or ERASE';
COMMENT ON COLUMN t_sm_sync_missingactions.sm_id IS 'The ID of the storage manager on which the missing operation shall be performed. References the t_storagemanager table';
COMMENT ON COLUMN t_sm_sync_missingactions.inv_id IS 'Identifies the inventory id of the file to be UPLOADED into the storage manager. References the t_inventory table';
COMMENT ON COLUMN t_sm_sync_missingactions.invsm_id IS 'Identifies the file to be ERASED from the identified storage manager. References the t_inventorysm table';
COMMENT ON COLUMN t_sm_sync_missingactions.tstamp IS 'When the record has been inserted (default value NOW)';


/* ------------------------------
	t_sor_requests
*/ ------------------------------
COMMENT ON TABLE t_sor_requests IS 'Contains the list of SOR (Special Operation Request)';
COMMENT ON COLUMN t_sor_requests.id_sor_request IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_sor_requests.spacecraftid IS 'Spacecraft Identifier eg: Sentinel-1A';
COMMENT ON COLUMN t_sor_requests.requestid IS 'The unique originator request identifier. It is composed by year and a 3 value progressive number. eg: 2012-001';
COMMENT ON COLUMN t_sor_requests.raiseddate IS 'When SOR was generated';
COMMENT ON COLUMN t_sor_requests.originator IS 'The name of the person raising the SOR';
COMMENT ON COLUMN t_sor_requests.status IS 'Status of SOR. Can be: Requested, Planned or Re-Planned, Executed or Abandoned';
COMMENT ON COLUMN t_sor_requests.statusupdated IS 'When the SOR status has been changed';
COMMENT ON COLUMN t_sor_requests.emailtitle IS 'The email subject. Is a naming convention composed by: <SpacecraftID> SOR <RequestID> <Title> - <Status>';
COMMENT ON COLUMN t_sor_requests.emailbody IS 'Contain the body of the email';
COMMENT ON SEQUENCE t_sor_requests_id_sor_request_seq IS 'Used to generate the primary keys of the t_sor_requests table';


/* ------------------------------
	t_statetransitions_allowed
*/ ------------------------------
COMMENT ON TABLE t_statetransitions_allowed IS 'Contains the list of admitted transitions for each table';
COMMENT ON COLUMN t_statetransitions_allowed.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_statetransitions_allowed.table_id IS 'Is the identifier of the table to which the status change is associated. References the t_statetransitions_tables table';
COMMENT ON COLUMN t_statetransitions_allowed.prev_state_id IS 'Is the identifier to the previous value of the changing status. References the t_stati table';
COMMENT ON COLUMN t_statetransitions_allowed.post_state_id IS 'Is the identifier to the new value of the changing status. References the t_stati table';


/* ------------------------------
	t_statetransitions_flows
*/ ------------------------------
COMMENT ON TABLE t_statetransitions_flows IS 'Contains the list of possible data flows for tables where the status change is checked';
COMMENT ON COLUMN t_statetransitions_flows.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_statetransitions_flows.flow_type IS 'The type of flow (eg: RETRIEVE, ARCHIVE...). "none" where there are no different flows';


/* ------------------------------
	t_statetransitions_tables
*/ ------------------------------
COMMENT ON TABLE t_statetransitions_tables IS 'Contains the list of tables having the "status" field to analyze';
COMMENT ON COLUMN t_statetransitions_tables.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_statetransitions_tables.table_name IS 'The name of the table';
COMMENT ON COLUMN t_statetransitions_tables.flow_id IS 'This field is used when in a table there may be the same status transitions, but in different flows. The default is 1 that mean "none". References the t_statetransitions_flows table';




