#
#	Copyright 1995-2002, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$ 
#
#	$Prod: A.C.S. ProductHeader Library $
#	$Id$
#
#   $Log$
#   Revision 2.1  2006/08/23 14:51:24  paoscu
#   Shared libraries dependencies added
#
#   Revision 2.0  2006/02/28 09:14:06  marpas
#   Exception 2.1 I/F adopted
#
#   Revision 1.3  2005/06/20 12:24:42  enrcar
#   INCLUDEPATH Removed
#
#   Revision 1.2  2003/02/05 14:23:03  giucas
#   Changed by marpas
#
#   Revision 1.1.1.1  2002/10/23 10:04:58  giucas
#   Import libProductHeader
#
#
#

include ../../common/commondefs.mk

  LIBRARYNAME =	libProductHeader

  VERSIONFILE = prodHeaderV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = ProductHeader.C \
   		prodHeaderV.C
   				

   C++INCLUDE = ProductHeader.h 



DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared 




include ../../common/commonrules.mk
DSOSPECIFICDEPS =



#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE
