#
#
#   Copyright 2019, Exprivia - DFDA-AS
#   Via Della Bufalotta, 378 - 00139 Roma - Italy
#   http://www.exprivia.it
#
#   All Rights Reserved.
#
#   This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA;
#   the contents of this file may not be disclosed to third parties, copied or
#   duplicated in any form, in whole or in part, without the prior written
#   permission of Exprivia SpA
#
#   $Prod: SRV App $
#
#

include ../../common/commondefs.mk


  LIBRARYNAME =	libSRVApp

  VERSIONFILE = SRVAppV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
		SRVAppV.C\
		SRVApp.C

   C++INCLUDE = SRVApp.h \
		
COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)


#empty rule, do not remove, you can add specific remotion commands
cleanspecific:
	@rm -f *.bak;


#empty rule, do not remove, you can add specific remotion commands
helpspecific:



# DO NOT DELETE
include ../../common/commonrules.mk


