include $(PRJROOTTREE)/common/commondefs.mk

TARGETFILES=

cleanspecific:

helpspecific:

INST_EXECUTABLE= s1_pre_inventory_aux_tro.rb \
				s1_pre_inventory_aux_tec.rb

include $(PRJROOTTREE)/common/commonrules.mk
