#
#	Copyright 1995-2004, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	Authors: 
#
#	$Prod: A.C.S. TlDaemon Default PCC Library Makefile $
#	$Id$
#
#	$Log$
#	
#

include ../../common/commondefs.mk

  LIBRARYNAME =	libTlDefaultPCC

  VERSIONFILE =	tldpccfV.C

     CSOURCES =	

     CINCLUDE =	





   C++SOURCES = \
		TlPreconditionCheckerFactory.C \
		DbAlternative_PCC.C \
		DefaultAlternative_PCC.C \
		DefaultTl_PCC.C \
		tldpccfV.C


   C++INCLUDE = \


  DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared -L$(LIB_INTEGRATION_PATH)/lib

  TARGETFILES =  $(DSO_LIBRARY)


#empty rule, do not remove, you can add specific remotion commands
cleanspecific:


#empty rule, do not remove, you can add specific remotion commands
helpspecific:


include ../../common/commonrules.mk
