#
#	Copyright 1995-2001, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libDgfListener Library $
#	$Authors$
#	$Name$
#	$Id$
#       $Log$
#       Revision 1.5  2005/09/08 14:17:26  paoscu
#       INCLUDEPATH REMOVED
#
#       Revision 1.4  2005/06/15 14:58:36  serfol
#       inserting custom include and lib
#
#       Revision 1.3  2003/01/31 13:13:46  serfol
#       updated the version file
#
#       Revision 1.2  2002/12/20 14:27:50  luipir
#       *** empty log message ***
#
#       Revision 1.1.1.1  2002/12/18 17:35:38  luipir
#       import libDgfListener start
#
#


  LIBRARYNAME =	libDgfListener

  VERSIONFILE = DgfListenerV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
   		DgfBroadcastListener.C \
		DgfListenerV.C

   C++INCLUDE = DgfBroadcastListener.h


include ../../common/commondefs.mk

DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared 




include ../../common/commonrules.mk
DSOSPECIFICDEPS =



#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE


