#
#	Copyright 1995-2014, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$
#	$Prod: A.C.S. ThinLayer TaskTableElements Library Makefile $
#
#	$Id$
#
#	$Log$
#	Revision 2.4  2008/10/20 13:18:56  marfav
#	Added support to task cmdline parameters
#	
#	Revision 2.3  2008/04/22 11:07:45  marfav
#	Task Table elemenets now use the conditioned visitor design pattern
#	
#	Revision 2.1  2006/03/06 14:18:30  giucas
#	Fixed conflicts on merge
#	
#	Revision 2.0  2006/03/06 11:54:23  marfav
#	Exception 2.1 I/F adopted
#	
#	Revision 1.9  2006/03/06 11:43:26  marfav
#	New Task Library having recursive definition
#	

include ../../common/commondefs.mk


  LIBRARYNAME =	libTask

  VERSIONFILE =	tltV.C

     CSOURCES =	

     CINCLUDE =	


   C++SOURCES = \
		AtExitSequence.C \
		BreakpointDescriptor.C \
		ConfigDescriptor.C \
		ConfigSpaceDescriptor.C \
		InputAlternative.C \
		InputDescriptor.C \
		OutputDescriptor.C \
		Pool.C \
		Sequence.C \
		Task.C \
		TaskDataTypes.C \
		TaskTableElement.C \
		TaskTableVisitable.C \
		TaskTableVisitor.C \
		WeightNormalizer.C \
		TaskParameterDescriptor.C \
		tltV.C


   C++INCLUDE = \
		AtExitSequence.h \
		BreakpointDescriptor.h \
		ConfigDescriptor.h \
		ConfigSpaceDescriptor.h \
		InputAlternative.h \
		InputDescriptor.h \
		OutputDescriptor.h \
		Pool.h \
		Sequence.h \
		Task.h \
		TaskDataTypes.h \
		TaskTableElement.h \
		TaskTableVisitable.h \
		TaskTableVisitor.h \
		WeightNormalizer.h \
		TaskParameterDescriptor.h \





#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

helpspecific:


include ../../common/commonrules.mk
