##
#    Copyright 1995-2005, Advanced Computer Systems ,Inc.
#    Via Della Bufalotta, 378 - 00139 Roma - Italy
#    http://www.acsys.it
#    All Rights Reserved.
#
#    This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#    the contents of this file may not be disclosed to third parties, copied or
#    duplicated in any form, in whole or in part, without the prior written
#    permission of Advanced Computer Systems, Inc.
#
#	 $Prod: $
#
#    $Id$
#
#    $Author$
#
#    $Log$
#    Revision 5.0  2013/06/18 09:49:23  marpas
#    adoption of libException 5.x standards
#
#    Revision 1.7  2013/03/08 16:55:59  marpas
#    libDbBasic no longer used
#
#    Revision 1.6  2010/10/12 13:13:53  clanas
#    modified to use pgsql public interfaces
#
#    Revision 1.5  2008/11/04 15:19:42  marpas
#    dbExpress include no loger from extcomponents ! There is libDbExpress !
#
#    Revision 1.4  2008/11/04 12:03:23  marpas
#    bitwise operation introduced
#
#    Revision 1.3  2008/06/30 09:36:25  enrcar
#    Unable to compile. Fixed.
#
#    Revision 1.2  2008/05/07 16:03:52  enrcar
#    EC:: postgres path added
#
#    Revision 1.1.1.2  2007/12/04 10:44:23  crivig
#    Imported source
#
#
include ../../common/commondefs.mk

  LIBRARYNAME =	libPostgres8Dialect

  VERSIONFILE = Psg8DV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
		Postgres8SQLDialectFactory.C \
		Postgres8SQLDialect.C \
		Postgres8ConnectionParameters.C \
		Psg8DV.C

   C++INCLUDE = 

 CUSTOM_INCLUDEPATH := 	
                        
 DSOLIBRARYPATH = 
			
 CUSTOM_LDOPTS := 
			

 DSOSPECIFICDEPS = -lpq
   

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:


#empty rule, do not remove, you can add specific help strings
helpspecific:


include ../../common/commonrules.mk



# DO NOT DELETE


