#
#	Copyright 1995-2006, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$
#
#	$Prod: libESAProductFileName LINUX Makefile $
#
#	$Id$
#
#   $Log$
#   Revision 1.5  2012/02/15 09:50:35  marpas
#   no more warnings
#
#   Revision 1.8  2010/10/20 13:13:32  marpas
#   fixed for .so generation
#
#   Revision 1.7  2009/04/02 13:16:53  enrcar
#   EC:: Support to crule for plain-C added
#
#   Revision 1.6  2007/01/25 10:25:44  giucas
#   py WRAPPER added
#
#   Revision 1.5  2006/10/11 12:09:43  enrcar
#   LINUX: Library is now compiled by c++ compiler
#
#   Revision 1.4  2006/09/28 14:02:56  enrcar
#   file re-added
#
#   Revision 1.2  2006/09/27 15:43:39  enrcar
#   versioning added
#
#   Revision 1.1.1.1  2006/05/17 09:22:06  enrcar
#   imported source
#
#


include ../../common/commondefs.mk

  LIBRARYNAME =	libESAProductFileName

  VERSIONFILE = esapfnV.C

     CSOURCES =\
           
     CINCLUDE =\
                ESAProductFileName.h	

   C++SOURCES = esapfnV.C \
   				libESAProductFileName.C	 
                
   C++INCLUDE = 

DSOSPECIFICDEPS =

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:


#empty rule, do not remove, you can add specific help strings
helpspecific:

include ../../common/commonrules.mk



# DO NOT DELETE
