#
#	Copyright 2019, Exprivia - DFDA-AS
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Exprivia SpA.
#
#	$Author: $
#
#	$Prod: LTA common functions $
#


include ../../common/commondefs.mk

  LIBRARYNAME =	libLTACommon

  VERSIONFILE = LTACommonV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = LTACommon.C \
                LTADBSimulationSingleton.C \
                AipParameters.C \
                LTACommonV.C

   C++INCLUDE = LTACommon.h \
                LTADBSimulationSingleton.h \
                AipParameters.h


COV_PATHS := $(shell pwd)/unitTest

COV_BASE_DIR := $(shell pwd)



#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk



