#
#	Copyright 1995-2018, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$
#
#	$Prod: A.C.S. Default RemoteConnections_PublicKeys Header $
#
#	$Id$
#
#   	Log: Makefile,v $
#


include ../../common/commondefs.mk

  LIBRARYNAME =	Default_RemoteConnections_PublicKeys

  VERSIONFILE = pubkV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = pubkV.C fake.C

   C++INCLUDE = RemoteConnections_RSAPublicKey.h
                


include ../../common/commonrules.mk

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:




# DO NOT DELETE


