#
#	Copyright 1995-2012, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libPackageProcessing$
#
#	$Id$
#
#	$Author$
#
#	$Log$
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libPackageProcessing

VERSIONFILE = PackageProcessingV.C

CUSTOM_INCLUDEPATH =

CUSTOM_LIBPATH =

CSOURCES =	

CINCLUDE =	

C++SOURCES = \
	PackageProcessingManager.C \
	PackageProcessor.C \
	PackageProcessorCheck.C \
	PackageProcessorFmtDist.C \
	PackageTaskTableManager.C \
	ExpProcInfo.C \
	PackageProcessingV.C


C++INCLUDE = \
	PackageProcessingManager.h \
	PackageTaskTableManager.h \
	ExpProcInfo.h \
	PackageProcessor.h \
	PackageProcessorCheck.h \
	PackageProcessorFmtDist.h
	
DSOSPECIFICDEPS = -lboost_serialization

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk


