#
#	Copyright 2011, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Author$
#
#	$Prod: A.C.S. /sgiDTInclude Library test $
#
#	$Id$
#
#   $Log$
#
#
#

include ../../../common/commondefs.mk

TARGETFILES=
cleanspecific:


helpspecific:
	@echo Nothing to be done

include ../../../common/commonrules.mk
