#
#	Copyright 2023-2023, Exprivia - DFDA-AS
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Exprivia SpA.
#
#	$Prod: ADGSBaselineReportGenerator $
#

include $(PRJROOTTREE)/common/commondefs.mk

TARGETFILES=

cleanspecific:

helpspecific:

INST_EXECUTABLE= adgs_baseline_report.rb

include $(PRJROOTTREE)/common/commonrules.mk
