#
#	Copyright 1995-2022, Exprivia SpA DFDA-AS
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.exprivia.com
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Exprivia SpA
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Exprivia SpA
#
#	$Author$
#
#	$Prod: A.C.S. Default RemoteConnections_PrivateKeys Header $
#
#


include ../../common/commondefs.mk

  LIBRARYNAME =	Default_RemoteConnections_PrivateKeys

  VERSIONFILE = privkV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = privkV.C fake.C

   C++INCLUDE = RemoteConnections_RSAPrivateKey.h
                


include ../../common/commonrules.mk

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:




# DO NOT DELETE


