#
#	Copyright 1995-2008, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libFieldReplacer $
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 1.2  2008/11/14 14:50:13  manuel.maccaroni
#	fixed cvs tags
#	
#	Revision 1.1.1.1  2008/11/14 14:47:24  manuel.maccaroni
#	Import libFieldReplacer
#	
#
#
include ../../common/commondefs.mk

   LIBRARYNAME = libFieldReplacer

   VERSIONFILE = FieldReplacerV.C

   CUSTOM_INCLUDEPATH =

   CUSTOM_LIBPATH =

   CSOURCES =	

   CINCLUDE =	

   C++SOURCES = \
	FieldReplacer.C  \
	FieldReplacerV.C 

   C++INCLUDE = \
   	FieldReplacer.h 


DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

DSODEPENDLIBS = 


