#
#	Copyright 1995-2010, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libDbExpress$
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 2.0  2010/02/19 11:18:57  marpas
#	ORACLE dependency from now on
#	
#	Revision 1.3  2010/02/19 11:16:49  marpas
#	oralobif.hpp header file added to be used in conjunction with ORACLE driver and
#	related dialect for LOB operations.
#	
#	Revision 1.2  2008/12/11 11:20:44  lucio.pulvirenti
#	thread safety & cstr class definitiona added
#	
#	Revision 1.1.1.1  2008/07/21 15:28:10  paoscu
#	Importing dbExpress
#	
#        
#

include ../../common/commondefs.mk

   LIBRARYNAME = libDbExpress

   VERSIONFILE = DbExpressV.C

   CUSTOM_INCLUDEPATH =

   CUSTOM_LIBPATH =

   CSOURCES =	

   CINCLUDE =	

   C++SOURCES = DbExpress.C \
				DbExpressV.C 

   C++INCLUDE = dbxcommon.hpp \
   				dbxpress.hpp \
				oralobif.hpp \
				cstr.hpp \
				dbxpressIf.h \
				DbExpress.h


#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

