mkdir -p "$RPM_BUILD_ROOT%{INST_DIR}"
mkdir -p "$RPM_BUILD_ROOT%{SERVICE_DIR}"

cp $RPM_BUILD_DIR/%{APP_NAME}/target/*.jar $RPM_BUILD_ROOT/%{TARGET_JAR}

cp $RPM_BUILD_DIR/%{APP_NAME}/setup/conf/systemd/%{SERVICE_FILENAME} $RPM_BUILD_ROOT/%{TARGET_SERVICE}
