#
#	Copyright 1995-2001, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	Authors: 
#
#	$Prod: A.C.S. Timer Library $
#	$Id$
#       $Log$
#       Revision 2.1  2006/08/23 14:50:30  paoscu
#       Shared libraries dependencies added
#
#       Revision 2.0  2006/02/28 08:28:39  marpas
#       Exception 2.1 I/F adopted
#
#       Revision 1.4  2005/06/20 14:22:50  enrcar
#       INCLUDEPATH REMOVED
#
#       Revision 1.3  2003/01/31 17:31:18  marpas
#       LIB_INTEGRATION_PATH variable management
#
#       Revision 1.2  2003/01/16 11:33:45  marpas
#       lock & unlock exceptions added
#
#       Revision 1.1.1.1  2002/10/04 16:26:05  paoscu
#       Import libTimer
#
#       Revision 1.3  2001/08/30 10:49:22  marco
#       minor changes linux <--> irix
#
#       Revision 1.2  2001/08/07 11:05:15  marco
#       version class updated
#
#       Revision 1.1.1.1  2001/08/07 07:33:06  marco
#       Imported sources
#


include ../../common/commondefs.mk


  LIBRARYNAME =	libTimer

  VERSIONFILE = tV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = Timer.C tV.C

   C++INCLUDE = Timer.h

DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared 

COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)




include ../../common/commonrules.mk
DSOSPECIFICDEPS =



#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE


