#
#	Copyright 2013, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: $
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libEOFFilenamePreInventory

VERSIONFILE = EOFFilenamePreInventoryV.C

CUSTOM_INCLUDEPATH =

CUSTOM_LIBPATH =

CSOURCES =	

CINCLUDE =	

C++SOURCES = EOFFilenamePreInventory.C \
	EOFFilenamePreInventoryFactory.C \
	EOFFilenamePreInventoryV.C

C++INCLUDE = EOFFilenamePreInventory.h \
	EOFFilenamePreInventoryFactory.h \


DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

DSOSPECIFICDEPS =




