#!/bin/bash
#
# This script deletes the lock files generated by the distribution older than 36 hours
#

for i in `find /data/ADGS/downloadspace -type f -name "*.lock" -mtime +1.5`
do
        filename=${i%.lock}
        if [ ! -e $filename ] ;
        then
                rm -f $i
        fi
done
