
-- Version 11.12.00
-- POSTGRES








--------------------------------------------------------------------------------
-------------------------------- TABLES CREATION -------------------------------
--------------------------------------------------------------------------------

/* ------------------------------
	t_proc_ftype_generation
*/ ------------------------------
CREATE TABLE t_proc_ftype_generation (
    id INTEGER NOT NULL,
    proc_id INTEGER NOT NULL,
	ftype_id INTEGER NOT NULL
) ;
ALTER TABLE t_proc_ftype_generation
	ADD CONSTRAINT pk_t_proc_ftype_generation
		PRIMARY KEY (id) ;

ALTER TABLE t_proc_ftype_generation 
	ADD CONSTRAINT uq_proc_ftype_generation01
		UNIQUE (proc_id, ftype_id) ;

ALTER TABLE t_proc_ftype_generation
	ADD CONSTRAINT fk_proc_ftype_generation01
		FOREIGN KEY (proc_id)
			REFERENCES t_processors (id_processor)
				ON DELETE CASCADE ;

ALTER TABLE t_proc_ftype_generation
	ADD CONSTRAINT fk_proc_ftype_generation02
		FOREIGN KEY (ftype_id)
			REFERENCES t_filetypes (id_filetype)
				ON DELETE CASCADE ;

CREATE INDEX ix_t_proc_ftype_generation01 ON t_proc_ftype_generation USING BTREE (proc_id) ;
CREATE INDEX ix_t_proc_ftype_generation02 ON t_proc_ftype_generation USING BTREE (ftype_id) ;

COMMENT ON TABLE t_proc_ftype_generation IS 'Cross table that links processors and filetypes that can be generated by processors';
COMMENT ON COLUMN t_proc_ftype_generation.id IS 'Record identifier (Primary Key)';
COMMENT ON COLUMN t_proc_ftype_generation.proc_id IS 'Processor identifier. References the t_processors table';
COMMENT ON COLUMN t_proc_ftype_generation.ftype_id IS 'FileType identifier. References the t_filetypes table';








--------------------------------------------------------------------------------
-------------------------------- VIEWS CREATION --------------------------------
--------------------------------------------------------------------------------

/* ------------------------------
	v_proc_ftype_generation
*/ ------------------------------
CREATE OR REPLACE VIEW v_proc_ftype_generation (
	processorname, 
	processorversion,
	filetype)
AS SELECT
	pr.processorname, 
	pr.processorversion,
	ft.filetype
FROM 
	t_proc_ftype_generation AS pf
	INNER JOIN t_processors AS pr 
		ON pf.proc_id = pr.id_processor
	INNER JOIN t_filetypes AS ft 
		ON pf.ftype_id = ft.id_filetype
;








---------------------------------------------------------------------------------
---------------------------------- CONCLUSIONS ----------------------------------
---------------------------------------------------------------------------------

DELETE FROM t_schema WHERE version = 'pds-11.12.00' ;

INSERT INTO t_schema (
		version, 
		modificationdate,
		modificationtype,
		schematype,
		cvstag,
		description )
VALUES	(
		'pds-11.12.00',
		'2015-10-08',
		3,
		2,
		'PDS_11-12-0',
		'Added table t_proc_ftype_generation and view v_proc_ftype_generation.'
) ;


