#
#
#	Copyright (c) 2021 EXPRIVIA
#	License: Proprietary
#   ADGS RemoteConnections_PrivateKeys Header 
#


include ../../common/commondefs.mk

  LIBRARYNAME =	ADGS_RemoteConnections_PrivateKeys

  VERSIONFILE = privkV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = privkV.C fake.C

   C++INCLUDE = \
		RemoteConnections_RSAPrivateKey.h \
		DbConnectionSecret.h 

   ENCRYPTED_SOURCES = \
		RemoteConnections_RSAPrivateKey.h \
		DbConnectionSecret.h 
 


include ../../common/commonrules.mk

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:




# DO NOT DELETE


