#
#	Copyright 1995-2010, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	$Prod: A.C.S. libProductNaming$
#
#	$Id$
#
#	$Author$
#
#	$Log$
#	Revision 1.3  2010/09/22 09:34:22  damdec
#	SentinelProductName class added
#	
#	Revision 1.2  2010/04/16 08:59:33  marant
#	SafeProductName added
#	
#	Revision 1.1.1.1  2010/04/12 10:02:06  marant
#	Import libProductNaming
#	
#        
#

include ../../common/commondefs.mk

LIBRARYNAME = libProductNaming

VERSIONFILE = ProductNamingV.C

CUSTOM_INCLUDEPATH =

CUSTOM_LIBPATH =

CSOURCES =	

CINCLUDE =	

C++SOURCES = ProductNaming.C \
	     NamingRules.C \
	     SafeProductName.C \
	     SentinelProductName.C \
	     ProductNamingV.C 

C++INCLUDE = ProductNaming.h \
		SafeProductName.h \
		SentinelProductName.h 

DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared

#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


# DO NOT DELETE

include ../../common/commonrules.mk

DSOSPECIFICDEPS =


