ADGS:
  baseUrl: https://omcs.atlassian.net
  apiVer: latest
  username: ccds.adgs.service@exprivia.com
  token: jc00ExKen7kjAYnuvVl21130
  assignee: ADGS
  status: "To+Do"
  type: "Email to ADGS"
  transId: 81
  OutDirectory: /data/fromFOSMail
  LogDirectory: /data/ADGS/log
  LogLevel: INFO
