#
#	Copyright 1995-2002, Advanced Computer Systems , Inc.
#	Via Della Bufalotta, 378 - 00139 Roma - Italy
#	http://www.acsys.it
#
#	All Rights Reserved.
#
#	This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems;
#	the contents of this file may not be disclosed to third parties, copied or
#	duplicated in any form, in whole or in part, without the prior written
#	permission of Advanced Computer Systems, Inc.
#
#	Authors: 
#
#	$Prod: A.C.S. String Utility library $
#	$Id$
#
#       $Log$
#       Revision 1.3  2012/12/03 16:51:47  marpas
#       refactoring, appliying qa rules and coding best practices
#       pay attention to performances and other optimization
#
#       Revision 1.2  2006/08/23 14:50:15  paoscu
#       Shared libraries dependencies added
#
#       Revision 1.1.1.1  2004/09/20 16:47:24  marfav
#       Import libStringUtils
#
#
#

include ../../common/commondefs.mk

  LIBRARYNAME =	libStringUtils

  VERSIONFILE = suV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = StringUtils.C \
		suV.C

   C++INCLUDE = StringUtils.h \


COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)



#empty rule, do not remove, you can add specific remotion commands
cleanspecific:

#empty rule, do not remove, you can add specific help strings
helpspecific:


DSOSPECIFICDEPS =


# DO NOT DELETE

DSOLIBRARYPATH = -L$(LIB_INTEGRATION_PATH)/shared 




include ../../common/commonrules.mk



