/*

Copyright 2010-2020, Advanced Computer Systems , Inc.
Via Della Bufalotta, 378 - 00139 Roma - Italy
http://www.acsys.itA.C.S. - Advanced Computer Systems S.p.A.

This is UNPUBLISHED PROPRIETARY SOURCE CODE of Advanced Computer Systems, S.p.A.;
the contents of this file may not be disclosed to third parties, copied or
duplicated in any form, in whole or in part, without the prior written
permission of Advanced Computer Systems, S.p.A.


	$Prod: A.C.S. Databases schema comments script $

	$Id$

	$Author$

	$Log$
	Revision 1.1  2014/07/15 12:14:12  achnat
	Added comments
	
*/





--------------------------------------------------------------------------------
--                                                                            --
--                                  COMMENTS                                  --
--                                                                            --
--------------------------------------------------------------------------------

/* ------------------------------
	t_cov_periods
*/ ------------------------------
COMMENT ON TABLE t_cov_periods IS 'Contains the list of planned periods, shows the events that occurred in a period and the rule to which the period is associated';
COMMENT ON COLUMN t_cov_periods.id_interval IS 'Record identifier (Primary Key autoincrement)';
COMMENT ON COLUMN t_cov_periods.coveragerule_id IS 'Id of the referenced rule. References id_coveragerule on t_cov_rules table.';
COMMENT ON COLUMN t_cov_periods.t_begin IS 'Begin time of the period';
COMMENT ON COLUMN t_cov_periods.t_end IS 'End time of the period';
COMMENT ON COLUMN t_cov_periods.exp_val_start IS 'Expected validity start';
COMMENT ON COLUMN t_cov_periods.exp_val_stop IS 'Expected validity stop';
COMMENT ON COLUMN t_cov_periods.events IS 'Counter of the occurred events';
COMMENT ON COLUMN t_cov_periods.cover_pct IS 'Percentage of coverage of the validity interval';
COMMENT ON COLUMN t_cov_periods.creationdate IS 'Datetime that represents when the record was inserted. Is automatically generated by a default to "now"';
COMMENT ON COLUMN t_cov_periods.reported IS 'Flag that declares if the period has been reported';
COMMENT ON SEQUENCE t_cov_periods_id_interval_seq IS 'Used to generate the primary keys of the t_cov_periods table';


/* ------------------------------
	t_cov_relevancies
*/ ------------------------------
COMMENT ON TABLE t_cov_relevancies IS 'Contains the list of files per period. This table is used only by stored procedures to calculate the coverage percentage';
COMMENT ON COLUMN t_cov_relevancies.id_relevancy IS 'Record identifier (Primary Key autoincrement)';
COMMENT ON COLUMN t_cov_relevancies.period_id IS 'Id of the referenced period. References id_interval on t_cov_periods table.';
COMMENT ON COLUMN t_cov_relevancies.inv_id IS 'Id of the referenced file to analyze. References id_inv on t_inventory table.';
COMMENT ON COLUMN t_cov_relevancies.inv_val_start IS 'ValidityStart of the file to analyze';
COMMENT ON COLUMN t_cov_relevancies.inv_val_stop IS 'ValidityStop of the file to analyze';
COMMENT ON COLUMN t_cov_relevancies.creationdate IS 'Datetime that represents when the record was inserted. Is automatically generated by a default to "now"';
COMMENT ON SEQUENCE t_cov_relevancies_id_relevancy_seq IS 'Used to generate the primary keys of the t_cov_relevancies table';


/* ------------------------------
	t_cov_rules
*/ ------------------------------
COMMENT ON TABLE t_cov_rules IS 'Contains the list of rules and their configurations' ;
COMMENT ON COLUMN t_cov_rules.id_coveragerule IS 'Record identifier (Primary Key autoincrement)' ;
COMMENT ON COLUMN t_cov_rules.rule_type IS 'Type of rule. Can be only A, B or C' ;
COMMENT ON COLUMN t_cov_rules.time_0 IS 'Datetime that represents the beginning of the first period' ;
COMMENT ON COLUMN t_cov_rules.t_sec IS 'Width of each period. The values is expressed in seconds. For C type rules this value is 0' ;
COMMENT ON COLUMN t_cov_rules.int_a IS 'Interval A. Is the number that will be used to generate the period validity start. The value is expressed in seconds. For C type rules this value is 0' ;
COMMENT ON COLUMN t_cov_rules.int_b IS 'Interval B. Is the number that will be used to generate the period validity stop. The value is expressed in seconds and must be less than int_a. For C type rules this value is -1' ;
COMMENT ON COLUMN t_cov_rules.n_min IS 'Minimum number of expected file for a period. The value must be greater than 0. For A and C type rules this value is 1' ;
COMMENT ON COLUMN t_cov_rules.n_max IS 'Maximum number of expected file for a period. The value must be greater than n_min. For A and C type rules this value is 1' ;
COMMENT ON COLUMN t_cov_rules.delta_gap IS 'Allowable range for the gap between consecutive files. The value is expressed in seconds. For A and C type rules this value is 0' ;
COMMENT ON COLUMN t_cov_rules.cover_pct IS 'Expected percentage of coverage for a period. The default value is zero' ;
COMMENT ON COLUMN t_cov_rules.check_delta_gap IS 'Flag that indicate if the check for delta_gap is needed. The default value is false' ;
COMMENT ON COLUMN t_cov_rules.check_cover_pct IS 'Flag that indicate if the check for delta_pct is needed. The default value is false' ;
COMMENT ON COLUMN t_cov_rules.deltawait_sec IS 'Tolerance interval. The values is expressed in seconds' ;
COMMENT ON COLUMN t_cov_rules.deltamissing_sec IS 'Indicates how long, after the end of an interval, you can wait before declare an item lost. The value is expressed in seconds' ;
COMMENT ON COLUMN t_cov_rules.creation_date IS 'Datetime that represents when the rule was created. Is automatically generated by a default to "now"' ;
COMMENT ON COLUMN t_cov_rules.last_update IS 'Datetime that represents the last change of the rule. Is automatically generated by a default to "now"' ;
COMMENT ON COLUMN t_cov_rules.author IS 'Name of the user who created the rule' ;
COMMENT ON COLUMN t_cov_rules.description IS 'Description of the rule. Can be empty' ;
COMMENT ON COLUMN t_cov_rules.fixedvaliditystart IS 'For files having validity from the beginning of the mission.' ;
COMMENT ON COLUMN t_cov_rules.fixedvaliditystop IS 'For files having validity until the end of the mission.' ;
COMMENT ON SEQUENCE t_cov_rules_id_coveragerule_seq IS 'Used to generate the primary keys of the t_cov_rules table';


/* ------------------------------
	t_cov_x_filetypes
*/ ------------------------------
COMMENT ON TABLE t_cov_x_filetypes IS 'Contains the relations between filetpes and rules. Only the filetypes listed into this table will be analyzed by functions.' ;
COMMENT ON COLUMN t_cov_x_filetypes.coveragerule_id IS 'Id of referenced rule. References id_coveragerule on t_cov_rules table.' ;
COMMENT ON COLUMN t_cov_x_filetypes.filetype_id IS 'Id of referenced file type. References id_filetype on t_filetypes table.' ;


