include ../../common/commondefs.mk


  LIBRARYNAME =	libSerialization

  VERSIONFILE = SerializableV.C

     CSOURCES =	

     CINCLUDE =	

   C++SOURCES = \
		SerializableV.C \
		ACSJsonObject.C \
		Serializable.C \
		JsonSerializable.C 

   C++INCLUDE = \
   		SerializableV.h \
		ACSJsonObject.h \
		Serializable.h \
		JsonSerializable.h 

DSODEPENDLIBS = 


COV_PATHS := $(shell pwd)/test

COV_BASE_DIR := $(shell pwd)


#empty rule, do not remove, you can add specific remotion commands
cleanspecific:
	@rm -f *.bak;


#empty rule, do not remove, you can add specific remotion commands
helpspecific:



# DO NOT DELETE
include ../../common/commonrules.mk
